// Curated episode vibes for Angel. Keys are "S.E".
// Season premieres/finales are auto-tagged in app.js — not repeated here.
window.TAG_DEFS = {
  fanfav:    {label:"Fan favorite", desc:"The ones everybody puts on their best-of list"},
  heavy:     {label:"Gut-punch", desc:"Grief, loss and the hours that hurt — 'Hero', 'A Hole in the World', 'Not Fade Away'"},
  format:    {label:"Format experiment", desc:"The show breaking its own shape — puppets, ballet, amnesia, 1952, dream logic"},
  arc:       {label:"Arc / mythology", desc:"Wolfram & Hart, the Shanshu Prophecy, Connor, Jasmine, the season-long story"},
  noir:      {label:"Case of the week", desc:"Standalone LA detective work — the show's noir mode"},
  comedy:    {label:"Comedy", desc:"The funny ones"},
  horror:    {label:"Extra creepy", desc:"Genuinely frightening — watch with the lights on"},
  flashback: {label:"Flashback", desc:"Angel's 250 years — Galway, London, the Boxer Rebellion, 1952, WWII"},
  twopart:   {label:"Two-parter", desc:"Halves of one continuous story"},
  buffyverse:{label:"Buffy crossover", desc:"Sunnydale characters, Sunnydale consequences"},
  milestone: {label:"Milestone", desc:"The 100th episode, the deaths, the hinge points of the series"},
  angel:     {label:"Angel-centric", desc:"Angel and/or Angelus gets the spotlight"},
  cordelia:  {label:"Cordelia-centric", desc:"Cordelia Chase, from vapid to visionary"},
  doyle:     {label:"Doyle-centric", desc:"Allen Francis Doyle, all nine episodes of him"},
  wesley:    {label:"Wesley-centric", desc:"Wesley Wyndam-Pryce, rogue demon hunter"},
  gunn:      {label:"Gunn-centric", desc:"Charles Gunn"},
  fred:      {label:"Fred-centric", desc:"Winifred Burkle"},
  lorne:     {label:"Lorne-centric", desc:"The Host of Caritas"},
  connor:    {label:"Connor-centric", desc:"Angel and Darla's impossible son"},
  spike:     {label:"Spike-centric", desc:"William the Bloody, in LA"},
  illyria:   {label:"Illyria-centric", desc:"The Old One wearing Fred's face"},
  darla:     {label:"Darla-centric", desc:"Darla, sire and mother"},
  faith:     {label:"Faith-centric", desc:"The other Slayer"},
  lindsey:   {label:"Lindsey-centric", desc:"Lindsey McDonald, the lawyer with the hand"},
  lilah:     {label:"Lilah-centric", desc:"Lilah Morgan, Special Projects"},
};

window.EP_TAGS = {
  "1.1":["arc","angel","doyle","cordelia"], "1.2":["noir"], "1.3":["buffyverse","spike","angel"],
  "1.4":["noir"], "1.5":["noir","cordelia","comedy","fanfav"], "1.6":["noir","comedy"],
  "1.7":["noir","doyle"], "1.8":["buffyverse","heavy","fanfav","angel","format"],
  "1.9":["arc","heavy","fanfav","milestone","doyle"], "1.10":["arc","wesley","cordelia"],
  "1.11":["noir","angel","flashback"], "1.12":["noir","cordelia"], "1.13":["noir"],
  "1.14":["noir","horror","wesley"], "1.15":["flashback","angel","heavy","fanfav"],
  "1.16":["noir","angel","lilah"], "1.17":["noir","angel","cordelia"],
  "1.18":["arc","twopart","faith","buffyverse","fanfav","wesley"],
  "1.19":["arc","twopart","faith","buffyverse","fanfav","heavy"],
  "1.20":["arc","noir","gunn"], "1.21":["arc","lindsey","fanfav"],
  "1.22":["arc","darla","lindsey","lilah","fanfav","milestone"],

  "2.1":["arc","lorne","angel","faith"], "2.2":["format","flashback","fanfav","angel","heavy","horror"],
  "2.3":["gunn","cordelia","comedy"], "2.4":["noir","arc","lilah"],
  "2.5":["arc","darla","angel","flashback","fanfav"], "2.6":["comedy","wesley","fanfav"],
  "2.7":["arc","flashback","darla","fanfav","buffyverse","milestone"],
  "2.8":["noir","gunn"], "2.9":["arc","darla","angel","heavy","fanfav"],
  "2.10":["arc","darla","angel","heavy","fanfav","milestone"],
  "2.11":["arc","angel","heavy"], "2.12":["arc","angel","noir"],
  "2.13":["comedy","lorne","noir"], "2.14":["noir","gunn","wesley","arc"],
  "2.15":["arc","angel","darla","lindsey","heavy","fanfav"],
  "2.16":["arc","angel","fanfav","heavy","milestone"],
  "2.17":["comedy","cordelia","buffyverse","fanfav"], "2.18":["arc","lindsey","fanfav"],
  "2.19":["arc","lorne","cordelia","fred"], "2.20":["arc","cordelia","format","comedy"],
  "2.21":["arc","lorne","comedy","fanfav","fred"],
  "2.22":["arc","fanfav","buffyverse","heavy","cordelia","wesley","lorne"],

  "3.1":["arc","angel","buffyverse","heavy","darla"], "3.2":["arc","cordelia","lilah"],
  "3.3":["gunn","arc","heavy","lorne"], "3.4":["comedy","angel","format"],
  "3.5":["fred","fanfav","comedy"], "3.6":["heavy","wesley","cordelia","fanfav","lilah"],
  "3.7":["arc","darla"], "3.8":["arc","darla","connor"],
  "3.9":["arc","darla","heavy","fanfav","connor","milestone"],
  "3.10":["comedy","connor","arc"], "3.11":["cordelia","format","arc","fanfav"],
  "3.12":["comedy","gunn","fred"],
  "3.13":["format","fanfav","angel","cordelia","wesley","fred","milestone"],
  "3.14":["cordelia","angel","arc"], "3.15":["arc","wesley","heavy"],
  "3.16":["arc","heavy","fanfav","wesley","connor","milestone"],
  "3.17":["arc","heavy","wesley","fanfav","angel"], "3.18":["gunn","fred"],
  "3.19":["arc","fred","connor"], "3.20":["arc","connor","fred"],
  "3.21":["arc","connor","angel","heavy"], "3.22":["arc","connor","cordelia","heavy","fanfav"],

  "4.1":["arc","angel","connor","wesley","fanfav","heavy"], "4.2":["arc","gunn","cordelia"],
  "4.3":["lorne","comedy","noir"], "4.4":["arc","cordelia","connor","lorne"],
  "4.5":["fred","arc","gunn","heavy"], "4.6":["format","comedy","fanfav","cordelia","wesley","gunn","fred"],
  "4.7":["arc","cordelia","connor","heavy"], "4.8":["arc","lilah","connor","heavy"],
  "4.9":["arc","gunn"], "4.10":["arc","format","angel","fanfav","heavy"],
  "4.11":["arc","angel","fanfav"], "4.12":["arc","lilah","heavy","wesley","angel"],
  "4.13":["arc","faith","fanfav","wesley"], "4.14":["arc","faith","angel","heavy"],
  "4.15":["arc","faith","buffyverse","fanfav","angel","flashback"],
  "4.16":["gunn","arc","cordelia"], "4.17":["arc","cordelia","connor","heavy","fanfav"],
  "4.18":["arc","fred","comedy"], "4.19":["arc","fred"], "4.20":["arc","connor","fred"],
  "4.21":["arc","angel","connor"], "4.22":["arc","lilah","connor","heavy","fanfav","milestone"],

  "5.1":["arc","angel","spike","comedy","gunn"], "5.2":["arc","spike","fanfav"],
  "5.3":["noir","angel"], "5.4":["spike","fred","horror","fanfav","heavy"],
  "5.5":["lorne","comedy"], "5.6":["format","comedy","fanfav","angel","flashback"],
  "5.7":["wesley","heavy","fanfav","arc"],
  "5.8":["arc","spike","angel","flashback","fanfav","lindsey"],
  "5.9":["comedy","format"], "5.10":["format","angel","spike","lindsey"],
  "5.11":["arc","spike","buffyverse","heavy","fanfav","gunn"],
  "5.12":["cordelia","fanfav","heavy","milestone","arc","lindsey"],
  "5.13":["flashback","angel","spike","fanfav","format"],
  "5.14":["format","comedy","fanfav","milestone","angel","fred","wesley"],
  "5.15":["heavy","fanfav","fred","wesley","arc","milestone","twopart"],
  "5.16":["heavy","arc","illyria","wesley","fanfav","twopart"],
  "5.17":["arc","lindsey","illyria","gunn","heavy"],
  "5.18":["arc","connor","wesley","fanfav","heavy"],
  "5.19":["illyria","arc","wesley"],
  "5.20":["comedy","buffyverse","flashback","spike","angel"],
  "5.21":["arc","angel","fanfav","heavy","illyria","twopart"],
  "5.22":["arc","heavy","fanfav","milestone","twopart","angel","spike","wesley","gunn","illyria","lorne"],
};
