// Doctor Who Across the Eras — chart data. Revived series only (2005–present).
// Season axis. Seasons 1–13 = TVmaze show 210 (2005 revival). Seasons 14–16 are stitched on from
// TVmaze show 72724 ("Doctor Who" 2023): 14 = the 2023 60th-anniversary specials, 15 = the 2024
// "Season 1" (with The Church on Ruby Road as 15×00), 16 = the 2025 "Season 2" (with Joy to the
// World as 16×00). Christmas/New Year specials live in the season they belong to in the watch order.
// Each entry: [label, startSeason, endSeason, bg, fg?]
const TARDIS="#003b6f", BLUE="#3aa0ff", MBLUE="#1e6fb8", LBLUE="#a8d4ff", PALE="#dcecff",
      GOLD="#f2c94c", ORANGE="#f2994a", RED="#c62828", DRED="#7f1d1d", RUST="#a4462f",
      GREEN="#2f8f5b", LGREEN="#9fdcb8", PURPLE="#6a3d9a", LPURP="#c9b3e6", TEAL="#2a9d8f",
      PINK="#f4a6b0", BROWN="#8b5a2b", TAN="#d9b382", GRAY="#7f8c9b", SILVER="#c8ccd4",
      DGRAY="#2b2f36", WHITE="#fff", BLACK="#111";

window.ERA_CATS = [
  ["showrunners","Showrunner"],
  ["doctors","The Doctor"],
  ["companions","Companions & TARDIS team"],
  ["villains","Recurring villains & monsters"],
  ["arcs","Major arcs"],
  ["recurring","Recurring characters & home bases"],
  ["format","Broadcast & format"],
];

window.ERAS = {
  showrunners: [
    ["Russell T Davies (RTD1)", 1, 4, ORANGE, BLACK],
    ["Steven Moffat", 5, 10, PURPLE, WHITE],
    ["Chris Chibnall", 11, 13, TEAL, WHITE],
    ["Russell T Davies (RTD2)", 14, 16, BLUE, BLACK],
  ],
  doctors: [
    [["Ninth — Christopher Eccleston", 1, 1, DGRAY, WHITE],
     ["Tenth — David Tennant", 2, 4, TAN, BLACK],
     ["Eleventh — Matt Smith (from 5×01)", 5, 7, BROWN, WHITE],
     ["Twelfth — Peter Capaldi (from 8×01)", 8, 10, TARDIS, WHITE],
     ["Thirteenth — Jodie Whittaker (regenerates 13×09)", 11, 13, MBLUE, WHITE],
     ["Fourteenth — David Tennant", 14, 14, TAN, BLACK],
     ["Fifteenth — Ncuti Gatwa (bi-generated 14×03)", 15, 16, GOLD, BLACK]],
    [["War Doctor — John Hurt (7×15)", 7, 7, GRAY, WHITE],
     ["First Doctor — David Bradley (10×13)", 10, 10, SILVER, BLACK],
     ["The Fugitive Doctor — Jo Martin", 12, 13, RUST, WHITE]],
  ],
  companions: [
    [["Rose Tyler", 1, 2, PINK, BLACK],
     ["Martha Jones", 3, 3, RED, WHITE],
     ["Donna Noble (debuts 2×14)", 4, 4, ORANGE, BLACK],
     ["Amy Pond (leaves 7×05)", 5, 7, RUST, WHITE],
     ["Clara Oswald (from 7×06)", 8, 9, LBLUE, BLACK],
     ["Bill Potts", 10, 10, GOLD, BLACK],
     ["Yasmin Khan", 11, 13, PURPLE, WHITE],
     ["Donna Noble returns", 14, 14, ORANGE, BLACK],
     ["Ruby Sunday", 15, 16, PINK, BLACK]],
    [["Mickey Smith", 1, 2, BROWN, WHITE],
     ["Rory Williams (from 5×06)", 5, 7, MBLUE, WHITE],
     ["Nardole", 10, 10, LGREEN, BLACK],
     ["Graham O'Brien", 11, 12, TAN, BLACK],
     ["Dan Lewis", 13, 13, TEAL, WHITE],
     ["Belinda Chandra", 16, 16, LPURP, BLACK]],
    [["Captain Jack Harkness (from 1×09)", 1, 1, GOLD, BLACK],
     ["Captain Jack (3×11–13, 4×12–13; returns 12×11)", 3, 4, GOLD, BLACK],
     ["Ryan Sinclair", 11, 12, GREEN, WHITE]],
    [["River Song (from 4×08)", 4, 7, LPURP, BLACK],
     ["River Song — The Husbands of River Song", 9, 9, LPURP, BLACK]],
  ],
  villains: [
    [["Daleks — in almost every season of the revival", 1, 13, DRED, WHITE]],
    [["Cybermen (2×05–06, 2×12–13)", 2, 2, SILVER, BLACK],
     ["Cybermen — The Next Doctor", 4, 4, SILVER, BLACK],
     ["Cybermen (6×12, 7×12, 8×11–12)", 6, 8, SILVER, BLACK],
     ["Mondasian Cybermen (10×11–12)", 10, 10, SILVER, BLACK],
     ["Cybermen (12×09–10, 13×09)", 12, 13, SILVER, BLACK]],
    [["The Master — John Simm", 3, 4, BLACK, WHITE],
     ["Missy — Michelle Gomez", 8, 10, PURPLE, WHITE],
     ["The Master — Sacha Dhawan", 12, 13, BLACK, WHITE]],
    [["Weeping Angels — 3×10 Blink", 3, 3, GRAY, WHITE],
     ["The Time of Angels (5×04–05)", 5, 5, GRAY, WHITE],
     ["The Angels Take Manhattan (7×05)", 7, 7, GRAY, WHITE],
     ["Village of the Angels (13×04)", 13, 13, GRAY, WHITE]],
    [["The Ood (2×08–09)", 2, 2, PALE, BLACK],
     ["Judoon (3×01)", 3, 3, TAN, BLACK],
     ["Sontarans (4×04–05)", 4, 4, GREEN, WHITE],
     ["Zygons (9×07–08)", 9, 9, RUST, WHITE],
     ["Judoon (12×05)", 12, 12, TAN, BLACK],
     ["Sontarans & Sea Devils (13×02, 13×08)", 13, 13, GREEN, WHITE]],
    [["Dalek Emperor", 1, 1, DRED, WHITE],
     ["Cybermen vs Daleks at Torchwood", 2, 2, SILVER, BLACK],
     ["Mr Saxon — the Master", 3, 3, BLACK, WHITE],
     ["Davros & the Reality Bomb", 4, 4, DRED, WHITE],
     ["The Alliance & the Pandorica", 5, 5, PURPLE, WHITE],
     ["The Silence", 6, 6, DGRAY, WHITE],
     ["The Great Intelligence", 7, 7, LBLUE, BLACK],
     ["Missy & the Nethersphere", 8, 8, PURPLE, WHITE],
     ["The Hybrid & the Time Lords", 9, 9, GOLD, BLACK],
     ["Missy, Simm's Master & the Mondasians", 10, 10, BLACK, WHITE],
     ["Tzim-Sha (“Tim Shaw”)", 11, 11, RUST, WHITE],
     ["The Master & the Timeless Child", 12, 12, BLACK, WHITE],
     ["Swarm, Azure & the Division", 13, 13, TEAL, WHITE],
     ["The Toymaker", 14, 14, GOLD, BLACK],
     ["Sutekh the Destroyer", 15, 15, DRED, WHITE],
     ["The Rani & Omega", 16, 16, PURPLE, WHITE]],
  ],
  arcs: [
    [["Bad Wolf", 1, 1, GOLD, BLACK],
     ["Torchwood", 2, 2, MBLUE, WHITE],
     ["Vote Saxon", 3, 3, BLACK, WHITE],
     ["The missing planets & the Medusa Cascade", 4, 4, ORANGE, BLACK],
     ["Cracks in time — “silence will fall”", 5, 6, DGRAY, WHITE],
     ["The Impossible Girl", 7, 7, LBLUE, BLACK],
     ["The Promised Land / Nethersphere", 8, 8, PURPLE, WHITE],
     ["The Hybrid", 9, 9, GOLD, BLACK],
     ["The Vault & Missy's redemption", 10, 10, LPURP, BLACK],
     ["The Timeless Child & the Division", 11, 13, TEAL, WHITE],
     ["Bi-generation & the Pantheon", 14, 14, BLUE, BLACK],
     ["“The one who waits” & Ruby's mother", 15, 15, PINK, BLACK],
     ["Mrs Flood & the Wish World", 16, 16, LPURP, BLACK]],
    [["The Time War & the last of the Time Lords", 1, 4, DRED, WHITE],
     ["The Doctor's death at Lake Silencio", 5, 6, DGRAY, WHITE],
     ["Trenzalore & the search for Gallifrey", 7, 9, GOLD, BLACK],
     ["Gallifrey burned by the Master", 12, 13, BLACK, WHITE]],
    [["Rose & the Doctor", 1, 2, PINK, BLACK],
     ["Martha's unrequited love", 3, 3, RED, WHITE],
     ["The DoctorDonna & the metacrisis", 4, 4, ORANGE, BLACK],
     ["Amy, Rory & Melody Pond", 5, 7, RUST, WHITE],
     ["Clara & Danny Pink", 8, 8, GREEN, WHITE],
     ["Clara's death & Ashildr", 9, 9, LBLUE, BLACK],
     ["Bill, Nardole & the Vault", 10, 10, GOLD, BLACK],
     ["Yaz's feelings for the Doctor", 12, 13, PURPLE, WHITE],
     ["Who is Ruby's birth mother?", 15, 15, PINK, BLACK],
     ["Belinda, Poppy & the Wish World", 16, 16, LPURP, BLACK]],
  ],
  recurring: [
    [["Jackie Tyler", 1, 2, PINK, BLACK],
     ["Jackie returns (4×12–13)", 4, 4, PINK, BLACK],
     ["Brian Williams, Rory's dad (7×02, 7×04)", 7, 7, TAN, BLACK],
     ["Carla & Cherry Sunday", 15, 16, PINK, BLACK]],
    [["Wilfred Mott (from 3×14)", 3, 4, RED, WHITE],
     ["Craig Owens (5×11, 6×12)", 5, 6, TAN, BLACK],
     ["Danny Pink", 8, 8, GREEN, WHITE],
     ["Sylvia Noble & Shaun Temple", 14, 14, ORANGE, BLACK],
     ["Mrs Flood", 15, 16, LPURP, BLACK]],
    [["UNIT (3×12–13, 4×04–05)", 3, 4, GREEN, WHITE],
     ["Kate Stewart & Osgood (from 7×04)", 7, 9, MBLUE, WHITE],
     ["UNIT (12×01–02, 13×09)", 12, 13, MBLUE, WHITE],
     ["UNIT & the UNIT Tower — Kate, Shirley, Mel", 14, 16, MBLUE, WHITE]],
    [["Sarah Jane Smith (2×03, 4×12–13)", 2, 4, TAN, BLACK],
     ["The Paternoster Gang — Vastra, Jenny & Strax", 6, 8, GREEN, WHITE],
     ["Ashildr / Me", 9, 10, GOLD, BLACK]],
    [["Powell Estate, London 2005–06", 1, 2, GRAY, WHITE],
     ["Chiswick & the Nobles", 3, 4, ORANGE, BLACK],
     ["Leadworth & Amy's house", 5, 6, LGREEN, BLACK],
     ["Coal Hill School, Shoreditch", 7, 10, LBLUE, BLACK],
     ["Sheffield", 11, 13, TEAL, WHITE],
     ["London — Ruby's flat & the UNIT Tower", 14, 16, BLUE, BLACK]],
  ],
  format: [
    [["BBC One / BBC Wales revival", 1, 13, TARDIS, WHITE],
     ["BBC / Disney+ co-production", 14, 16, BLUE, BLACK]],
    [["13 × 45-minute episodes", 1, 10, PALE, BLACK],
     ["10 × 50–70-minute episodes", 11, 12, LBLUE, BLACK],
     ["Flux — a single 6-part serial", 13, 13, GRAY, WHITE],
     ["8-episode seasons + specials", 14, 16, LGREEN, BLACK]],
    [["Christmas special every year", 1, 10, RED, WHITE],
     ["New Year's Day specials", 11, 13, DRED, WHITE],
     ["Christmas specials return", 14, 16, RED, WHITE]],
  ],
};

window.SEASON_META = {
  1:{years:"2005",showrunner:"Russell T Davies"},
  2:{years:"2006",showrunner:"Russell T Davies"},
  3:{years:"2007",showrunner:"Russell T Davies"},
  4:{years:"2008–10 · + the specials year",showrunner:"Russell T Davies"},
  5:{years:"2010",showrunner:"Steven Moffat"},
  6:{years:"2011",showrunner:"Steven Moffat"},
  7:{years:"2012–13 · + the 50th",showrunner:"Steven Moffat"},
  8:{years:"2014",showrunner:"Steven Moffat"},
  9:{years:"2015",showrunner:"Steven Moffat"},
  10:{years:"2016–17",showrunner:"Steven Moffat"},
  11:{years:"2018–19",showrunner:"Chris Chibnall"},
  12:{years:"2020–21",showrunner:"Chris Chibnall"},
  13:{years:"2021–22 · Flux + specials",showrunner:"Chris Chibnall"},
  14:{years:"2023 · the 60th specials",showrunner:"Russell T Davies"},
  15:{years:"2023–24 · billed “Season 1”",showrunner:"Russell T Davies"},
  16:{years:"2024–25 · billed “Season 2”",showrunner:"Russell T Davies"},
};
