// Curated episode vibes for Doctor Who (2005– ). Keys are "S.E" using the numbering in episodes.json:
// specials sit in the season they belong to in the watch order (e.g. 4.14–4.18 are the 2008–10 specials,
// 7.14–7.16 are The Snowmen / Day of the Doctor / Time of the Doctor, and a Christmas special that aired
// *before* its season premiere is numbered E0, e.g. 10.0 and 15.0).
// Season premieres/finales are auto-tagged in app.js — not repeated here.
window.TAG_DEFS = {
  arc:        {label:"Arc-heavy", desc:"Bad Wolf, Torchwood, Saxon, the cracks, the Silence, the Impossible Girl, the Hybrid, the Timeless Child, the Flux, the Pantheon…"},
  standalone: {label:"Classic standalone", desc:"Watchable cold — a monster, a place, a problem"},
  twoparter:  {label:"Two-parter", desc:"Part of a multi-episode story or a direct cliffhanger pair"},
  fanfav:     {label:"Fan favorite", desc:"The ones that top every best-of list"},
  heavy:      {label:"Gut-punch", desc:"Goodbyes, losses and the ones that leave a mark"},
  scary:      {label:"Genuinely scary", desc:"Blink / Midnight / The Empty Child territory — hide behind the sofa"},
  historical: {label:"Historical", desc:"Set in the past, including the celebrity historicals"},
  experiment: {label:"Format experiment", desc:"Breaks the usual shape of an episode"},
  doctorlite: {label:"Doctor-lite / companion-lite", desc:"A lead barely appears — the production's double-banking episodes"},
  xmas:       {label:"Christmas / New Year special", desc:"The festive specials, in the season they belong to"},
  regen:      {label:"Regeneration", desc:"A Doctor changes face"},
  debut:      {label:"New Doctor or companion debuts", desc:"First proper outing for a lead"},
  farewell:   {label:"A companion leaves", desc:"Exits, mind-wipes and long goodbyes"},
  multidoctor:{label:"Multi-Doctor / anniversary", desc:"More than one Doctor on screen"},
  rose:       {label:"Rose spotlight", desc:""},
  martha:     {label:"Martha spotlight", desc:""},
  donna:      {label:"Donna spotlight", desc:""},
  jack:       {label:"Captain Jack", desc:""},
  amy:        {label:"Amy spotlight", desc:""},
  rory:       {label:"Rory spotlight", desc:""},
  river:      {label:"River Song", desc:""},
  clara:      {label:"Clara spotlight", desc:""},
  bill:       {label:"Bill spotlight", desc:""},
  nardole:    {label:"Nardole", desc:""},
  fam:        {label:"Team TARDIS spotlight", desc:"Graham, Ryan, Yaz and Dan"},
  ruby:       {label:"Ruby spotlight", desc:""},
};

window.EP_TAGS = {
  "1.1":["rose","debut","standalone"], "1.2":["rose","standalone","arc"], "1.3":["historical","scary","standalone"],
  "1.4":["twoparter","rose","standalone"], "1.5":["twoparter","standalone"], "1.6":["fanfav","heavy","arc"],
  "1.7":["standalone","arc"], "1.8":["rose","heavy","fanfav"], "1.9":["twoparter","fanfav","scary","jack","historical"],
  "1.10":["twoparter","fanfav","jack","historical"], "1.11":["standalone","rose"], "1.12":["arc","twoparter","jack"],
  "1.13":["arc","twoparter","regen","heavy","fanfav","rose","jack"], "1.14":["xmas","debut","rose"],

  "2.1":["standalone","rose"], "2.2":["historical","arc","rose"], "2.3":["fanfav","heavy","rose"],
  "2.4":["fanfav","historical","standalone"], "2.5":["twoparter","arc"], "2.6":["twoparter","arc","heavy"],
  "2.7":["historical","standalone","rose"], "2.8":["twoparter","scary","fanfav"], "2.9":["twoparter","scary","fanfav"],
  "2.10":["experiment","doctorlite"], "2.11":["standalone"], "2.12":["twoparter","arc","rose"],
  "2.13":["twoparter","arc","heavy","fanfav","rose","farewell"], "2.14":["xmas","donna","debut"],

  "3.1":["martha","debut","standalone"], "3.2":["historical","martha"], "3.3":["standalone","martha"],
  "3.4":["twoparter","historical"], "3.5":["twoparter","historical"], "3.6":["standalone","martha"],
  "3.7":["standalone","scary"], "3.8":["twoparter","fanfav","heavy","historical","martha"],
  "3.9":["twoparter","fanfav","heavy","historical","martha"], "3.10":["fanfav","scary","doctorlite","experiment"],
  "3.11":["arc","jack","fanfav"], "3.12":["arc","twoparter","jack"],
  "3.13":["arc","twoparter","martha","jack","heavy","farewell"], "3.14":["xmas","heavy"],

  "4.1":["donna","debut","standalone"], "4.2":["historical","heavy","fanfav","donna"], "4.3":["standalone","donna"],
  "4.4":["twoparter","martha"], "4.5":["twoparter","martha"], "4.6":["standalone","martha"],
  "4.7":["historical","donna"], "4.8":["twoparter","river","fanfav","scary"], "4.9":["twoparter","river","fanfav","heavy"],
  "4.10":["fanfav","scary","experiment","standalone"], "4.11":["donna","fanfav","arc","doctorlite","experiment"],
  "4.12":["arc","twoparter","fanfav","rose","martha","jack"],
  "4.13":["arc","twoparter","heavy","fanfav","donna","rose","martha","jack","farewell"],
  "4.14":["xmas","historical"], "4.15":["standalone"], "4.16":["fanfav","scary","heavy","arc"],
  "4.17":["arc","twoparter","xmas"], "4.18":["arc","twoparter","regen","heavy","fanfav"],

  "5.1":["debut","amy","fanfav"], "5.2":["standalone","amy"], "5.3":["standalone","historical"],
  "5.4":["twoparter","scary","river","fanfav"], "5.5":["twoparter","scary","river","arc","amy"],
  "5.6":["historical","standalone","rory"], "5.7":["experiment","fanfav","amy","rory"],
  "5.8":["twoparter","standalone"], "5.9":["twoparter","heavy","arc","rory"],
  "5.10":["fanfav","heavy","historical","amy"], "5.11":["standalone","fanfav","doctorlite"],
  "5.12":["arc","twoparter","fanfav","river","rory"], "5.13":["arc","twoparter","fanfav","amy","rory","river"],
  "5.14":["xmas","fanfav","heavy"],

  "6.1":["arc","twoparter","river","fanfav","scary"], "6.2":["arc","twoparter","river","scary"],
  "6.3":["standalone","historical"], "6.4":["fanfav","experiment","standalone"], "6.5":["twoparter","standalone"],
  "6.6":["twoparter","arc","amy"], "6.7":["arc","fanfav","river","amy","rory"], "6.8":["arc","historical","river"],
  "6.9":["scary","standalone"], "6.10":["fanfav","heavy","amy","rory","experiment"],
  "6.11":["fanfav","heavy","scary","amy"], "6.12":["standalone"], "6.13":["arc","river","fanfav"],
  "6.14":["xmas","standalone"],

  "7.1":["arc","clara","fanfav"], "7.2":["standalone","rory"], "7.3":["historical","standalone"],
  "7.4":["standalone","amy","rory"], "7.5":["heavy","fanfav","scary","amy","rory","river","farewell"],
  "7.14":["xmas","clara","arc","debut"], "7.6":["clara","arc","standalone"], "7.7":["clara","standalone"],
  "7.8":["standalone","scary"], "7.9":["scary","standalone","fanfav"], "7.10":["standalone","arc"],
  "7.11":["historical","standalone","doctorlite"], "7.12":["standalone"], "7.13":["arc","clara","fanfav","river"],
  "7.15":["multidoctor","arc","fanfav","rose"], "7.16":["xmas","regen","arc","heavy","clara"],

  "8.1":["debut","clara","arc","fanfav"], "8.2":["standalone","clara"], "8.3":["historical","standalone"],
  "8.4":["fanfav","scary","experiment","clara"], "8.5":["standalone"], "8.6":["standalone","clara"],
  "8.7":["clara","heavy","standalone"], "8.8":["fanfav","standalone","clara"],
  "8.9":["fanfav","clara","doctorlite","experiment"], "8.10":["standalone"],
  "8.11":["arc","twoparter","heavy","clara"], "8.12":["arc","twoparter","heavy","fanfav","clara"],
  "8.13":["xmas","fanfav","scary","clara"],

  "9.1":["arc","twoparter","fanfav"], "9.2":["arc","twoparter","clara","fanfav"],
  "9.3":["twoparter","scary","standalone"], "9.4":["twoparter","experiment","standalone"],
  "9.5":["twoparter","standalone","historical"], "9.6":["historical","heavy","standalone"],
  "9.7":["twoparter","arc"], "9.8":["twoparter","fanfav","arc"], "9.9":["experiment","scary","standalone"],
  "9.10":["heavy","fanfav","clara","arc","farewell"], "9.11":["fanfav","experiment","heavy","doctorlite","arc"],
  "9.12":["arc","clara","heavy"], "9.13":["xmas","river","heavy","fanfav","nardole"],

  "10.0":["xmas","standalone","nardole"], "10.1":["bill","debut","standalone"], "10.2":["standalone","bill"],
  "10.3":["historical","bill","fanfav"], "10.4":["scary","standalone","bill"], "10.5":["fanfav","standalone","bill"],
  "10.6":["arc","fanfav","experiment","nardole"], "10.7":["arc","twoparter"], "10.8":["arc","twoparter","bill"],
  "10.9":["standalone"], "10.10":["standalone","historical"],
  "10.11":["arc","twoparter","fanfav","heavy","bill","experiment"],
  "10.12":["arc","twoparter","heavy","fanfav","bill","nardole","farewell"],
  "10.13":["xmas","regen","multidoctor","heavy","clara","bill"],

  "11.1":["debut","fam","heavy"], "11.2":["standalone","fam"], "11.3":["historical","heavy","fanfav","fam"],
  "11.4":["standalone","scary","fam"], "11.5":["standalone"], "11.6":["historical","heavy","fanfav","fam"],
  "11.7":["standalone"], "11.8":["historical","fam"], "11.9":["standalone","heavy","fam"],
  "11.10":["standalone","fam"], "11.11":["xmas","standalone","fam"],

  "12.1":["twoparter","arc","fam"], "12.2":["twoparter","arc","historical"], "12.3":["standalone"],
  "12.4":["historical","standalone"], "12.5":["arc","fanfav","jack"], "12.6":["standalone"],
  "12.7":["standalone","fam"], "12.8":["historical","fanfav","scary","arc"], "12.9":["arc","twoparter"],
  "12.10":["arc","twoparter","heavy"], "12.11":["xmas","arc","jack","fam","farewell"],

  "13.1":["arc","fam"], "13.2":["arc","historical","fam"], "13.3":["arc","experiment"],
  "13.4":["arc","scary","fanfav"], "13.5":["arc","fam"], "13.6":["arc","fam"],
  "13.7":["xmas","experiment","fanfav","standalone"], "13.8":["standalone","historical"],
  "13.9":["regen","arc","multidoctor","heavy","fanfav","farewell"],

  "14.1":["donna","arc","debut"], "14.2":["experiment","fanfav","scary","donna","heavy"],
  "14.3":["arc","regen","fanfav","donna","heavy"],

  "15.0":["xmas","debut","ruby","fanfav"], "15.1":["standalone","ruby"], "15.2":["historical","experiment","ruby"],
  "15.3":["fanfav","experiment","standalone"], "15.4":["experiment","fanfav","scary","doctorlite","ruby"],
  "15.5":["fanfav","heavy","standalone","experiment"], "15.6":["historical","standalone","ruby"],
  "15.7":["arc","twoparter","scary","ruby"], "15.8":["arc","twoparter","heavy","ruby"],

  "16.0":["xmas","standalone","heavy"], "16.1":["debut","standalone"], "16.2":["experiment","fanfav","scary"],
  "16.3":["scary","fanfav","standalone"], "16.4":["doctorlite","ruby","standalone"], "16.5":["standalone"],
  "16.6":["heavy","standalone","arc"], "16.7":["arc","twoparter"],
  "16.8":["arc","twoparter","regen","heavy","ruby","farewell"],
};
