window.TAG_DEFS = {
  fanfav:     {label:"Fan favorite", desc:""},
  heavy:      {label:"Gut-punch", desc:""},
  arc:        {label:"Main story", desc:"Moves the war, the hunt or Aang's training forward"},
  standalone: {label:"Adventure of the week", desc:"A stop on the road that mostly stands alone"},
  multipart:  {label:"Multi-part story", desc:"Winter Solstice, the Siege of the North, the Book Two finale, the Day of Black Sun, the Boiling Rock, Sozin's Comet"},
  spirit:     {label:"Spirits & past Avatars", desc:"The Spirit World, Roku, Kyoshi, Koh, the lion turtle"},
  backstory:  {label:"Backstory", desc:"Flashbacks: the Air Nomads, Zuko's banishment, Lu Ten, Sozin, Kya"},
  experiment: {label:"Format experiment", desc:"Anthology, a bison's-eye view, a fever dream, a play within the show"},
  funny:      {label:"Comedy", desc:""},
  romance:    {label:"Romance", desc:""},
  skippable:  {label:"Often skipped", desc:"Widely ranked the weakest episode"},
  aang:{label:"Aang spotlight"}, katara:{label:"Katara spotlight"}, sokka:{label:"Sokka spotlight"},
  toph:{label:"Toph spotlight"}, zuko:{label:"Zuko spotlight"}, iroh:{label:"Iroh spotlight"},
  azula:{label:"Azula spotlight"},
};

window.EP_TAGS = {
  "1.1":["arc","aang"],
  "1.2":["arc","aang","zuko"],
  "1.3":["arc","heavy","backstory","aang"],
  "1.4":["standalone","sokka"],
  "1.5":["standalone","funny","aang"],
  "1.6":["standalone","katara"],
  "1.7":["arc","multipart","spirit","aang"],
  "1.8":["fanfav","arc","multipart","spirit","aang","zuko"],
  "1.9":["standalone","funny","katara"],
  "1.10":["standalone","sokka"],
  "1.11":["standalone","skippable"],
  "1.12":["fanfav","heavy","backstory","aang","zuko"],
  "1.13":["fanfav","arc","zuko","aang"],
  "1.14":["standalone","funny"],
  "1.15":["standalone","sokka","katara"],
  "1.16":["arc","aang"],
  "1.17":["standalone","aang"],
  "1.18":["arc","romance","katara","sokka"],
  "1.19":["fanfav","arc","multipart","spirit"],
  "1.20":["fanfav","arc","multipart","spirit","heavy","sokka","zuko","iroh"],
  "2.1":["arc","aang","azula"],
  "2.2":["standalone","funny","romance"],
  "2.3":["arc","azula"],
  "2.4":["standalone","spirit"],
  "2.5":["standalone","funny"],
  "2.6":["fanfav","arc","toph"],
  "2.7":["fanfav","heavy","backstory","zuko"],
  "2.8":["fanfav","arc","azula","toph","iroh"],
  "2.9":["fanfav","arc","aang","toph","iroh","zuko"],
  "2.10":["arc","spirit","sokka"],
  "2.11":["fanfav","heavy","funny","katara","sokka"],
  "2.12":["arc","sokka"],
  "2.13":["arc","azula","toph"],
  "2.14":["arc"],
  "2.15":["fanfav","experiment","heavy","funny","iroh"],
  "2.16":["arc","experiment","heavy"],
  "2.17":["arc","heavy","zuko"],
  "2.18":["arc"],
  "2.19":["arc","multipart","spirit","aang","toph"],
  "2.20":["fanfav","arc","multipart","heavy","zuko","azula","katara","iroh"],
  "3.1":["arc","aang","zuko"],
  "3.2":["fanfav","standalone","funny","romance","aang"],
  "3.3":["standalone","katara"],
  "3.4":["fanfav","standalone","sokka"],
  "3.5":["arc","funny","zuko","azula"],
  "3.6":["arc","backstory","spirit","aang","zuko","iroh"],
  "3.7":["standalone","funny","toph","katara"],
  "3.8":["fanfav","standalone","heavy","katara"],
  "3.9":["arc","experiment","funny","aang"],
  "3.10":["fanfav","arc","multipart","sokka"],
  "3.11":["fanfav","arc","multipart","zuko","iroh","azula"],
  "3.12":["arc","zuko"],
  "3.13":["fanfav","arc","zuko","aang"],
  "3.14":["fanfav","arc","multipart","sokka","zuko"],
  "3.15":["fanfav","arc","multipart","sokka","zuko","azula"],
  "3.16":["fanfav","arc","heavy","backstory","katara","zuko","azula"],
  "3.17":["fanfav","experiment","funny"],
  "3.18":["fanfav","arc","multipart","aang"],
  "3.19":["fanfav","arc","multipart","spirit","aang","zuko","iroh"],
  "3.20":["fanfav","arc","multipart","heavy","zuko","azula","katara"],
  "3.21":["fanfav","arc","multipart","spirit","romance","aang"],
};
