// Community — episode tags. Season premieres and finales are auto-tagged by the engine, so they aren't listed here.
// Keys are the season.episode numbers used in episodes.json.
window.TAG_DEFS = {
  fanfav:      {label:"Fan favorite", desc:"The ones people rewatch first"},
  paintball:   {label:"Paintball & campus games", desc:"Paintball, the floor is lava: Greendale goes to war"},
  documentary: {label:"Documentary episode", desc:"Abed's camera, the Dean's commercial, the Ken Burns war"},
  xmas:        {label:"Christmas special", desc:"Every season through 4 gets one"},
  halloween:   {label:"Halloween", desc:"Costume parties, zombies, spooky stories"},
  darkest:     {label:"Darkest Timeline", desc:"Remedial Chaos Theory and its evil-goatee fallout"},
  animated:    {label:"Animated / puppets / 8-bit", desc:"Stop-motion, video game, felt and G.I. Joe"},
  genre:       {label:"Genre parody", desc:"The episode is secretly a different kind of movie"},
  meta:        {label:"Meta / clip show", desc:"Fake clip shows and the show talking about itself"},
  dnd:         {label:"Dungeons & Dragons"},
  bottle:      {label:"Bottle episode", desc:"The study room, locked"},
  twoparter:   {label:"Two-parter"},
  milestone:   {label:"Milestone", desc:"Arrivals, departures, graduations and deaths"},
  heartfelt:   {label:"Heartfelt", desc:"Where the jokes step aside for a minute"},
  classic:     {label:"Classic standalone", desc:"A regular week in the study room"},
  jeff:        {label:"Jeff spotlight"},
  britta:      {label:"Britta spotlight"},
  abed:        {label:"Abed spotlight"},
  troy:        {label:"Troy spotlight"},
  annie:       {label:"Annie spotlight"},
  shirley:     {label:"Shirley spotlight"},
  pierce:      {label:"Pierce spotlight"},
  chang:       {label:"Chang spotlight"},
  dean:        {label:"Dean Pelton spotlight"},
};

window.EP_TAGS = {
  // season 1
  "1.1":  ["classic","jeff"],
  "1.2":  ["classic","jeff","britta","pierce"],
  "1.3":  ["classic","jeff","abed"],
  "1.4":  ["classic","jeff","shirley","annie"],
  "1.5":  ["classic","chang"],
  "1.6":  ["classic","troy","annie"],
  "1.7":  ["halloween","jeff"],
  "1.8":  ["classic","jeff"],
  "1.9":  ["classic","annie","jeff"],
  "1.10": ["classic","chang"],
  "1.11": ["classic","pierce"],
  "1.12": ["xmas","shirley"],
  "1.13": ["classic","jeff"],
  "1.14": ["classic","troy","britta"],
  "1.15": ["classic","annie","pierce"],
  "1.16": ["classic","britta","jeff"],
  "1.17": ["classic","jeff","abed"],
  "1.18": ["classic","pierce","jeff"],
  "1.19": ["classic","jeff"],
  "1.20": ["classic","britta","pierce"],
  "1.21": ["fanfav","genre","abed"],
  "1.22": ["classic","shirley","pierce"],
  "1.23": ["fanfav","paintball"],
  "1.24": ["milestone","chang","troy"],
  "1.25": ["classic","jeff","britta","annie"],
  // season 2
  "2.1":  ["classic","jeff"],
  "2.2":  ["classic","jeff"],
  "2.3":  ["pierce","heartfelt"],
  "2.4":  ["classic","dean"],
  "2.5":  ["classic","shirley","abed"],
  "2.6":  ["fanfav","halloween","genre","troy"],
  "2.7":  ["classic","abed"],
  "2.8":  ["fanfav","bottle","annie"],
  "2.9":  ["fanfav","dean","jeff","annie"],
  "2.10": ["troy","heartfelt"],
  "2.11": ["fanfav","xmas","animated","abed","heartfelt"],
  "2.12": ["classic","shirley","chang"],
  "2.13": ["classic","pierce"],
  "2.14": ["fanfav","dnd","pierce"],
  "2.15": ["classic","britta","troy","abed"],
  "2.16": ["fanfav","documentary","pierce"],
  "2.17": ["classic","annie"],
  "2.18": ["classic","shirley","chang"],
  "2.19": ["fanfav","genre","abed"],
  "2.20": ["classic","troy"],
  "2.21": ["fanfav","meta"],
  "2.22": ["milestone","shirley","chang"],
  "2.23": ["fanfav","paintball","twoparter"],
  "2.24": ["fanfav","paintball","twoparter","pierce"],
  // season 3
  "3.1":  ["classic","jeff"],
  "3.2":  ["classic","annie","britta"],
  "3.3":  ["classic","jeff"],
  "3.4":  ["fanfav","darkest"],
  "3.5":  ["fanfav","halloween","genre","britta"],
  "3.6":  ["classic","pierce","troy"],
  "3.7":  ["classic","annie"],
  "3.8":  ["fanfav","documentary","dean"],
  "3.9":  ["classic","annie","abed","shirley"],
  "3.10": ["xmas","genre"],
  "3.11": ["milestone","shirley"],
  "3.12": ["classic","jeff"],
  "3.13": ["twoparter","troy","abed"],
  "3.14": ["fanfav","documentary","twoparter","troy","abed"],
  "3.15": ["classic","britta"],
  "3.16": ["heartfelt","abed","annie"],
  "3.17": ["genre","troy","abed"],
  "3.18": ["classic","britta"],
  "3.19": ["fanfav","meta","abed"],
  "3.20": ["fanfav","animated","pierce"],
  "3.21": ["genre","chang"],
  "3.22": ["milestone","darkest","troy"],
  // season 4
  "4.1":  ["classic","jeff"],
  "4.2":  ["halloween","pierce"],
  "4.3":  ["classic","troy","abed"],
  "4.4":  ["classic","chang"],
  "4.5":  ["classic","jeff","shirley"],
  "4.6":  ["documentary","chang"],
  "4.7":  ["classic","dean","pierce"],
  "4.8":  ["classic","britta"],
  "4.9":  ["animated"],
  "4.10": ["xmas","jeff"],
  "4.11": ["classic","troy","abed"],
  "4.12": ["classic","chang","abed"],
  "4.13": ["milestone","darkest","jeff"],
  // season 5
  "5.1":  ["milestone","jeff"],
  "5.2":  ["classic","jeff"],
  "5.3":  ["genre","jeff","annie"],
  "5.4":  ["fanfav","bottle","milestone","pierce"],
  "5.5":  ["fanfav","paintball","milestone","heartfelt","troy","abed"],
  "5.6":  ["classic","annie"],
  "5.7":  ["classic","britta"],
  "5.8":  ["fanfav","meta","dean"],
  "5.9":  ["classic","abed","annie"],
  "5.10": ["fanfav","dnd"],
  "5.11": ["fanfav","animated","jeff"],
  "5.12": ["twoparter","dean"],
  "5.13": ["twoparter"],
  // season 6
  "6.1":  ["milestone","shirley"],
  "6.2":  ["classic","dean","jeff"],
  "6.3":  ["classic","abed"],
  "6.4":  ["classic","dean","chang"],
  "6.5":  ["classic","jeff"],
  "6.6":  ["classic","jeff"],
  "6.7":  ["classic","britta"],
  "6.8":  ["genre","abed","chang"],
  "6.9":  ["genre","jeff"],
  "6.10": ["genre","abed"],
  "6.11": ["paintball"],
  "6.12": ["classic","abed"],
  "6.13": ["fanfav","meta","heartfelt","shirley"],
};
