// Gilmore Girls — episode tags. Season premieres and finales are auto-tagged by the engine, so they aren't listed here.
// Keys are the season.episode numbers used in episodes.json. Character tags (Dean, Jess, Logan, Christopher, Lane,
// Paris, Friday dinner) follow who the TVmaze synopsis puts at the centre of the episode; the rest are hand-picked.
window.TAG_DEFS = {
  fanfav:      {label:"Fan favorite", desc:"The ones people rewatch first"},
  heavy:       {label:"Gut-punch", desc:"Stars Hollow stops being cosy"},
  milestone:   {label:"Milestone", desc:"Firsts, lasts, weddings, arrivals"},
  fight:       {label:"Lorelai vs. Rory", desc:"Mother and daughter at odds"},
  estranged:   {label:"The estrangement", desc:"Season 6's not-speaking stretch, 6×01–6×08"},
  lukelorelai: {label:"Luke & Lorelai", desc:"The slow burn and everything after"},
  dean:        {label:"Dean", desc:"Rory and Dean Forester"},
  jess:        {label:"Jess", desc:"Rory and Jess Mariano"},
  logan:       {label:"Logan", desc:"Rory and Logan Huntzberger"},
  christopher: {label:"Christopher", desc:"Rory's father, Lorelai's first love"},
  friday:      {label:"Friday night dinner", desc:"Hartford, the maid of the week, and the deal"},
  town:        {label:"Stars Hollow event", desc:"Town meetings, festivals, marathons and Taylor"},
  holiday:     {label:"Holidays", desc:"Christmas, Thanksgiving, Easter, Valentine's"},
  birthday:    {label:"Birthday episode"},
  lane:        {label:"Lane spotlight"},
  paris:       {label:"Paris spotlight"},
  classic:     {label:"Classic standalone", desc:"A regular week of coffee and pop-culture references"},
};
window.EP_TAGS = {
  // season 1
  "1.1":   ["fanfav", "dean", "friday"],
  "1.2":   ["milestone"],
  "1.3":   ["fight", "friday"],
  "1.4":   ["paris"],
  "1.5":   ["dean"],
  "1.6":   ["birthday"],
  "1.7":   ["dean"],
  "1.8":   ["dean", "town", "lane"],
  "1.9":   ["fight", "dean"],
  "1.10":  ["fight", "dean", "holiday", "lane"],
  "1.11":  ["paris"],
  "1.12":  ["lukelorelai", "dean", "lane"],
  "1.13":  ["lane", "paris"],
  "1.14":  ["dean", "christopher"],
  "1.15":  ["christopher", "friday"],
  "1.16":  ["dean", "friday"],
  "1.17":  ["dean", "lane"],
  "1.18":  ["paris"],
  "1.19":  ["classic"],
  "1.20":  ["fight", "dean", "lane"],
  "1.21":  ["fanfav", "lukelorelai", "dean", "town", "paris"],
  // season 2
  "2.1":   ["dean", "lane"],
  "2.2":   ["dean"],
  "2.3":   ["christopher"],
  "2.4":   ["fanfav", "lukelorelai", "lane"],
  "2.5":   ["milestone", "jess", "paris"],
  "2.6":   ["christopher"],
  "2.7":   ["paris"],
  "2.8":   ["jess"],
  "2.9":   ["lukelorelai", "dean", "paris"],
  "2.10":  ["fanfav", "dean", "jess"],
  "2.11":  ["fight", "lane", "paris"],
  "2.12":  ["paris"],
  "2.13":  ["lukelorelai", "dean", "jess", "town", "lane"],
  "2.14":  ["christopher", "friday"],
  "2.15":  ["dean", "jess"],
  "2.16":  ["dean", "jess", "paris"],
  "2.17":  ["jess", "town"],
  "2.18":  ["dean", "jess"],
  "2.19":  ["heavy", "lukelorelai", "jess", "christopher", "town"],
  "2.20":  ["dean", "jess", "lane"],
  "2.21":  ["fanfav", "milestone", "lukelorelai", "jess", "christopher"],
  "2.22":  ["fanfav", "milestone", "lukelorelai", "jess", "christopher", "paris"],
  // season 3
  "3.1":   ["dean", "jess", "christopher", "town", "paris"],
  "3.2":   ["jess", "christopher", "friday", "paris"],
  "3.3":   ["dean", "lane", "paris"],
  "3.4":   ["jess", "lane"],
  "3.5":   ["jess"],
  "3.6":   ["jess"],
  "3.7":   ["fanfav", "dean", "jess", "town"],
  "3.8":   ["dean", "jess"],
  "3.9":   ["fanfav", "dean", "jess", "holiday", "lane", "paris"],
  "3.10":  ["dean", "jess", "town", "birthday", "paris"],
  "3.11":  ["paris"],
  "3.12":  ["lane", "paris"],
  "3.13":  ["dean", "jess", "christopher", "paris"],
  "3.14":  ["jess", "friday", "lane"],
  "3.15":  ["dean", "jess", "town", "lane"],
  "3.16":  ["paris"],
  "3.17":  ["fanfav", "milestone", "lukelorelai", "jess", "paris"],
  "3.18":  ["jess", "birthday"],
  "3.19":  ["dean", "jess", "friday", "lane"],
  "3.20":  ["dean", "jess", "lane"],
  "3.21":  ["heavy", "jess"],
  "3.22":  ["fanfav", "milestone", "jess"],
  // season 4
  "4.1":   ["fight", "friday"],
  "4.2":   ["milestone", "paris"],
  "4.3":   ["classic"],
  "4.4":   ["milestone", "dean"],
  "4.5":   ["lukelorelai", "jess"],
  "4.6":   ["classic"],
  "4.7":   ["town", "lane"],
  "4.8":   ["friday", "lane"],
  "4.9":   ["friday", "paris"],
  "4.10":  ["lane", "paris"],
  "4.11":  ["lukelorelai", "lane"],
  "4.12":  ["jess", "lane", "paris"],
  "4.13":  ["jess", "town"],
  "4.14":  ["dean", "lane", "paris"],
  "4.15":  ["lukelorelai", "dean", "lane", "paris"],
  "4.16":  ["heavy", "milestone"],
  "4.17":  ["paris"],
  "4.18":  ["dean", "town", "holiday", "lane"],
  "4.19":  ["friday", "lane", "paris"],
  "4.20":  ["dean", "jess", "paris"],
  "4.21":  ["dean", "jess", "friday", "town", "lane"],
  "4.22":  ["fanfav", "lukelorelai", "dean"],
  // season 5
  "5.1":   ["fight", "lukelorelai", "dean"],
  "5.2":   ["dean", "lane"],
  "5.3":   ["fanfav", "milestone", "lukelorelai", "logan", "town", "paris"],
  "5.4":   ["dean", "town", "lane", "paris"],
  "5.5":   ["dean", "lane"],
  "5.6":   ["logan", "christopher", "friday", "paris"],
  "5.7":   ["fanfav", "lukelorelai", "logan", "lane"],
  "5.8":   ["lukelorelai", "dean", "logan", "lane"],
  "5.9":   ["christopher", "paris"],
  "5.10":  ["logan", "paris"],
  "5.11":  ["christopher"],
  "5.12":  ["logan", "christopher"],
  "5.13":  ["fanfav", "milestone", "lukelorelai", "logan", "christopher"],
  "5.14":  ["heavy", "lukelorelai", "logan"],
  "5.15":  ["logan", "town"],
  "5.16":  ["lukelorelai", "lane"],
  "5.17":  ["logan"],
  "5.18":  ["lane", "paris"],
  "5.19":  ["logan"],
  "5.20":  ["logan"],
  "5.21":  ["classic"],
  "5.22":  ["fanfav", "heavy", "fight", "lukelorelai"],
  // season 6
  "6.1":   ["estranged", "lukelorelai"],
  "6.2":   ["estranged"],
  "6.3":   ["estranged", "logan", "lane"],
  "6.4":   ["estranged"],
  "6.5":   ["estranged", "paris"],
  "6.6":   ["estranged", "town"],
  "6.7":   ["estranged", "birthday"],
  "6.8":   ["fanfav", "estranged", "jess"],
  "6.9":   ["milestone"],
  "6.10":  ["lukelorelai", "holiday", "lane"],
  "6.11":  ["lane"],
  "6.12":  ["milestone", "lukelorelai", "town", "paris"],
  "6.13":  ["logan", "friday"],
  "6.14":  ["paris"],
  "6.15":  ["logan", "holiday"],
  "6.16":  ["logan"],
  "6.17":  ["lane"],
  "6.18":  ["jess", "logan"],
  "6.19":  ["fanfav", "milestone", "lane"],
  "6.20":  ["logan", "birthday"],
  "6.21":  ["logan", "paris"],
  "6.22":  ["heavy", "lukelorelai", "logan", "town"],
  // season 7
  "7.1":   ["logan"],
  "7.2":   ["lane"],
  "7.3":   ["friday"],
  "7.4":   ["christopher"],
  "7.5":   ["christopher", "town"],
  "7.6":   ["christopher"],
  "7.7":   ["christopher", "lane"],
  "7.8":   ["milestone", "lukelorelai", "christopher"],
  "7.9":   ["christopher"],
  "7.10":  ["logan", "christopher", "holiday"],
  "7.11":  ["lukelorelai", "christopher", "holiday", "lane"],
  "7.12":  ["lukelorelai", "christopher"],
  "7.13":  ["heavy", "logan", "christopher"],
  "7.14":  ["classic"],
  "7.15":  ["logan", "christopher"],
  "7.16":  ["logan", "lane"],
  "7.17":  ["logan", "lane"],
  "7.18":  ["lukelorelai", "town"],
  "7.19":  ["lukelorelai", "paris"],
  "7.20":  ["fanfav", "lukelorelai", "logan", "town"],
  "7.21":  ["milestone", "logan"],
  "7.22":  ["fanfav", "lukelorelai"],
};
