// The Office (US) — episode tags. Season premieres and finales are auto-tagged by the engine, so they aren't listed here.
// Keys are TVmaze's season.episode numbers (hour-longs are split into (1)/(2), e.g. "Goodbye, Michael" = 7.22 + 7.23).
window.TAG_DEFS = {
  fanfav:     {label:"Fan favorite", desc:"The ones people rewatch first"},
  cringe:     {label:"Peak cringe", desc:"Michael at his most unbearable — watch through your fingers"},
  heart:      {label:"Heart", desc:"The episodes that earn the tears"},
  jimpam:     {label:"Jim & Pam", desc:"The slow burn, the romance, the marriage"},
  jimdwight:  {label:"Jim vs. Dwight", desc:"Pranks, rivalries and the occasional truce"},
  michael:    {label:"Michael spotlight"},
  dwight:     {label:"Dwight spotlight"},
  andy:       {label:"Andy spotlight"},
  corporate:  {label:"Corporate & the company", desc:"Mergers, buyouts, bosses from New York and Tallahassee"},
  outing:     {label:"Out of the office", desc:"Field trips, parties and road trips"},
  holiday:    {label:"Holidays", desc:"Christmas, Halloween, Valentine's and the rest"},
  twoparter:  {label:"Hour-long (two parts)", desc:"Aired as one hour; TVmaze splits it into (1)/(2)"},
  milestone:  {label:"Milestone", desc:"Arrivals, departures and the days that changed the show"},
  classic:    {label:"Classic standalone", desc:"A regular day at Dunder Mifflin Scranton"},
};

window.EP_TAGS = {
  // season 1
  "1.1":   ["jimdwight"],
  "1.2":   ["fanfav", "cringe", "michael"],
  "1.3":   ["jimpam", "michael"],
  "1.4":   ["jimdwight"],
  "1.5":   ["michael"],
  "1.6":   ["classic"],
  // season 2
  "2.1":   ["fanfav", "michael"],
  "2.2":   ["cringe", "michael"],
  "2.3":   ["classic"],
  "2.4":   ["fanfav", "michael"],
  "2.5":   ["holiday"],
  "2.6":   ["classic"],
  "2.7":   ["michael"],
  "2.8":   ["michael"],
  "2.9":   ["classic"],
  "2.10":  ["fanfav", "jimpam", "holiday"],
  "2.11":  ["fanfav", "jimpam", "outing"],
  "2.12":  ["fanfav", "michael", "dwight"],
  "2.13":  ["jimpam"],
  "2.14":  ["classic"],
  "2.15":  ["classic"],
  "2.16":  ["jimpam", "holiday"],
  "2.17":  ["dwight"],
  "2.18":  ["classic"],
  "2.19":  ["michael"],
  "2.20":  ["classic"],
  "2.21":  ["michael"],
  "2.22":  ["fanfav", "heart", "jimpam"],
  // season 3
  "3.1":   ["fanfav", "cringe", "jimpam"],
  "3.2":   ["outing"],
  "3.3":   ["michael", "dwight"],
  "3.4":   ["cringe", "michael"],
  "3.5":   ["dwight"],
  "3.6":   ["cringe", "michael", "holiday"],
  "3.7":   ["corporate"],
  "3.8":   ["jimpam", "andy", "corporate", "milestone"],
  "3.9":   ["classic"],
  "3.10":  ["twoparter", "fanfav", "jimpam", "outing", "holiday"],
  "3.11":  ["twoparter", "fanfav", "jimpam", "outing", "holiday"],
  "3.12":  ["michael"],
  "3.13":  ["dwight", "outing"],
  "3.14":  ["classic"],
  "3.15":  ["michael"],
  "3.16":  ["classic"],
  "3.17":  ["michael", "outing"],
  "3.18":  ["outing"],
  "3.19":  ["andy", "milestone"],
  "3.20":  ["fanfav", "michael"],
  "3.21":  ["classic"],
  "3.22":  ["classic"],
  "3.23":  ["fanfav", "heart", "jimpam", "outing"],
  "3.24":  ["twoparter", "fanfav", "jimpam", "michael", "corporate"],
  "3.25":  ["twoparter", "fanfav", "heart", "jimpam", "michael", "corporate"],
  // season 4
  "4.1":   ["twoparter", "fanfav", "cringe", "jimpam"],
  "4.2":   ["twoparter", "fanfav", "cringe", "jimpam"],
  "4.3":   ["twoparter", "jimpam", "corporate"],
  "4.4":   ["twoparter", "corporate"],
  "4.5":   ["twoparter", "corporate"],
  "4.6":   ["twoparter", "andy", "corporate"],
  "4.7":   ["twoparter", "jimpam", "michael", "outing"],
  "4.8":   ["twoparter", "jimpam", "michael", "andy", "outing"],
  "4.9":   ["fanfav", "michael"],
  "4.10":  ["dwight", "corporate"],
  "4.11":  ["michael", "outing"],
  "4.12":  ["classic"],
  "4.13":  ["fanfav", "cringe", "jimpam", "michael", "outing"],
  "4.14":  ["classic"],
  "4.15":  ["outing"],
  "4.16":  ["classic"],
  "4.17":  ["outing"],
  "4.18":  ["twoparter", "michael"],
  "4.19":  ["twoparter", "michael"],
  // season 5
  "5.1":   ["twoparter", "jimpam"],
  "5.2":   ["twoparter", "heart", "jimpam", "milestone"],
  "5.3":   ["classic"],
  "5.4":   ["cringe"],
  "5.5":   ["michael"],
  "5.6":   ["michael"],
  "5.7":   ["classic"],
  "5.8":   ["outing"],
  "5.9":   ["classic"],
  "5.10":  ["classic"],
  "5.11":  ["holiday"],
  "5.12":  ["fanfav", "dwight"],
  "5.13":  ["classic"],
  "5.14":  ["twoparter", "fanfav", "cringe", "dwight"],
  "5.15":  ["twoparter", "fanfav", "cringe", "dwight"],
  "5.16":  ["twoparter", "michael", "outing"],
  "5.17":  ["twoparter", "heart", "michael", "outing"],
  "5.18":  ["classic"],
  "5.19":  ["classic"],
  "5.20":  ["michael", "corporate", "milestone"],
  "5.21":  ["fanfav", "michael", "corporate", "milestone"],
  "5.22":  ["michael", "corporate"],
  "5.23":  ["michael", "corporate"],
  "5.24":  ["michael", "corporate"],
  "5.25":  ["fanfav", "jimpam", "michael", "corporate", "milestone"],
  "5.26":  ["corporate"],
  "5.27":  ["fanfav"],
  "5.28":  ["outing"],
  // season 6
  "6.1":   ["classic"],
  "6.2":   ["corporate"],
  "6.3":   ["corporate"],
  "6.4":   ["twoparter", "fanfav", "heart", "jimpam", "outing", "milestone"],
  "6.5":   ["twoparter", "fanfav", "heart", "jimpam", "outing", "milestone"],
  "6.6":   ["classic"],
  "6.7":   ["classic"],
  "6.8":   ["classic"],
  "6.9":   ["jimdwight"],
  "6.10":  ["fanfav"],
  "6.11":  ["corporate"],
  "6.12":  ["cringe", "michael"],
  "6.13":  ["holiday"],
  "6.14":  ["corporate"],
  "6.15":  ["corporate", "milestone"],
  "6.16":  ["corporate", "holiday"],
  "6.17":  ["twoparter", "heart", "jimpam", "milestone"],
  "6.18":  ["twoparter", "heart", "jimpam", "milestone"],
  "6.19":  ["holiday"],
  "6.20":  ["classic"],
  "6.21":  ["michael"],
  "6.22":  ["andy"],
  "6.23":  ["classic"],
  "6.24":  ["michael"],
  "6.25":  ["jimpam", "michael"],
  "6.26":  ["corporate"],
  // season 7
  "7.1":   ["classic"],
  "7.2":   ["classic"],
  "7.3":   ["andy", "outing"],
  "7.4":   ["classic"],
  "7.5":   ["classic"],
  "7.6":   ["holiday"],
  "7.7":   ["outing"],
  "7.8":   ["classic"],
  "7.9":   ["corporate"],
  "7.10":  ["classic"],
  "7.11":  ["twoparter", "michael", "holiday"],
  "7.12":  ["twoparter", "jimdwight", "michael", "holiday"],
  "7.13":  ["michael"],
  "7.14":  ["classic"],
  "7.15":  ["classic"],
  "7.16":  ["michael", "holiday"],
  "7.17":  ["fanfav", "michael"],
  "7.18":  ["classic"],
  "7.19":  ["michael", "milestone"],
  "7.20":  ["corporate", "milestone"],
  "7.21":  ["heart", "michael"],
  "7.22":  ["twoparter", "fanfav", "heart", "michael", "milestone"],
  "7.23":  ["twoparter", "fanfav", "heart", "michael", "milestone"],
  "7.24":  ["classic"],
  "7.25":  ["dwight"],
  "7.26":  ["twoparter", "corporate"],
  "7.27":  ["twoparter", "corporate"],
  // season 8
  "8.1":   ["andy", "corporate"],
  "8.2":   ["andy"],
  "8.3":   ["classic"],
  "8.4":   ["andy", "outing"],
  "8.5":   ["holiday"],
  "8.6":   ["classic"],
  "8.7":   ["jimpam"],
  "8.8":   ["outing"],
  "8.9":   ["classic"],
  "8.10":  ["holiday"],
  "8.11":  ["classic"],
  "8.12":  ["outing"],
  "8.13":  ["jimpam"],
  "8.14":  ["dwight", "corporate", "outing"],
  "8.15":  ["dwight", "corporate", "outing"],
  "8.16":  ["corporate", "outing"],
  "8.17":  ["corporate", "outing"],
  "8.18":  ["dwight", "corporate", "outing"],
  "8.19":  ["andy", "milestone"],
  "8.20":  ["classic"],
  "8.21":  ["andy", "corporate"],
  "8.22":  ["outing"],
  "8.23":  ["jimdwight", "corporate"],
  "8.24":  ["andy", "corporate"],
  // season 9
  "9.1":   ["milestone"],
  "9.2":   ["jimpam", "outing"],
  "9.3":   ["andy"],
  "9.4":   ["outing"],
  "9.5":   ["holiday"],
  "9.6":   ["jimdwight", "andy"],
  "9.7":   ["classic"],
  "9.8":   ["classic"],
  "9.9":   ["dwight", "holiday"],
  "9.10":  ["classic"],
  "9.11":  ["dwight"],
  "9.12":  ["jimpam"],
  "9.13":  ["dwight"],
  "9.14":  ["classic"],
  "9.15":  ["jimpam", "holiday"],
  "9.16":  ["jimpam", "andy"],
  "9.17":  ["dwight", "outing"],
  "9.18":  ["classic"],
  "9.19":  ["classic"],
  "9.20":  ["classic"],
  "9.21":  ["jimpam", "jimdwight", "dwight", "andy", "corporate", "milestone"],
  "9.22":  ["twoparter", "fanfav", "heart", "jimpam", "dwight", "andy", "milestone"],
  "9.23":  ["twoparter", "fanfav", "heart", "jimpam", "dwight", "andy", "milestone"],
  "9.24":  ["twoparter", "fanfav", "heart", "outing"],
  "9.25":  ["twoparter", "fanfav", "heart", "outing"],
};
