// The Walking Dead on skipto.tv — chart data. AMC main series only (2010–2022), 11 seasons, 177 episodes.
// Season axis. Bars are drawn at season granularity; mid-season arrivals and exits are noted in the label
// with the exact episode (e.g. "Rick Grimes (leaves 9×05)"), the way the reference packages do it.
// Each entry: [label, startSeason, endSeason, bg, fg?]
const BLOOD="#7f1d1d", RUST="#a4462f", RED="#c0392b", BRICK="#8b3a2f", CRIM="#d1495b",
      OLIVE="#6f8f2f", MOSS="#3f6b34", ROT="#8fae3f", PALEG="#c7d99a", SWAMP="#26402a",
      RUSTY="#c97b34", AMBER="#e0a533", TAN="#d9b382", BROWN="#7a5230", SAND="#e2d3b3",
      SLATE="#4a5560", STEEL="#78889a", ASH="#b7bfc7", CHAR="#22262b", NIGHT="#14171b",
      TEAL="#2a7f7a", NAVY="#2c4a6e", PLUM="#6a3d6a", PINK="#d98fa5", WHITE="#fff", BLACK="#111";

window.ERA_CATS = [
  ["eras","Showrunner & format"],
  ["places","Locations & home bases"],
  ["originals","The originals — Rick's group"],
  ["roster","The communities & later arrivals"],
  ["villains","Big bads & threats"],
  ["arcs","Major arcs"],
];

window.ERAS = {
  eras: [
    [["Frank Darabont", 1, 1, BLOOD, WHITE],
     ["Glen Mazzara (from 2×02)", 2, 3, RUST, WHITE],
     ["Scott M. Gimple", 4, 8, OLIVE, BLACK],
     ["Angela Kang", 9, 11, TEAL, WHITE]],
    [["AMC · Sunday nights · 2010–2022", 1, 11, CHAR, WHITE]],
    [["6 episodes", 1, 1, SAND, BLACK],
     ["13 episodes", 2, 2, TAN, BLACK],
     ["16 episodes, split 8 + 8", 3, 9, ASH, BLACK],
     ["16 + 6 pandemic-delayed bonus episodes", 10, 10, STEEL, WHITE],
     ["24 episodes in three 8-episode parts", 11, 11, SLATE, WHITE]],
    [["Morgan → Fear the Walking Dead (8×16)", 8, 8, PLUM, WHITE],
     ["Jadis/Anne → The Walking Dead: World Beyond (9×05)", 9, 9, PLUM, WHITE],
     ["Rick & Michonne → The Ones Who Live (9×05 / 10×13)", 10, 10, NAVY, WHITE],
     ["Maggie & Negan → Dead City · Daryl → Daryl Dixon (11×24)", 11, 11, NAVY, WHITE]],
  ],

  places: [
    [["Atlanta camp & the CDC", 1, 1, RUSTY, BLACK],
     ["Hershel's farm", 2, 2, PALEG, BLACK],
     ["The prison (falls 4×08)", 3, 4, STEEL, WHITE],
     ["Alexandria Safe-Zone (from 5×12)", 5, 11, MOSS, WHITE]],
    [["Woodbury", 3, 3, BRICK, WHITE],
     ["Scattered on the road → Terminus (4×09–5×03)", 4, 5, BROWN, WHITE],
     ["The Hilltop (6×11; burns 10×12)", 6, 10, PALEG, BLACK],
     ["The Commonwealth (from 11×10)", 11, 11, AMBER, BLACK]],
    [["Atlanta — the department store & the tank", 1, 1, TAN, BLACK],
     ["The Sanctuary — Negan's factory (6×16–9×05)", 6, 9, CHAR, WHITE],
     ["Meridian — the Reapers (11×05–11×08)", 11, 11, SWAMP, WHITE]],
    [["Fort Benning — the place they never reach", 1, 2, SAND, BLACK],
     ["The Kingdom (7×02–9×16)", 7, 9, PLUM, WHITE],
     ["The Tower & the fall of the Hilltop", 10, 10, SLATE, WHITE]],
    [["Grady Memorial Hospital, Atlanta (5×04–5×08)", 5, 5, ASH, BLACK],
     ["Oceanside (from 7×15)", 7, 11, TEAL, WHITE]],
    [["The tombs & the cell blocks", 3, 4, NIGHT, WHITE],
     ["The Scavengers' junkyard (7×10–8×16)", 7, 8, STEEL, WHITE],
     ["The Whisperers' border & the guardians", 9, 10, SWAMP, WHITE],
     ["Riverbend & the Commonwealth estates", 11, 11, SAND, BLACK]],
  ],

  originals: [
    [["Rick Grimes — Andrew Lincoln (leaves 9×05)", 1, 9, BLOOD, WHITE],
     ["Rick returns (11×24)", 11, 11, BLOOD, WHITE]],
    [["Daryl Dixon — Norman Reedus (all 177 episodes)", 1, 11, BROWN, WHITE]],
    [["Carol Peletier — Melissa McBride", 1, 11, RUSTY, BLACK]],
    [["Glenn Rhee — Steven Yeun (dies 7×01)", 1, 7, MOSS, WHITE],
     ["Siddiq (8×06; dies 10×08)", 8, 10, TEAL, WHITE],
     ["Mercer (from 11×10)", 11, 11, AMBER, BLACK]],
    [["Carl Grimes (dies 8×09)", 1, 8, NAVY, WHITE],
     ["Lydia (from 9×10)", 9, 11, ASH, BLACK]],
    [["Lori Grimes (dies 3×04)", 1, 3, PINK, BLACK],
     ["Judith Grimes (born 3×04)", 4, 11, SAND, BLACK]],
    [["Shane Walsh (dies 2×12)", 1, 2, CHAR, WHITE],
     ["Michonne — Danai Gurira (arrives 2×13, leaves 10×13)", 3, 10, PLUM, WHITE]],
    [["Dale Horvath (dies 2×11)", 1, 2, TAN, BLACK],
     ["Tyreese (dies 5×09)", 3, 5, SLATE, WHITE],
     ["Ezekiel (from 7×02)", 7, 11, PLUM, WHITE]],
    [["T-Dog (dies 3×04)", 1, 3, BRICK, WHITE],
     ["Abraham Ford (dies 7×01)", 4, 7, RUSTY, BLACK],
     ["Alden (8×11; dies 11×17)", 8, 11, ASH, BLACK]],
    [["Andrea (dies 3×16)", 1, 3, PALEG, BLACK],
     ["Eugene Porter (from 4×10)", 4, 11, OLIVE, BLACK]],
    [["Sophia Peletier (dies 2×07)", 1, 2, PINK, BLACK],
     ["Sasha Williams (dies 7×16)", 3, 7, CRIM, WHITE],
     ["Magna, Yumiko, Connie, Kelly & Luke (from 9×06)", 9, 11, STEEL, WHITE]],
    [["Amy, Jim, Jacqui & Ed — the Atlanta camp dead", 1, 1, ASH, BLACK],
     ["Maggie Greene/Rhee (from 2×02; away 10×01–10×15)", 2, 11, MOSS, WHITE]],
    [["Merle — left on the roof (1×02)", 1, 1, RED, WHITE],
     ["Merle Dixon at Woodbury (dies 3×15)", 3, 3, RED, WHITE],
     ["Father Gabriel Stokes (from 5×02)", 5, 11, NIGHT, WHITE]],
  ],

  roster: [
    [["Hershel Greene (dies 4×08)", 2, 4, PALEG, BLACK],
     ["Aaron (from 5×12)", 5, 11, TEAL, WHITE]],
    [["Beth Greene (dies 5×08)", 2, 5, SAND, BLACK],
     ["Denise Cloyd (dies 6×14)", 6, 6, PINK, BLACK],
     ["Jerry (from 7×02)", 7, 11, AMBER, BLACK]],
    [["Otis & Patricia — Hershel's farm", 2, 2, TAN, BLACK],
     ["Rosita Espinosa (4×10; dies 11×24)", 4, 11, CRIM, WHITE]],
    [["Oscar & Axel — the prison inmates", 3, 3, SLATE, WHITE],
     ["Tara Chambler (4×07; dies 9×15)", 4, 9, OLIVE, BLACK],
     ["Elijah & the Oceanside crew (from 10×17)", 10, 11, MOSS, WHITE]],
    [["Bob Stookey (dies 5×03)", 4, 5, BROWN, WHITE],
     ["Gregory of the Hilltop (hanged 9×02)", 6, 9, TAN, BLACK],
     ["Virgil (from 10×04)", 10, 11, STEEL, WHITE]],
    [["Noah & the wards of Grady (5×04–5×14)", 5, 5, ASH, BLACK],
     ["Dwight (6×06; leaves 9×08 → Fear)", 6, 9, RUST, WHITE],
     ["Dante — the mole (10×01–10×07)", 10, 10, SWAMP, WHITE]],
    [["Deanna, Jessie, Aiden & Spencer Monroe", 5, 7, PLUM, WHITE],
     ["Princess — Juanita Sanchez (from 10×20)", 10, 11, PINK, BLACK]],
    [["Enid (5×12; dies 9×15)", 5, 9, PALEG, BLACK],
     ["Gamma / Mary (10×02–10×12)", 10, 10, ASH, BLACK]],
    [["Jesus / Paul Rovia (6×11; dies 9×08)", 6, 9, MOSS, WHITE],
     ["Leah (10×18; dies 11×16)", 10, 11, SWAMP, WHITE]],
    [["Randall & the men from Nebraska", 2, 2, BRICK, WHITE],
     ["Negan — Jeffrey Dean Morgan (from 6×16)", 6, 11, BLOOD, WHITE]],
    [["Sherry & the Saviors' wives (6×15–7×11)", 6, 7, CRIM, WHITE],
     ["Georgie (8×12)", 8, 8, SAND, BLACK],
     ["Tomi & the Commonwealth arrivals", 11, 11, AMBER, BLACK]],
    [["Jadis / Anne (7×10; leaves 9×05)", 7, 9, STEEL, WHITE],
     ["The Commonwealth's ruling class — Pamela & Sebastian", 11, 11, TAN, BLACK]],
    [["Morgan Jones (1×01)", 1, 1, NAVY, WHITE],
     ["Morgan — “Clear” (3×12)", 3, 3, NAVY, WHITE],
     ["Morgan (5×16; leaves 8×16 → Fear)", 5, 8, NAVY, WHITE]],
  ],

  villains: [
    [["The dead world & the CDC's dead end", 1, 1, SWAMP, WHITE],
     ["Shane's unraveling (dies 2×12)", 2, 2, CHAR, WHITE],
     ["The Governor — David Morrissey (3×03–4×08)", 3, 4, BLOOD, WHITE],
     ["Gareth & the Hunters of Terminus (4×16–5×03)", 5, 5, BRICK, WHITE],
     ["Negan & the Saviors (from 6×16)", 6, 8, RED, WHITE],
     ["Alpha, Beta & the Whisperers (9×08–10×16)", 9, 10, ASH, BLACK],
     ["The Commonwealth — Pamela Milton & Lance Hornsby", 11, 11, AMBER, BLACK]],
    [["The prison inmates (3×02–3×04)", 3, 3, SLATE, WHITE],
     ["The Claimers — Joe's gang (4×11–4×16)", 4, 4, BROWN, WHITE],
     ["The Wolves (5×16–6×09)", 5, 6, NIGHT, WHITE],
     ["The Scavengers — Jadis & the Heapsters (7×10–8×16)", 7, 8, STEEL, WHITE],
     ["The Highwaymen (9×16)", 9, 9, TAN, BLACK],
     ["Dante & the Whisperer infiltration (10×01–10×07)", 10, 10, SWAMP, WHITE],
     ["The Reapers — Pope & Leah (11×01–11×08)", 11, 11, CHAR, WHITE]],
    [["The barn walkers & the highway herd", 1, 2, PALEG, BLACK],
     ["The prison herd & the tombs", 3, 4, MOSS, WHITE],
     ["“Them” — the road herd & the church", 5, 5, OLIVE, BLACK],
     ["The quarry herd & the fall of Alexandria (6×01–6×09)", 6, 6, ROT, BLACK],
     ["Whisperer herds & the mega-herd (9×08–10×16)", 9, 10, MOSS, WHITE],
     ["Variant walkers — climbing, tool-using (11×19)", 11, 11, SWAMP, WHITE]],
    [["Merle — the Governor's right hand", 3, 3, RED, WHITE],
     ["Martinez & the Woodbury remnant (4×06–4×08)", 4, 4, BRICK, WHITE],
     ["Dawn Lerner & the Grady cops (5×04–5×08)", 5, 5, NAVY, WHITE],
     ["Dwight & Simon — Negan's lieutenants", 7, 8, RUST, WHITE],
     ["Beta — Ryan Hurst (9×10; dies 10×16)", 9, 10, CHAR, WHITE],
     ["Sebastian Milton & the Commonwealth guard", 11, 11, TAN, BLACK]],
    [["Milton Mamet & the Woodbury experiments", 3, 3, PLUM, WHITE],
     ["Eugene's Washington lie (4×10–5×05)", 4, 5, OLIVE, BLACK],
     ["Gregory's betrayals (6×11–9×02)", 6, 9, TAN, BLACK],
     ["Lance Hornsby's empire (11×10–11×23)", 11, 11, AMBER, BLACK]],
  ],

  arcs: [
    [["Waking up alone — Atlanta & the CDC", 1, 1, RUSTY, BLACK],
     ["The search for Sophia & the barn", 2, 2, PALEG, BLACK],
     ["Woodbury & the war for the prison", 3, 3, BLOOD, WHITE],
     ["The fall of the prison & the road to Terminus", 4, 4, BRICK, WHITE],
     ["Terminus, Grady & finding Alexandria", 5, 5, BROWN, WHITE],
     ["The Alexandria adjustment & the quarry herd", 6, 6, MOSS, WHITE],
     ["Under Negan's boot — building the war", 7, 7, RED, WHITE],
     ["All Out War", 8, 8, CRIM, WHITE],
     ["The time jump & Rick's exit", 9, 9, TEAL, WHITE],
     ["The Whisperer War", 10, 10, ASH, BLACK],
     ["The Reapers & the Commonwealth", 11, 11, AMBER, BLACK]],
    [["Rick, Lori & Shane's triangle", 1, 2, PINK, BLACK],
     ["Glenn & Maggie (from 2×04)", 3, 7, MOSS, WHITE],
     ["Michonne & the Grimes family", 8, 10, PLUM, WHITE],
     ["Maggie & Negan — the reckoning", 11, 11, BLOOD, WHITE]],
    [["Carol's transformation — from Ed to “The Grove”", 1, 4, RUSTY, BLACK],
     ["Carol vs herself — Alexandria & the Wolves", 5, 8, TAN, BLACK],
     ["Carol vs Alpha", 9, 10, ASH, BLACK],
     ["Carol & Daryl's long goodbye", 11, 11, BROWN, WHITE]],
    [["Daryl & Merle", 1, 3, RED, WHITE],
     ["Daryl & Beth (4×12–5×08)", 4, 5, SAND, BLACK],
     ["Daryl, Dwight & the cell (6×06–8×16)", 6, 8, RUST, WHITE],
     ["Daryl's search for Rick (9×01–9×05)", 9, 9, SLATE, WHITE],
     ["Daryl & Leah at the cabin", 10, 11, SWAMP, WHITE]],
    [["Sophia in the barn (2×07)", 2, 2, PALEG, BLACK],
     ["Judith's birth & Lori's death (3×04)", 3, 3, PINK, BLACK],
     ["“The Grove” — Lizzie & Mika (4×14)", 4, 4, SAND, BLACK],
     ["Beth's death & Tyreese's goodbye (5×08 / 5×09)", 5, 5, SLATE, WHITE],
     ["Denise, Glenn & Abraham — the deaths that broke it", 6, 7, BLOOD, WHITE],
     ["Carl's bite (8×08)", 8, 8, NAVY, WHITE],
     ["The pikes (9×15)", 9, 9, CHAR, WHITE],
     ["Alpha's head & Beta's fall", 10, 10, ASH, BLACK],
     ["Rosita, and the last goodbyes", 11, 11, CRIM, WHITE]],
    [["Washington, DC & Eugene's cure", 4, 5, OLIVE, BLACK],
     ["The Hilltop, the Kingdom & the alliance", 6, 8, PLUM, WHITE],
     ["Rebuilding the bridge & the fair", 9, 9, TEAL, WHITE],
     ["The border & the mask", 10, 10, SWAMP, WHITE],
     ["The Commonwealth's class system", 11, 11, AMBER, BLACK]],
  ],
};

window.SEASON_META = {
  1:{years:"2010 · 6 episodes",showrunner:"Frank Darabont"},
  2:{years:"2011–12 · 13 episodes",showrunner:"Glen Mazzara"},
  3:{years:"2012–13",showrunner:"Glen Mazzara"},
  4:{years:"2013–14",showrunner:"Scott M. Gimple"},
  5:{years:"2014–15",showrunner:"Scott M. Gimple"},
  6:{years:"2015–16",showrunner:"Scott M. Gimple"},
  7:{years:"2016–17",showrunner:"Scott M. Gimple"},
  8:{years:"2017–18 · All Out War",showrunner:"Scott M. Gimple"},
  9:{years:"2018–19 · the time jump",showrunner:"Angela Kang"},
  10:{years:"2019–21 · + 6 bonus episodes",showrunner:"Angela Kang"},
  11:{years:"2021–22 · 24 eps in three parts",showrunner:"Angela Kang"},
};
