// Star Trek: The Next Generation — episode tags. Season premieres and finales are auto-tagged by the engine, so they aren't listed here.
// Keys are the season.episode numbers used in episodes.json (TVmaze numbering: "Encounter at Farpoint" is 1.1–1.2,
// "All Good Things..." is 7.25–7.26).
window.TAG_DEFS = {
  fanfav:     {label:"Fan favorite", desc:"The ones people rewatch first"},
  heavy:      {label:"Gut-punch", desc:"Deaths, losses and the ones that stay with you"},
  q:          {label:"Q", desc:"Every episode with John de Lancie's Q"},
  borg:       {label:"The Borg", desc:"Resistance is futile"},
  romulan:    {label:"Romulans", desc:"Warbirds, defectors, Tomalak and Sela"},
  klingon:    {label:"Klingon politics", desc:"Worf's honour, the House of Duras and the High Council"},
  cardassian: {label:"Cardassians", desc:"From \"The Wounded\" to the Maquis"},
  mindbender: {label:"Mind-bender", desc:"Time loops, alternate realities and nothing is what it seems"},
  experiment: {label:"Format experiment", desc:"The show breaking its own rules"},
  holodeck:   {label:"Holodeck", desc:"Dixon Hill, Sherlock Holmes and the holodeck going wrong"},
  legacy:     {label:"Original series legacy", desc:"McCoy, Sarek, Spock and Scotty"},
  twoparter:  {label:"Two-parter"},
  milestone:  {label:"Milestone", desc:"Arrivals, departures and the days that changed the show"},
  classic:    {label:"Classic standalone", desc:"A regular week on the Enterprise"},
  picard:     {label:"Picard spotlight"},
  riker:      {label:"Riker spotlight"},
  data:       {label:"Data spotlight"},
  worf:       {label:"Worf spotlight"},
  geordi:     {label:"Geordi spotlight"},
  troi:       {label:"Troi spotlight"},
  beverly:    {label:"Beverly Crusher spotlight"},
  wesley:     {label:"Wesley spotlight"},
  lwaxana:    {label:"Lwaxana Troi"},
  barclay:    {label:"Barclay"},
};

window.EP_TAGS = {
  "1.1": ["q","twoparter","legacy"], "1.2": ["q","twoparter"],
  "1.8": ["wesley"], "1.10": ["q"], "1.11": ["lwaxana","troi"], "1.12": ["holodeck","picard"],
  "1.13": ["data"], "1.15": ["holodeck","riker"], "1.17": ["wesley"], "1.19": ["wesley"],
  "1.20": ["klingon","worf"], "1.23": ["heavy","milestone"], "1.24": ["picard"],
  "2.3": ["holodeck","data"], "2.6": ["data"], "2.8": ["klingon","riker"],
  "2.9": ["fanfav","data","picard"], "2.11": ["romulan"], "2.13": ["mindbender"], "2.14": ["riker","worf"],
  "2.16": ["fanfav","q","borg","milestone"], "2.19": ["lwaxana","holodeck"], "2.20": ["klingon","worf"],
  "2.22": ["experiment","riker"],
  "3.2": ["data"], "3.6": ["geordi"], "3.7": ["romulan","geordi","worf"], "3.8": ["troi"], "3.10": ["romulan"],
  "3.13": ["q","data"], "3.14": ["experiment","riker"], "3.15": ["fanfav","mindbender","romulan","klingon"],
  "3.16": ["fanfav","heavy","data"], "3.17": ["fanfav","klingon","worf"], "3.19": ["picard"], "3.20": ["romulan"],
  "3.21": ["barclay","holodeck"], "3.22": ["data"], "3.23": ["fanfav","legacy","picard"], "3.24": ["lwaxana","troi"],
  "4.1": ["fanfav","borg","twoparter"], "4.2": ["fanfav","heavy","borg","picard"], "4.3": ["data"],
  "4.5": ["beverly","mindbender"], "4.7": ["heavy","klingon","worf","milestone"], "4.8": ["mindbender","riker","romulan"],
  "4.9": ["wesley","milestone"], "4.10": ["troi"], "4.11": ["experiment","data","romulan"], "4.12": ["cardassian"],
  "4.16": ["geordi"], "4.19": ["barclay"], "4.20": ["q","picard"], "4.21": ["fanfav","picard","romulan"],
  "4.22": ["lwaxana","heavy"], "4.23": ["beverly"], "4.24": ["geordi","romulan","klingon"], "4.25": ["data"],
  "4.26": ["klingon","romulan","worf","twoparter"],
  "5.1": ["klingon","romulan","worf","twoparter"], "5.2": ["fanfav","picard"], "5.3": ["cardassian","milestone"],
  "5.6": ["wesley"], "5.7": ["romulan","legacy","twoparter","milestone"], "5.8": ["romulan","legacy","twoparter"],
  "5.10": ["worf"], "5.12": ["troi"], "5.14": ["mindbender"], "5.18": ["fanfav","mindbender"],
  "5.19": ["fanfav","wesley"], "5.20": ["lwaxana"], "5.23": ["borg","geordi"], "5.24": ["geordi","romulan"],
  "5.25": ["fanfav","heavy","picard"],
  "6.2": ["barclay"], "6.3": ["troi"], "6.4": ["fanfav","legacy","geordi"], "6.6": ["q"],
  "6.8": ["holodeck","worf","data"], "6.9": ["data"],
  "6.10": ["fanfav","heavy","cardassian","picard","twoparter"], "6.11": ["fanfav","heavy","cardassian","picard","twoparter"],
  "6.12": ["fanfav","holodeck","barclay"], "6.14": ["romulan","troi"], "6.15": ["fanfav","q","picard","mindbender"],
  "6.16": ["klingon","romulan","worf","twoparter"], "6.17": ["klingon","romulan","worf","twoparter"],
  "6.18": ["picard"], "6.19": ["heavy","picard"], "6.20": ["picard","romulan","cardassian"],
  "6.21": ["mindbender","riker"], "6.22": ["beverly"], "6.23": ["klingon","worf"], "6.24": ["riker"],
  "6.25": ["mindbender","romulan"], "6.26": ["borg","data","twoparter"],
  "7.1": ["borg","data","twoparter"], "7.3": ["geordi"], "7.4": ["picard","twoparter"], "7.5": ["picard","twoparter"],
  "7.6": ["data"], "7.7": ["lwaxana","troi"], "7.10": ["data"], "7.11": ["fanfav","mindbender","worf"],
  "7.12": ["romulan","riker"], "7.14": ["beverly"], "7.15": ["fanfav","heavy","experiment","cardassian"],
  "7.19": ["barclay"], "7.20": ["wesley","cardassian","milestone"], "7.21": ["klingon","worf"],
  "7.24": ["cardassian","milestone"],
  "7.25": ["fanfav","q","mindbender","twoparter"], "7.26": ["fanfav","q","mindbender","twoparter"],
  // Everything else: a regular week on the Enterprise.
  "1.3": ["classic"], "1.4": ["classic"], "1.5": ["classic"], "1.6": ["classic"], "1.7": ["classic"], "1.9": ["classic"], "1.14": ["classic"], "1.16": ["classic"],
  "1.18": ["classic"], "1.21": ["classic"], "1.22": ["classic"], "1.25": ["classic"], "1.26": ["romulan"], "2.1": ["troi"], "2.2": ["classic"], "2.4": ["classic"],
  "2.5": ["classic"], "2.7": ["classic"], "2.10": ["classic"], "2.12": ["classic"], "2.15": ["classic"], "2.17": ["classic"], "2.18": ["classic"], "2.21": ["classic"],
  "3.1": ["wesley"], "3.3": ["classic"], "3.4": ["classic"], "3.5": ["classic"], "3.9": ["classic"], "3.11": ["classic"], "3.12": ["classic"], "3.18": ["picard"],
  "3.25": ["classic"], "3.26": ["fanfav","borg","twoparter"], "4.4": ["picard"], "4.6": ["classic"], "4.13": ["classic"], "4.14": ["classic"], "4.15": ["classic"], "4.17": ["classic"],
  "4.18": ["classic"], "5.4": ["data"], "5.5": ["classic"], "5.9": ["classic"], "5.11": ["classic"], "5.13": ["classic"], "5.15": ["classic"], "5.16": ["classic"],
  "5.17": ["classic"], "5.21": ["picard"], "5.22": ["classic"], "5.26": ["data","twoparter"], "6.1": ["data","twoparter"], "6.5": ["classic"], "6.7": ["classic"], "6.13": ["classic"],
  "7.2": ["classic"], "7.8": ["picard","beverly"], "7.9": ["classic"], "7.13": ["classic"], "7.16": ["data","troi"], "7.17": ["data"], "7.18": ["troi"], "7.22": ["picard"],
  "7.23": ["holodeck","data"],
};
