window.TAG_DEFS = {
  fanfav:     {label:"Fan favorite", desc:""},
  heavy:      {label:"Gut-punch", desc:""},
  arc:        {label:"Mythology / arc", desc:"Moves the Lumon throughline"},
  reveal:     {label:"Big reveal", desc:"Something you can't un-know"},
  experiment: {label:"Format experiment", desc:"Breaks the show's usual shape"},
  outside:    {label:"Mostly outside Lumon", desc:"Little or no severed floor"},
  funny:      {label:"Office comedy", desc:"Waffle parties, Music Dance Experience, the perks"},
  romance:    {label:"Romance", desc:""},
  mark:{label:"Mark spotlight"}, helly:{label:"Helly / Helena spotlight"}, irving:{label:"Irving spotlight"},
  dylan:{label:"Dylan spotlight"}, cobel:{label:"Cobel spotlight"}, milchick:{label:"Milchick spotlight"},
  gemma:{label:"Gemma / Ms. Casey spotlight"}, devon:{label:"Devon & Ricken spotlight"},
};

window.EP_TAGS = {
  "1.1":["arc","mark","helly"],
  "1.2":["helly","mark","arc"],
  "1.3":["irving","helly","arc","funny"],
  "1.4":["fanfav","heavy","helly","mark","devon"],
  "1.5":["fanfav","reveal","irving","mark"],
  "1.6":["fanfav","heavy","reveal","dylan","cobel"],
  "1.7":["fanfav","funny","milchick","irving","heavy"],
  "1.8":["arc","dylan","mark","devon"],
  "1.9":["fanfav","arc","reveal","heavy","mark","helly","irving","dylan","gemma"],
  "2.1":["arc","reveal","mark","milchick"],
  "2.2":["arc","outside","mark","devon","cobel"],
  "2.3":["arc","irving","dylan","mark"],
  "2.4":["fanfav","arc","reveal","heavy","experiment","irving","helly"],
  "2.5":["heavy","irving","dylan","milchick"],
  "2.6":["heavy","romance","outside","irving","mark"],
  "2.7":["fanfav","experiment","outside","reveal","heavy","romance","gemma","mark"],
  "2.8":["experiment","outside","reveal","cobel"],
  "2.9":["arc","mark","devon","cobel","helly"],
  "2.10":["fanfav","arc","heavy","reveal","mark","helly","gemma","dylan","milchick"],
};
