// Dragon Ball Z — episode tags. Season premieres and finales are auto-tagged by the engine.
// Keys are the season.episode numbers used in episodes.json ('2.0' and '6.0' are the two TV specials).
window.TAG_DEFS = {
  story:          {label:"Main story", desc:"Advances the saga — as opposed to the anime-only detours"},
  filler:         {label:"Anime-only filler", desc:"Not in the manga; safe to skip on a rewatch"},
  special:        {label:"TV special", desc:"The two feature-length specials, in air order"},
  fanfav:         {label:"Fan favorite", desc:"The ones people rewatch first"},
  fight:          {label:"Landmark fight", desc:"The bouts the show is remembered for"},
  transformation: {label:"Transformation", desc:"A new form, grade or fusion — and the episode it lands in"},
  technique:      {label:"Signature technique", desc:"Spirit Bomb, Instant Transmission, the father-son Kamehameha"},
  training:       {label:"Training arc", desc:"Gravity chambers, Snake Way, the Hyperbolic Time Chamber"},
  tournament:     {label:"Tournament", desc:"Martial arts tournaments, in this world or the next"},
  heavy:          {label:"Gut-punch", desc:"Deaths, sacrifices and the ones that hurt"},
  death:          {label:"Someone dies", desc:"It rarely sticks, but it still stings"},
  revival:        {label:"Wished back", desc:"Dragon Balls, Porunga, and the undo button"},
  lore:           {label:"Lore & backstory", desc:"Saiyan history, Kais, timelines and how any of this works"},
  comedy:         {label:"Played for laughs", desc:"The show remembering it started as a comedy"},
  goku:           {label:"Goku spotlight"},
  gohan:          {label:"Gohan spotlight"},
  vegeta:         {label:"Vegeta spotlight"},
  piccolo:        {label:"Piccolo spotlight"},
  krillin:        {label:"Krillin spotlight"},
  trunks:         {label:"Trunks spotlight"},
  goten:          {label:"Goten spotlight"},
  bulma:          {label:"Bulma spotlight"},
  videl:          {label:"Videl spotlight"},
  satan:          {label:"Mr. Satan spotlight"},
  eighteen:       {label:"Android 18 spotlight"},
  frieza:         {label:"Frieza"},
  cell:           {label:"Cell"},
  buu:            {label:"Majin Buu"},
};

window.EP_TAGS = {
  // season 1
  "1.1":  ["story","goku","gohan","piccolo","lore","fanfav"],
  "1.2":  ["story","goku","piccolo"],
  "1.3":  ["story","piccolo","fight","fanfav"],
  "1.4":  ["story","gohan","piccolo"],
  "1.5":  ["story","gohan","death","heavy","fanfav"],
  "1.6":  ["story","piccolo","gohan"],
  "1.7":  ["story","gohan","training"],
  "1.8":  ["story","gohan","comedy"],
  "1.9":  ["filler","gohan"],
  "1.10": ["filler","gohan"],
  "1.11": ["filler","vegeta"],
  "1.12": ["filler","training"],
  "1.13": ["filler","comedy"],
  "1.14": ["filler","comedy"],
  "1.15": ["filler","piccolo","gohan"],
  "1.16": ["filler","gohan"],
  "1.17": ["filler","training"],
  "1.18": ["story","goku","training"],
  "1.19": ["story","vegeta","training"],
  "1.20": ["story","goku","training","lore","fanfav"],
  "1.21": ["story","training"],
  "1.22": ["story","vegeta","fight"],
  "1.23": ["story","death","heavy","fight"],
  "1.24": ["story","death","heavy","fight"],
  "1.25": ["story","death","heavy","fanfav"],
  "1.26": ["story","piccolo","gohan","death","heavy","fanfav"],
  "1.27": ["story","goku"],
  "1.28": ["story","goku","fight","fanfav"],
  "1.29": ["story","goku","transformation","fight"],
  "1.30": ["story","goku","vegeta","fight","fanfav"],
  "1.31": ["story","vegeta","fight"],
  "1.32": ["story","goku","technique","fanfav"],
  "1.33": ["story","gohan","fight"],
  "1.34": ["story","krillin","fight"],
  "1.35": ["story","vegeta","heavy","fanfav"],
  "1.36": ["story","bulma"],
  "1.37": ["story","bulma","krillin"],
  "1.38": ["story","vegeta"],
  "1.39": ["story","gohan","krillin","bulma"],
  // season 2
  "2.1":  ["story","gohan","krillin","bulma"],
  "2.2":  ["story","gohan","krillin"],
  "2.3":  ["story","bulma","comedy"],
  "2.4":  ["story","krillin"],
  "2.5":  ["story","gohan","krillin"],
  "2.6":  ["story","frieza"],
  "2.7":  ["story","vegeta"],
  "2.8":  ["story","gohan","krillin"],
  "2.9":  ["story","gohan","krillin"],
  "2.10": ["story","vegeta","fight"],
  "2.11": ["story","vegeta"],
  "2.12": ["story","vegeta","fight"],
  "2.13": ["story","lore","vegeta"],
  "2.14": ["story","vegeta","fight"],
  "2.15": ["story","gohan","lore","transformation"],
  "2.16": ["story","piccolo","fight"],
  "2.17": ["story","vegeta"],
  "2.18": ["story","gohan"],
  "2.19": ["story","krillin","gohan"],
  "2.20": ["story","gohan","krillin"],
  "2.21": ["story","bulma","comedy"],
  "2.22": ["story","gohan","fight"],
  "2.23": ["story","piccolo"],
  "2.24": ["story","fight","comedy"],
  "2.0":  ["special","lore","heavy","fanfav"],
  "2.25": ["story","fight","heavy"],
  "2.26": ["story","fight","heavy"],
  "2.27": ["story","goku","fight","fanfav"],
  "2.28": ["story","goku","lore"],
  "2.29": ["story","goku","fight"],
  "2.30": ["story","goku","fight"],
  "2.31": ["story","vegeta","frieza"],
  "2.32": ["story","comedy","fanfav","goku"],
  "2.33": ["story","vegeta"],
  "2.34": ["story","gohan","krillin"],
  "2.35": ["story","comedy","fanfav"],
  // season 3
  "3.1":  ["story","vegeta","krillin"],
  "3.2":  ["story","piccolo","revival"],
  "3.3":  ["story","piccolo","transformation","fanfav"],
  "3.4":  ["story","piccolo","frieza","fight"],
  "3.5":  ["story","gohan","fight"],
  "3.6":  ["story","piccolo","fight","fanfav"],
  "3.7":  ["story","frieza","vegeta"],
  "3.8":  ["story","frieza","transformation"],
  "3.9":  ["story","frieza","transformation"],
  "3.10": ["story","death","heavy","frieza"],
  "3.11": ["story","goku","fight"],
  "3.12": ["story","vegeta","death","heavy","fanfav"],
  "3.13": ["story","goku","frieza","fight"],
  "3.14": ["story","goku","frieza","fight"],
  "3.15": ["story","frieza","fight"],
  "3.16": ["story","goku","fight"],
  "3.17": ["story","goku","fight"],
  "3.18": ["story","goku","technique","fight"],
  "3.19": ["story","gohan","krillin"],
  "3.20": ["story","goku","technique","fight"],
  "3.21": ["story","goku","transformation","fanfav","fight"],
  "3.22": ["story","goku","frieza","fight"],
  "3.23": ["story","frieza","fight"],
  "3.24": ["story","goku","fight"],
  "3.25": ["story","gohan"],
  "3.26": ["story","gohan","fight"],
  "3.27": ["story","revival","piccolo"],
  "3.28": ["story","goku","frieza","fight"],
  "3.29": ["story","frieza","heavy","fanfav"],
  "3.30": ["story","goku","frieza","fight"],
  "3.31": ["story","goku","frieza"],
  "3.32": ["story","goku","heavy"],
  "3.33": ["story","goku","revival","fanfav"],
  // season 4
  "4.1":  ["filler"],
  "4.2":  ["filler","krillin"],
  "4.3":  ["filler","piccolo"],
  "4.4":  ["filler","piccolo","fight"],
  "4.5":  ["filler","gohan"],
  "4.6":  ["filler","gohan"],
  "4.7":  ["filler","gohan"],
  "4.8":  ["filler","krillin"],
  "4.9":  ["filler","gohan"],
  "4.10": ["filler","krillin","comedy"],
  "4.11": ["story","frieza"],
  "4.12": ["story","trunks","transformation","fight","fanfav"],
  "4.13": ["story","trunks","lore","heavy","fanfav"],
  "4.14": ["story","goku","technique"],
  "4.15": ["story","trunks","lore"],
  "4.16": ["story","goku","training"],
  "4.17": ["story","training"],
  "4.18": ["story","goku","training","comedy"],
  "4.19": ["story","fight"],
  "4.20": ["story","fight"],
  "4.21": ["story","goku","fight","heavy"],
  "4.22": ["story","vegeta","transformation","fanfav"],
  "4.23": ["story","lore"],
  "4.24": ["story","bulma","trunks"],
  "4.25": ["story","krillin"],
  "4.26": ["story","fight"],
  "4.27": ["story","fight"],
  "4.28": ["story","eighteen","fight"],
  "4.29": ["story","vegeta","fight","heavy"],
  "4.30": ["story","trunks","fight"],
  "4.31": ["story","piccolo"],
  "4.32": ["story","piccolo","cell"],
  // season 5
  "5.1":  ["story","cell","heavy"],
  "5.2":  ["story","piccolo","transformation"],
  "5.3":  ["story","piccolo","cell","fight"],
  "5.4":  ["story","cell","lore","fanfav"],
  "5.5":  ["story","piccolo","cell"],
  "5.6":  ["story","trunks","krillin"],
  "5.7":  ["story","goku"],
  "5.8":  ["story","training","lore","fanfav"],
  "5.9":  ["story","cell"],
  "5.10": ["story","cell","fight"],
  "5.11": ["story","piccolo","fight"],
  "5.12": ["story","eighteen","fight"],
  "5.13": ["story","cell","eighteen"],
  "5.14": ["story","cell","heavy"],
  "5.15": ["story","vegeta","trunks"],
  "5.16": ["story","vegeta","transformation","fanfav"],
  "5.17": ["story","vegeta","cell","fight"],
  "5.18": ["story","vegeta","cell","heavy"],
  "5.19": ["story","krillin","eighteen","heavy","fanfav"],
  "5.20": ["story","trunks","fight"],
  "5.21": ["story","cell","transformation","fanfav"],
  "5.22": ["story","vegeta","cell","fight"],
  "5.23": ["story","trunks","transformation","fight"],
  "5.24": ["story","trunks","cell","heavy"],
  "5.25": ["story","trunks","lore","heavy"],
  "5.26": ["story","cell","training"],
  // season 6
  "6.1":  ["story","satan","comedy"],
  "6.2":  ["story","cell","satan"],
  "6.3":  ["story","training","comedy"],
  "6.4":  ["story","goku","gohan","training"],
  "6.5":  ["filler","gohan"],
  "6.6":  ["filler"],
  "6.7":  ["story","piccolo","lore"],
  "6.8":  ["story","lore","revival"],
  "6.9":  ["filler","satan","comedy"],
  "6.10": ["story","satan","comedy","fight"],
  "6.0":  ["special","trunks","heavy","fanfav"],
  "6.11": ["story","satan","cell"],
  "6.12": ["story","goku","cell","fight","fanfav"],
  "6.13": ["story","goku","cell","fight"],
  "6.14": ["story","goku","cell","fight"],
  "6.15": ["story","goku","gohan","heavy"],
  "6.16": ["story","gohan","fight"],
  "6.17": ["story","gohan","cell","heavy"],
  "6.18": ["story","eighteen","cell"],
  "6.19": ["story","cell","heavy","fight"],
  "6.20": ["story","gohan","transformation","fanfav"],
  "6.21": ["story","gohan","cell","fight","fanfav"],
  "6.22": ["story","gohan","cell","fight"],
  "6.23": ["story","goku","death","heavy","fanfav"],
  "6.24": ["story","trunks","death","heavy","cell"],
  "6.25": ["story","gohan","cell","fight"],
  "6.26": ["story","gohan","cell","fanfav","fight"],
  "6.27": ["story","goku","heavy"],
  "6.28": ["story","revival","krillin","eighteen"],
  "6.29": ["story","trunks","fanfav","heavy"],
  // season 7
  "7.1":  ["filler","goku"],
  "7.2":  ["filler","goku","tournament"],
  "7.3":  ["filler","tournament"],
  "7.4":  ["filler","goku","tournament"],
  "7.5":  ["filler","goku","fight"],
  "7.6":  ["story","gohan","comedy","fanfav"],
  "7.7":  ["story","gohan","comedy","fanfav"],
  "7.8":  ["filler","gohan","videl","comedy"],
  "7.9":  ["story","videl","gohan"],
  "7.10": ["story","videl","gohan"],
  "7.11": ["story","gohan","videl"],
  "7.12": ["story","goten","transformation","fanfav"],
  "7.13": ["story","videl","training"],
  "7.14": ["story","goku","tournament"],
  "7.15": ["story","comedy","tournament"],
  "7.16": ["story","tournament","goku","fanfav"],
  "7.17": ["story","goten","trunks","tournament","fanfav"],
  "7.18": ["story","goten","trunks","tournament"],
  "7.19": ["story","trunks","tournament","comedy"],
  "7.20": ["story","tournament"],
  "7.21": ["story","piccolo","tournament"],
  "7.22": ["story","gohan","tournament"],
  "7.23": ["story","videl","heavy","fight"],
  "7.24": ["story","gohan","tournament"],
  "7.25": ["story","gohan","heavy"],
  // season 8
  "8.1":  ["story","lore","heavy"],
  "8.2":  ["story","fight"],
  "8.3":  ["story","vegeta","fight"],
  "8.4":  ["story","goku","fight"],
  "8.5":  ["story","fight"],
  "8.6":  ["story","eighteen","satan","tournament"],
  "8.7":  ["story","satan","comedy"],
  "8.8":  ["story","vegeta","lore","heavy"],
  "8.9":  ["story","vegeta","transformation","fanfav","heavy"],
  "8.10": ["story","vegeta","goku"],
  "8.11": ["story","goku","vegeta","fight","fanfav"],
  "8.12": ["story","buu","gohan"],
  "8.13": ["story","buu","heavy"],
  "8.14": ["story","buu","death","heavy"],
  "8.15": ["story","buu","heavy","comedy"],
  "8.16": ["story","buu","comedy"],
  "8.17": ["story","vegeta","heavy"],
  "8.18": ["story","vegeta","death","heavy","fanfav"],
  "8.19": ["story","buu","goten","trunks"],
  "8.20": ["story","bulma","revival"],
  "8.21": ["story","revival","krillin"],
  "8.22": ["story","satan","buu"],
  "8.23": ["story","goten","trunks","training","comedy"],
  "8.24": ["story","gohan","lore","training"],
  "8.25": ["story","goten","trunks","bulma"],
  "8.26": ["story","goku","transformation","fanfav","fight"],
  "8.27": ["story","buu","heavy"],
  "8.28": ["story","goten","trunks","training"],
  "8.29": ["story","goku","heavy"],
  "8.30": ["story","goku","gohan"],
  "8.31": ["story","gohan","lore","transformation"],
  "8.32": ["story","goten","trunks","transformation","fanfav"],
  "8.33": ["story","satan","buu","fanfav"],
  "8.34": ["story","satan","buu","heavy","fanfav"],
  // season 9
  "9.1":  ["story","buu","heavy","fanfav"],
  "9.2":  ["story","buu","fight"],
  "9.3":  ["story","buu","heavy"],
  "9.4":  ["story","goten","trunks","fight"],
  "9.5":  ["story","goten","trunks","comedy","fight"],
  "9.6":  ["story","goten","trunks","buu"],
  "9.7":  ["story","buu","piccolo","heavy"],
  "9.8":  ["story","goten","trunks","fight"],
  "9.9":  ["story","buu","heavy"],
  "9.10": ["story","gohan","transformation","fanfav"],
  "9.11": ["story","goku","buu"],
  "9.12": ["story","buu","transformation"],
  "9.13": ["story","goku","lore"],
  "9.14": ["story","goku","vegeta"],
  "9.15": ["story","goku","vegeta","fanfav"],
  "9.16": ["story","goku","vegeta","transformation","fanfav"],
  "9.17": ["story","buu","fight"],
  "9.18": ["story","buu","comedy","fight"],
  "9.19": ["story","comedy","fight"],
  "9.20": ["story","goku","vegeta","buu"],
  "9.21": ["story","goku","vegeta","buu"],
  "9.22": ["story","buu","heavy"],
  "9.23": ["story","buu","transformation","heavy"],
  "9.24": ["story","buu","heavy","fanfav"],
  "9.25": ["story","goku","vegeta","fight"],
  "9.26": ["story","goku","buu","fight"],
  "9.27": ["story","vegeta","heavy","fanfav"],
  "9.28": ["story","goku","vegeta","fight"],
  "9.29": ["story","buu","satan"],
  "9.30": ["story","revival","satan"],
  "9.31": ["story","satan","comedy"],
  "9.32": ["story","satan","fanfav"],
  "9.33": ["story","goku","technique","fanfav","fight"],
  "9.34": ["story","satan","buu","comedy"],
  "9.35": ["story","comedy","goten","trunks"],
  "9.36": ["story","tournament","gohan","videl"],
  "9.37": ["story","tournament","buu"],
  "9.38": ["story","goku","fanfav","tournament"],
};
