// Twin Peaks (ABC 1990–91 + Showtime 2017) — chart data on an EPISODE axis: columns are the 48 episodes in order.
// 1–8 = S1 (the Pilot is TVmaze 1×01), 9–30 = S2, 31–48 = S3 "The Return" (Parts 1–18).
// Absolute index helpers: S1eN = N | S2eN = 8+N | S3eN = 30+N
// NOTE ON NUMBERING: TVmaze counts the 90-minute Pilot as 1×01, so every original-broadcast
// "Episode N" is TVmaze 1×(N+1). The famous Red Room dream is original Episode 2 = TVmaze 1×03 = column 3.
// Fire Walk With Me (1992) is a film, not an episode — it sits in the gap between columns 30 and 31
// and is called out in the S3 label rather than given a column.
// Each entry: [label, startEp, endEp, bg, fg?]
window.CHART_AXIS = "episode";

const RED="#b3001b", DRED="#7a0011", CRIM="#d62839", ROSE="#e88b96",
      FIR="#1f4d33", GREEN="#2e6b46", LGREEN="#93c2a3", OLIVE="#5f6b32",
      COFFEE="#4a2c17", BROWN="#7b5230", TAN="#c8a97e", CREAM="#efe6d5",
      GOLD="#d4a017", AMBER="#e0902b",
      INK="#111111", CHAR="#2f2f2f", GRAY="#6f6f6f", LGRAY="#cbc7c0",
      NAVY="#1b2a44", BLUE="#3c6ea5", LBLUE="#b9d3e8",
      PURPLE="#5b3a8c", LPURP="#c6b4e0", PINK="#e79ab0",
      TEAL="#2a7f7f", NEON="#e8467c",
      WHITE="#fff", BLACK="#000";

window.ERA_CATS = [
  ["seasons","Season, network & who made it"],
  ["case","The investigation"],
  ["lodge","The Lodge & the spirits"],
  ["evil","Antagonists & pressure"],
  ["town","Twin Peaks, Washington"],
  ["law","The station & the Bureau"],
  ["places","Places (and who's playing the Roadhouse)"],
];

window.ERAS = {
  seasons: [
    [["S1 — Who killed Laura Palmer?", 1, 8, RED, WHITE],
     ["S2 — The reveal, the drift, and the Black Lodge", 9, 30, DRED, WHITE],
     ["S3: The Return — 25 years later (after Fire Walk With Me, 1992)", 31, 48, INK, WHITE]],
    [["ABC", 1, 30, BLUE, WHITE],
     ["Showtime", 31, 48, PURPLE, WHITE]],
    [["Apr–May 1990", 1, 8, LBLUE, BLACK],
     ["Sept–Dec 1990", 9, 19, LBLUE, BLACK],
     ["Jan–Jun 1991 (moved to Saturdays, then benched)", 20, 30, LGRAY, BLACK],
     ["May–Sept 2017", 31, 48, LPURP, BLACK]],
    [["Lynch & Frost hands-on", 1, 17, CHAR, WHITE],
     ["ABC forces the reveal; Lynch drifts away — Frost, Peyton & Engels carry S2", 18, 29, GRAY, WHITE],
     ["Lynch back", 30, 30, CHAR, WHITE],
     ["Lynch & Frost write all 18 Parts", 31, 48, INK, WHITE]],
    [["Lynch", 1, 1, RED, WHITE], ["Lynch", 3, 3, RED, WHITE], ["Lynch", 9, 10, RED, WHITE],
     ["Lynch", 15, 15, RED, WHITE], ["Lynch", 30, 30, RED, WHITE],
     ["David Lynch directs all 18 Parts", 31, 48, RED, WHITE]],
    [["Dunham", 2, 2, TAN, BLACK], ["Rathborne", 4, 4, LGREEN, BLACK], ["Hunter", 5, 5, LBLUE, BLACK],
     ["Glatter", 6, 6, TAN, BLACK], ["Deschanel", 7, 7, LGREEN, BLACK], ["Frost", 8, 8, GOLD, BLACK],
     ["Glatter", 11, 11, TAN, BLACK], ["Holland", 12, 12, LBLUE, BLACK], ["Clifford", 13, 13, LGREEN, BLACK],
     ["Glatter", 14, 14, TAN, BLACK], ["Deschanel", 16, 16, LGREEN, BLACK], ["Hunter", 17, 17, LBLUE, BLACK],
     ["Rathborne", 18, 18, LGREEN, BLACK], ["Dunham", 19, 19, TAN, BLACK], ["Deschanel", 20, 20, LGREEN, BLACK],
     ["Holland", 21, 21, LBLUE, BLACK], ["Edel", 22, 22, LGRAY, BLACK], ["Diane Keaton", 23, 23, PINK, BLACK],
     ["Glatter", 24, 24, TAN, BLACK], ["Foley", 25, 25, LGRAY, BLACK], ["Dunham", 26, 26, TAN, BLACK],
     ["Sanger", 27, 27, LGRAY, BLACK], ["Gyllenhaal", 28, 28, LGRAY, BLACK], ["Hunter", 29, 29, LBLUE, BLACK]],
  ],

  case: [
    [["Who killed Laura Palmer?", 1, 14, RED, WHITE],
     ["\"Lonely Souls\" — it's Leland, it's BOB", 15, 16, INK, WHITE],
     ["Cooper closes the case; Leland dies", 17, 17, DRED, WHITE],
     ["Case closed — the town drifts", 18, 24, LGRAY, BLACK],
     ["The race to the Black Lodge", 25, 30, PURPLE, WHITE],
     ["25 years later: the Blue Rose case", 31, 48, INK, WHITE]],
    [["Cooper's rock-throwing Tibetan method", 3, 4, TAN, BLACK],
     ["Jacques, the cabin & the one-armed man", 5, 8, BROWN, WHITE],
     ["Laura's secret diary & Harold Smith", 11, 14, PURPLE, WHITE],
     ["Maddy's murder", 15, 16, DRED, WHITE],
     ["Windom Earle's chess game", 20, 30, CHAR, WHITE]],
    [["Cooper in the Red Room", 31, 32, RED, WHITE],
     ["Cooper as \"Dougie Jones\" in Las Vegas", 33, 45, GOLD, BLACK],
     ["Cooper wakes: \"I am the FBI\"", 46, 46, CRIM, WHITE],
     ["Back to Twin Peaks; Mr. C destroyed", 47, 47, DRED, WHITE],
     ["Odessa: \"What year is this?\"", 48, 48, INK, WHITE]],
    [["Buckhorn, SD: Ruth Davenport's body & Major Briggs's head", 31, 41, TEAL, WHITE],
     ["Diane, the coordinates & the Fireman's instructions", 42, 48, NAVY, WHITE]],
    [["Hawk & Laura's missing diary pages (the Log Lady calls)", 31, 45, FIR, WHITE],
     ["\"Is it the story of the little girl who lived down the lane?\"", 46, 48, OLIVE, WHITE]],
  ],

  lodge: [
    [["BOB, hiding inside Leland", 3, 17, INK, WHITE],
     ["BOB comes back for the Lodge", 24, 30, CHAR, WHITE],
     ["BOB riding inside Mr. C — destroyed in Part 17", 31, 47, INK, WHITE]],
    [["The Man From Another Place (Cooper's dream → the Lodge)", 3, 30, RED, WHITE],
     ["The Arm, and its evolution", 31, 48, CRIM, WHITE]],
    [["Philip Gerard / MIKE, the one-armed man", 1, 17, GOLD, BLACK],
     ["MIKE in the Black Lodge", 30, 30, AMBER, BLACK],
     ["MIKE: \"Is it future, or is it past?\"", 31, 48, GOLD, BLACK]],
    [["The Giant", 9, 30, LGRAY, BLACK],
     ["The Fireman (and Señorita Dido)", 31, 48, CREAM, BLACK]],
    [["The Woodsmen — \"Gotta light?\"", 38, 47, CHAR, WHITE]],
    [["The Experiment", 31, 44, NEON, WHITE],
     ["Judy / Jowday — the extreme negative force", 45, 48, DRED, WHITE]],
    [["Mrs. Tremond & her grandson", 10, 17, LPURP, BLACK],
     ["Alice Tremond opens the door", 48, 48, PURPLE, WHITE]],
    [["Garmonbozia, creamed corn & the convenience store", 15, 30, OLIVE, WHITE],
     ["Phillip Jeffries, now a teakettle", 44, 47, TEAL, WHITE]],
  ],

  evil: [
    [["BOB — through Leland", 3, 17, INK, WHITE],
     ["Windom Earle", 20, 30, PURPLE, WHITE],
     ["Mr. C — Cooper's doppelgänger", 31, 47, CHAR, WHITE]],
    [["Jacques Renault", 4, 8, BROWN, WHITE],
     ["Jean Renault", 11, 21, COFFEE, WHITE],
     ["Thomas Eckhardt", 22, 24, NAVY, WHITE],
     ["Miss Twin Peaks & the Lodge endgame", 27, 30, PURPLE, WHITE]],
    [["Ben Horne & One Eyed Jacks", 3, 18, GOLD, BLACK],
     ["Evelyn Marsh & Malcolm Sloan (the James detour)", 19, 23, LGRAY, BLACK]],
    [["Hank Jennings", 5, 24, OLIVE, WHITE],
     ["Chantal & Hutch", 32, 46, DRED, WHITE]],
    [["Ray Monroe", 31, 43, TEAL, WHITE],
     ["Judy", 44, 48, DRED, WHITE]],
    [["Duncan Todd & Roger", 32, 45, NAVY, WHITE]],
    [["Richard Horne", 35, 46, CRIM, WHITE]],
    [["Anthony Sinclair & Ike \"The Spike\"", 35, 43, GRAY, WHITE]],
  ],

  town: [
    [["Laura Palmer — the body, the tape, the dream", 1, 30, ROSE, BLACK],
     ["Laura Palmer / Carrie Page", 31, 48, PINK, BLACK]],
    [["Leland Palmer (dies 2×09)", 1, 17, DRED, WHITE],
     ["Leland in the Red Room: \"Find Laura\"", 32, 32, RED, WHITE],
     ["Leland, Parts 17–18", 47, 48, RED, WHITE]],
    [["Sarah Palmer", 1, 30, LPURP, BLACK],
     ["Sarah Palmer — something got inside", 31, 48, PURPLE, WHITE]],
    [["Maddy Ferguson (arrives 1×02, killed 2×07)", 2, 16, ROSE, BLACK],
     ["Becky Burnett", 35, 43, PINK, BLACK]],
    [["Audrey Horne", 1, 30, CRIM, WHITE],
     ["Audrey & Charlie — \"Is it about Billy?\"", 42, 46, RED, WHITE]],
    [["Donna Hayward", 1, 30, LGREEN, BLACK],
     ["Steven Burnett", 35, 45, OLIVE, WHITE]],
    [["James Hurley", 1, 30, LBLUE, BLACK],
     ["James (still cool)", 32, 47, BLUE, WHITE]],
    [["Bobby Briggs", 1, 30, GOLD, BLACK],
     ["Deputy Bobby Briggs", 34, 47, AMBER, BLACK]],
    [["Shelly Johnson", 1, 30, PINK, BLACK],
     ["Shelly (Return)", 32, 45, ROSE, BLACK]],
    [["Leo Johnson", 1, 30, COFFEE, WHITE],
     ["Red", 32, 41, CRIM, WHITE]],
    [["Benjamin Horne", 1, 30, GOLD, BLACK],
     ["Ben Horne & Beverly Paige", 31, 47, AMBER, BLACK]],
    [["Jerry Horne", 3, 30, OLIVE, WHITE],
     ["Jerry, lost in the woods", 31, 46, FIR, WHITE]],
    [["Josie Packard (dies 2×16)", 1, 24, NAVY, WHITE],
     ["Sylvia & Johnny Horne", 39, 40, LBLUE, BLACK]],
    [["Catherine Martell (and \"Mr. Tojamura\")", 1, 30, PURPLE, WHITE],
     ["Carl Rodd & the Fat Trout Trailer Park", 36, 45, BROWN, WHITE]],
    [["Pete Martell (Jack Nance — gone before the Return)", 1, 30, TAN, BLACK],
     ["The Mitchum brothers (and the pie)", 35, 47, GOLD, BLACK]],
    [["Norma Jennings", 1, 30, CREAM, BLACK],
     ["Norma & Big Ed, finally", 31, 48, TAN, BLACK]],
    [["Big Ed & Nadine Hurley", 1, 30, LGREEN, BLACK],
     ["Nadine's silent drape runners", 35, 45, GREEN, WHITE]],
    [["Dr. Lawrence Jacoby", 1, 30, TEAL, WHITE],
     ["\"Dr. Amp\" and the golden shovels", 31, 43, GOLD, BLACK]],
    [["The Log Lady", 1, 30, BROWN, WHITE],
     ["The Log Lady — Catherine Coulson's last scenes (Part 15)", 31, 45, COFFEE, WHITE]],
    [["Major Garland Briggs", 1, 30, FIR, WHITE],
     ["Briggs — dead 25 years, still leaving messages", 33, 47, GREEN, WHITE]],
  ],

  law: [
    [["Special Agent Dale Cooper", 1, 30, RED, WHITE],
     ["Cooper in the Red Room", 31, 32, DRED, WHITE],
     ["Cooper as \"Dougie Jones\"", 33, 45, GOLD, BLACK],
     ["Cooper is back", 46, 48, CRIM, WHITE]],
    [["Sheriff Harry S. Truman", 1, 30, FIR, WHITE],
     ["Sheriff Frank Truman", 34, 47, GREEN, WHITE]],
    [["Deputy Tommy \"Hawk\" Hill", 1, 30, BROWN, WHITE],
     ["Chief Deputy Hawk", 31, 47, COFFEE, WHITE]],
    [["Deputy Andy Brennan & Lucy Moran", 1, 30, LGREEN, BLACK],
     ["Andy, Lucy & Wally \"Brando\" Brennan", 31, 47, GREEN, WHITE]],
    [["Albert Rosenfield (from 1×03)", 3, 30, NAVY, WHITE],
     ["Albert — Miguel Ferrer's last role", 33, 47, BLUE, WHITE]],
    [["Gordon Cole (David Lynch, from 2×06)", 14, 30, CHAR, WHITE],
     ["Deputy Director Gordon Cole", 33, 47, INK, WHITE]],
    [["Denise Bryson", 19, 21, PINK, BLACK],
     ["Diane Evans", 36, 48, PURPLE, WHITE]],
    [["Annie Blackburn", 25, 30, LBLUE, BLACK],
     ["Agent Tammy Preston", 33, 47, NAVY, WHITE]],
    [["Agent Roger Hardy leans on the sheriff", 18, 19, LGRAY, BLACK],
     ["Janey-E & Sonny Jim Jones", 34, 48, AMBER, BLACK]],
    [["Dr. Will & Eileen Hayward", 1, 30, CREAM, BLACK],
     ["Bushnell Mullins, Lucky 7 Insurance", 35, 47, TEAL, WHITE]],
    [["Dick Tremayne", 11, 29, TAN, BLACK],
     ["Deputy Chad Broxford", 34, 47, GRAY, WHITE]],
    [["Bill Hastings & Buckhorn PD", 31, 41, LBLUE, BLACK],
     ["Freddie Sykes & the green glove", 44, 47, GREEN, WHITE]],
    [["The Fusco brothers", 37, 43, LGRAY, BLACK],
     ["Agent Randall Headley & Agent Wilson", 44, 47, NAVY, WHITE]],
    [["Naido", 33, 33, ROSE, BLACK],
     ["Naido returns", 44, 47, PINK, BLACK]],
  ],

  places: [
    [["The Great Northern Hotel", 1, 30, BROWN, WHITE],
     ["The Great Northern (and that hum)", 31, 48, COFFEE, WHITE]],
    [["The Double R Diner — damn fine coffee & cherry pie", 1, 30, CREAM, BLACK],
     ["The Double R", 31, 48, TAN, BLACK]],
    [["The Roadhouse / Bang Bang Bar", 1, 30, PURPLE, WHITE],
     ["The Roadhouse — a band almost every week", 31, 48, NEON, WHITE]],
    [["The sheriff's station", 1, 30, FIR, WHITE],
     ["The sheriff's station", 31, 48, GREEN, WHITE]],
    [["The Palmer house", 1, 30, LPURP, BLACK],
     ["The Palmer house", 31, 48, PURPLE, WHITE]],
    [["One Eyed Jacks", 3, 21, CRIM, WHITE],
     ["Las Vegas", 33, 48, GOLD, BLACK]],
    [["The Packard sawmill, the mill fire & Ghostwood", 1, 30, OLIVE, WHITE],
     ["Buckhorn, South Dakota", 31, 44, TEAL, WHITE]],
    [["Cooper's dream: the Red Room", 3, 3, RED, WHITE],
     ["Visions of the Lodge", 15, 29, DRED, WHITE],
     ["The Black Lodge", 30, 30, INK, WHITE],
     ["The Red Room, the mauve zone & the Fireman's place", 31, 48, RED, WHITE]],
    [["Glastonbury Grove & the sycamores", 27, 30, FIR, WHITE],
     ["New York: the glass box", 31, 32, NAVY, WHITE],
     ["The convenience store above", 38, 47, CHAR, WHITE],
     ["Odessa, Texas", 48, 48, AMBER, BLACK]],
    [["Julee Cruise", 1, 1, LPURP, BLACK], ["Julee Cruise", 15, 15, LPURP, BLACK],
     ["Chromatics", 32, 32, NEON, WHITE], ["The Cactus Blossoms", 33, 33, TAN, BLACK],
     ["Au Revoir Simone", 34, 34, LBLUE, BLACK], ["Trouble", 35, 35, CRIM, WHITE],
     ["Sharon Van Etten", 36, 36, LGREEN, BLACK], ["\"The\" Nine Inch Nails", 38, 38, INK, WHITE],
     ["Au Revoir Simone", 39, 39, LBLUE, BLACK], ["Rebekah Del Rio (and Moby)", 40, 40, PURPLE, WHITE],
     ["Chromatics", 42, 42, NEON, WHITE], ["James Hurley — \"Just You\"", 43, 43, BLUE, WHITE],
     ["Lissie", 44, 44, GOLD, BLACK], ["The Veils", 45, 45, GRAY, WHITE],
     ["Eddie Vedder", 46, 46, OLIVE, WHITE], ["Julee Cruise", 47, 47, LPURP, BLACK]],
  ],
};

window.SEASON_META = {
  1: { years: "1990",    showrunner: "Lynch & Frost" },
  2: { years: "1990–91", showrunner: "Frost, Peyton & Engels" },
  3: { years: "2017",    showrunner: "Lynch & Frost" },
};
