// Twin Peaks — episode tags. Keys are TVmaze season.episode, matching episodes.json
// (the Pilot is 1.1, so original-broadcast "Episode N" is 1.N+1 / 2.N-7).
// Season premieres and finales are auto-tagged by the engine and are not listed here.
window.TAG_DEFS = {
  fanfav:    {label:"Fan favorite", desc:"The ones people rewatch, quote and argue about"},
  lynch:     {label:"Lynch-directed", desc:"David Lynch behind the camera — 6 of the original 30, all 18 Parts"},
  lodge:     {label:"Dream / Lodge sequence", desc:"The Red Room, the Black Lodge, the visions, the backwards talking"},
  reveal:    {label:"The reveal", desc:"The plot turns and there's no going back"},
  weird:     {label:"Peak Lynch weirdness", desc:"Sound design, silence, and something that doesn't explain itself"},
  heavy:     {label:"Gut-punch", desc:"The ones that hurt"},
  soap:      {label:"Soap-opera detour", desc:"The post-reveal S2 drift — pine weasels, Little Nicky, the James road trip"},
  experiment:{label:"Format experiment", desc:"An hour that abandons the show's own shape"},
  roadhouse: {label:"Roadhouse performance", desc:"The episode ends at the Bang Bang Bar"},
  music:     {label:"Musical guest", desc:"A band or singer plays, credited as themselves"},
  dougie:    {label:"Dougie comedy", desc:"Cooper adrift in Las Vegas, and everyone deciding it's fine"},

  cooper:{label:"Cooper spotlight"}, laura:{label:"Laura spotlight"}, leland:{label:"Leland spotlight"},
  audrey:{label:"Audrey spotlight"}, donna:{label:"Donna spotlight"}, bobby:{label:"Bobby spotlight"},
  shelly:{label:"Shelly spotlight"}, albert:{label:"Albert spotlight"}, gordon:{label:"Gordon Cole spotlight"},
  diane:{label:"Diane spotlight"}, hawk:{label:"Hawk spotlight"}, logLady:{label:"Log Lady spotlight"},
  sarah:{label:"Sarah Palmer spotlight"}, windom:{label:"Windom Earle spotlight"},
  mrc:{label:"Mr. C spotlight"}, ben:{label:"Ben Horne spotlight"},
};

window.EP_TAGS = {
  // S1 — eight hours, and the town is already the point
  "1.1":["fanfav","lynch","heavy","cooper","laura","leland","roadhouse","music"],
  "1.2":["cooper","audrey","donna"],
  "1.3":["fanfav","lynch","lodge","weird","cooper","albert"],
  "1.4":["heavy","leland","donna","albert"],
  "1.5":["cooper","leland","hawk"],
  "1.6":["cooper","logLady","weird","donna"],
  "1.7":["audrey","cooper","ben"],
  "1.8":["fanfav","audrey","cooper","heavy"],

  // S2 — the reveal at the halfway point, then the long drift, then the Lodge
  "2.1":["fanfav","lynch","lodge","weird","cooper"],
  "2.2":["lynch","lodge","weird","donna","audrey"],
  "2.3":["leland","cooper","weird"],
  "2.4":["donna","audrey","albert"],
  "2.5":["cooper","audrey","ben"],
  "2.6":["gordon","leland","ben"],
  "2.7":["fanfav","lynch","reveal","heavy","lodge","weird","leland","laura","roadhouse","music"],
  "2.8":["heavy","leland","weird"],
  "2.9":["fanfav","reveal","heavy","lodge","leland","cooper","albert"],
  "2.10":["soap","ben"],
  "2.11":["soap","donna"],
  "2.12":["soap","ben"],
  "2.13":["soap","windom","cooper"],
  "2.14":["soap","windom"],
  "2.15":["soap","windom","shelly"],
  "2.16":["heavy","lodge","weird"],
  "2.17":["cooper","shelly","bobby"],
  "2.18":["soap","donna","ben"],
  "2.19":["soap","windom","audrey"],
  "2.20":["lodge","windom","cooper"],
  "2.21":["windom","lodge","audrey","shelly"],
  "2.22":["fanfav","lynch","lodge","heavy","weird","cooper","windom","laura"],

  // S3 — The Return
  "3.1":["lynch","lodge","weird","cooper","mrc"],
  "3.2":["lynch","lodge","weird","mrc","leland","laura","roadhouse","music"],
  "3.3":["fanfav","lynch","lodge","weird","cooper","dougie","roadhouse","music"],
  "3.4":["lynch","dougie","gordon","albert","bobby","roadhouse","music"],
  "3.5":["lynch","dougie","mrc","shelly","roadhouse","music"],
  "3.6":["lynch","heavy","dougie","weird","roadhouse","music"],
  "3.7":["lynch","dougie","hawk","diane","gordon","weird"],
  "3.8":["fanfav","lynch","experiment","weird","lodge","heavy","mrc","roadhouse","music"],
  "3.9":["lynch","gordon","diane","bobby","albert","roadhouse","music"],
  "3.10":["lynch","dougie","heavy","roadhouse","music"],
  "3.11":["fanfav","lynch","weird","heavy","dougie","gordon"],
  "3.12":["lynch","audrey","gordon","sarah","diane","roadhouse","music"],
  "3.13":["fanfav","lynch","dougie","audrey","heavy","roadhouse","music"],
  "3.14":["fanfav","lynch","weird","lodge","sarah","gordon","diane","roadhouse","music"],
  "3.15":["lynch","heavy","logLady","weird","roadhouse","music"],
  "3.16":["fanfav","lynch","cooper","audrey","diane","heavy","roadhouse","music"],
  "3.17":["fanfav","lynch","lodge","reveal","cooper","gordon","laura","roadhouse","music"],
  "3.18":["fanfav","lynch","heavy","weird","laura","cooper","diane","sarah"],
};
