apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: across-the-eras-github
  namespace: across-the-eras
  labels:
    app: across-the-eras
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local:8080
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: eeca9819-709a-4f0b-96a0-fcfe50d0771a
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: across-the-eras-infisical
        namespace: across-the-eras
      secretsScope:
        projectSlug: across-the-eras-qbd6
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: across-the-eras-github
    secretNamespace: across-the-eras
    creationPolicy: Orphan
