// The Wire — episode tags. Keys are TVmaze season.episode, matching episodes.json.
// Season premieres and finales are auto-tagged by the engine and are not listed here.
window.TAG_DEFS = {
  fanfav:    {label:"Fan favorite", desc:"The ones people rewatch and quote"},
  pieces:    {label:"All the pieces matter", desc:"Arc-critical — skip it and the season stops making sense"},
  heavy:     {label:"Gut-punch", desc:"The ones that hurt"},
  death:     {label:"A major death", desc:"Someone you know doesn't make it out"},
  monologue: {label:"Standout scene / monologue", desc:"Snot Boogie, the chess lesson, \"fuck\", the Gatsby speech…"},
  montage:   {label:"Closing montage", desc:"The season-ending sweep across the city"},
  courtroom: {label:"Courtroom", desc:"The law's machinery, on the record"},

  port:      {label:"The docks", desc:"Local 1514, the cans, the Greeks"},
  hamsterdam:{label:"Hamsterdam", desc:"Colvin's free zones"},
  coop:      {label:"The Co-Op & the connect", desc:"Prop Joe's New Day Co-Operative and the package"},
  school:    {label:"The schools", desc:"Tilghman Middle and the special class"},
  hall:      {label:"City Hall", desc:"Campaigns, commissioners and the money"},
  paper:     {label:"The newsroom", desc:"The Baltimore Sun"},
  boys:      {label:"The boys of S4", desc:"Michael, Dukie, Randy and Namond"},

  mcnulty:{label:"McNulty spotlight"}, omar:{label:"Omar spotlight"}, bubbles:{label:"Bubbles spotlight"},
  stringer:{label:"Stringer spotlight"}, avon:{label:"Avon spotlight"}, dangelo:{label:"D'Angelo spotlight"},
  bunk:{label:"Bunk spotlight"}, kima:{label:"Kima spotlight"}, freamon:{label:"Freamon spotlight"},
  daniels:{label:"Daniels spotlight"}, carcetti:{label:"Carcetti spotlight"}, colvin:{label:"Bunny Colvin spotlight"},
  prez:{label:"Prez spotlight"}, marlo:{label:"Marlo spotlight"}, bodie:{label:"Bodie spotlight"},
  joe:{label:"Prop Joe spotlight"}, carver:{label:"Carver spotlight"}, herc:{label:"Herc spotlight"},
  cutty:{label:"Cutty spotlight"},
};

window.EP_TAGS = {
  // S1 — the towers & the detail
  "1.1":["fanfav","monologue","pieces","mcnulty","dangelo","daniels"],
  "1.2":["pieces","freamon","kima","prez","daniels"],
  "1.3":["fanfav","monologue","pieces","omar","dangelo","bodie"],
  "1.4":["fanfav","monologue","bunk","mcnulty"],
  "1.5":["pieces","freamon","omar","kima"],
  "1.6":["pieces","freamon","prez","kima"],
  "1.7":["pieces","kima","carver","herc"],
  "1.8":["fanfav","monologue","hall","omar","mcnulty"],
  "1.9":["fanfav","omar","joe","avon","stringer"],
  "1.10":["fanfav","heavy","pieces","kima"],
  "1.11":["heavy","pieces","kima","daniels","bunk"],
  "1.12":["fanfav","heavy","death","pieces","bodie","stringer"],
  "1.13":["fanfav","montage","pieces","dangelo","avon","mcnulty"],

  // S2 — the port
  "2.1":["port","pieces","mcnulty"],
  "2.2":["port","heavy","pieces","bunk"],
  "2.3":["port","heavy","bubbles"],
  "2.4":["port","pieces","daniels","freamon"],
  "2.5":["port","pieces","omar","stringer"],
  "2.6":["fanfav","heavy","death","monologue","courtroom","pieces","dangelo","omar","stringer"],
  "2.7":["port","pieces","bunk"],
  "2.8":["port","heavy","mcnulty","bunk"],
  "2.9":["port","heavy","pieces","stringer"],
  "2.10":["port","heavy","pieces","omar"],
  "2.11":["fanfav","heavy","death","port","pieces"],
  "2.12":["fanfav","montage","port","pieces","daniels"],

  // S3 — City Hall & Hamsterdam
  "3.1":["pieces","marlo","cutty","stringer"],
  "3.2":["pieces","colvin","stringer","marlo"],
  "3.3":["fanfav","monologue","heavy","colvin","bunk"],
  "3.4":["fanfav","hamsterdam","pieces","colvin","carver"],
  "3.5":["hamsterdam","pieces","colvin","cutty"],
  "3.6":["pieces","avon","stringer","joe","coop","bodie"],
  "3.7":["hamsterdam","pieces","freamon","coop"],
  "3.8":["fanfav","heavy","pieces","stringer","avon","colvin"],
  "3.9":["hamsterdam","pieces","colvin","mcnulty","prez"],
  "3.10":["hamsterdam","pieces","colvin","stringer","prez"],
  "3.11":["fanfav","heavy","death","monologue","pieces","stringer","avon","omar","colvin"],
  "3.12":["fanfav","montage","pieces","hamsterdam","avon","colvin","mcnulty"],

  // S4 — the schools
  "4.1":["fanfav","boys","school","pieces","prez","marlo"],
  "4.2":["school","hall","boys","carcetti","bunk"],
  "4.3":["school","boys","prez","pieces"],
  "4.4":["school","boys","prez","carcetti"],
  "4.5":["school","hall","boys","pieces","carcetti","omar"],
  "4.6":["fanfav","hall","pieces","carcetti","school","boys"],
  "4.7":["pieces","omar","bodie","boys","school"],
  "4.8":["fanfav","school","boys","colvin","pieces"],
  "4.9":["school","boys","hall","carcetti","colvin"],
  "4.10":["heavy","school","boys","colvin","carver"],
  "4.11":["pieces","hall","carcetti","omar","boys"],
  "4.12":["fanfav","heavy","boys","bubbles","pieces","school"],
  "4.13":["fanfav","heavy","death","montage","pieces","bodie","boys","bubbles","freamon"],

  // S5 — the newspaper
  "5.1":["paper","pieces","mcnulty","freamon"],
  "5.2":["paper","pieces","mcnulty","marlo"],
  "5.3":["paper","pieces","mcnulty","marlo","coop"],
  "5.4":["heavy","death","pieces","daniels","marlo","omar","hall"],
  "5.5":["fanfav","heavy","death","pieces","joe","marlo","paper","coop"],
  "5.6":["paper","pieces","omar","marlo","freamon"],
  "5.7":["fanfav","courtroom","monologue","hall","pieces","freamon"],
  "5.8":["fanfav","heavy","death","pieces","omar","paper"],
  "5.9":["fanfav","heavy","death","pieces","marlo","freamon","boys","mcnulty"],
  "5.10":["fanfav","montage","pieces","mcnulty","daniels","bubbles","paper","marlo"],
};
