window.TAG_DEFS = {
  fanfav:    { label: "Fan favorite", desc: "The ones people bring up first" },
  cringe:    { label: "Cringe comedy", desc: "Heavy secondhand embarrassment" },
  milestone: { label: "Milestone", desc: "Hinge points in Pied Piper's story" },
  heavy:     { label: "Gut-punch", desc: "" },
  arc:       { label: "Arc-heavy", desc: "Directly advances the season-long plot" },
  standalone:{ label: "Standalone-ish", desc: "More of a self-contained B-plot week" },
  richard:   { label: "Richard spotlight" },
  erlich:    { label: "Erlich spotlight" },
  dinesh:    { label: "Dinesh spotlight" },
  gilfoyle:  { label: "Gilfoyle spotlight" },
  jared:     { label: "Jared spotlight" },
  bighead:   { label: "Big Head spotlight" },
  monica:    { label: "Monica spotlight" },
  gavin:     { label: "Gavin spotlight" },
  jianyang:  { label: "Jian-Yang spotlight" },
  laurie:    { label: "Laurie Bream spotlight" },
  russ:      { label: "Russ Hanneman spotlight" },
};

window.EP_TAGS = {
  "1.1": ["milestone","richard","gavin","cringe"],
  "1.2": ["jared","erlich","standalone"],
  "1.3": ["erlich","gavin","standalone"],
  "1.4": ["bighead","cringe","standalone"],
  "1.5": ["erlich","arc"],
  "1.6": ["dinesh","erlich","standalone","cringe"],
  "1.7": ["arc","monica","richard"],
  "1.8": ["milestone","fanfav","cringe","arc","richard","gavin"],

  "2.1": ["laurie","monica","arc"],
  "2.2": ["dinesh","arc"],
  "2.3": ["russ","milestone","fanfav"],
  "2.4": ["bighead","cringe"],
  "2.5": ["gilfoyle","standalone"],
  "2.6": ["erlich","jared","standalone"],
  "2.7": ["arc","russ"],
  "2.8": ["richard","gavin","arc"],
  "2.9": ["milestone","arc","gavin"],
  "2.10": ["milestone","fanfav","arc","richard"],

  "3.1": ["milestone","richard","gavin","erlich"],
  "3.2": ["cringe","fanfav","jared","erlich"],
  "3.3": ["richard","gilfoyle","arc"],
  "3.4": ["gavin","standalone"],
  "3.5": ["richard","standalone"],
  "3.6": ["cringe","fanfav","erlich","bighead"],
  "3.7": ["arc","dinesh","gilfoyle"],
  "3.8": ["milestone","erlich","gavin","arc"],
  "3.9": ["jared","richard","arc"],
  "3.10": ["milestone","fanfav","richard","jared","laurie","arc"],

  "4.1": ["milestone","richard","gavin"],
  "4.2": ["milestone","dinesh","cringe","fanfav","gavin","jianyang"],
  "4.3": ["richard","bighead","monica","jianyang"],
  "4.4": ["richard","gilfoyle","gavin","jianyang","arc"],
  "4.5": ["gavin","cringe","fanfav","dinesh"],
  "4.6": ["erlich","richard","standalone"],
  "4.7": ["richard","gilfoyle","jianyang"],
  "4.8": ["richard","erlich","arc"],
  "4.9": ["fanfav","arc"],
  "4.10": ["milestone","heavy","richard","jared","fanfav"],

  "5.1": ["milestone","richard","gavin"],
  "5.2": ["richard","dinesh","gilfoyle"],
  "5.3": ["richard","gilfoyle","dinesh","cringe"],
  "5.4": ["richard","gavin","bighead","jared"],
  "5.5": ["milestone","cringe","fanfav","richard","jared","laurie"],
  "5.6": ["richard","gavin","jared","cringe","laurie"],
  "5.7": ["russ","gilfoyle","dinesh"],
  "5.8": ["milestone","fanfav","arc","richard","gilfoyle","monica"],

  "6.1": ["richard","jared","gilfoyle","dinesh"],
  "6.2": ["richard","jared","gavin"],
  "6.3": ["dinesh","jared","richard"],
  "6.4": ["cringe","richard","monica","gavin"],
  "6.5": ["milestone","gavin","gilfoyle","monica","dinesh"],
  "6.6": ["fanfav","russ","jianyang","monica"],
  "6.7": ["milestone","fanfav","heavy","richard","jianyang","jared","dinesh","gilfoyle"],
};
