// Battlestar Galactica — episode tags. Keys are TVmaze season.episode as used in episodes.json.
// "1.0" is the 2003 Miniseries (see NOTES.md). Season premieres and finales are auto-tagged
// by the engine and are not listed here.
window.TAG_DEFS = {
  fanfav:    {label:"Fan favorite", desc:"The hours people rewatch, quote and argue about"},
  milestone: {label:"Milestone", desc:"A hinge the whole series turns on"},
  myth:      {label:"Mythology-heavy", desc:"Kobol, the scrolls, the Five, the Opera House — the arc proper"},
  heavy:     {label:"Gut-punch", desc:"The ones that hurt"},
  death:     {label:"A major death", desc:"Someone you know doesn't make it out"},
  battle:    {label:"Battle set-piece", desc:"Vipers, flak, and the big fleet actions"},
  experiment:{label:"Format experiment", desc:"The show breaking its own shape — real time, documentary, flashback, exposition"},
  cylonpov:  {label:"Cylon POV", desc:"Told from the other side of the war"},
  politics:  {label:"Politics & the law", desc:"Elections, the Quorum, tribunals, the trial"},
  cliff:     {label:"Cliffhanger", desc:"Ends on a drop"},
  twopart:   {label:"Two-parter", desc:"Half of a matched pair (or a feature-length event)"},
  standalone:{label:"Standalone", desc:"A self-contained hour you can skip and still follow the arc"},

  adama:   {label:"Adama spotlight"},
  roslin:  {label:"Roslin spotlight"},
  starbuck:{label:"Starbuck spotlight"},
  apollo:  {label:"Apollo spotlight"},
  baltar:  {label:"Baltar spotlight"},
  six:     {label:"Number Six spotlight"},
  tigh:    {label:"Tigh spotlight"},
  sharon:  {label:"Boomer / Athena spotlight"},
  helo:    {label:"Helo spotlight"},
  tyrol:   {label:"Tyrol spotlight"},
  gaeta:   {label:"Gaeta spotlight"},
  cain:    {label:"Admiral Cain spotlight"},
  danna:   {label:"D'Anna spotlight"},
};

window.EP_TAGS = {
  // The Miniseries + Season 1
  "1.0":["milestone","myth","heavy","battle","twopart","adama","roslin","baltar","six","starbuck"],
  "1.1":["fanfav","experiment","heavy","myth","baltar","six","starbuck"],
  "1.2":["sharon","tyrol","roslin"],
  "1.3":["politics","apollo","roslin"],
  "1.4":["heavy","starbuck","adama"],
  "1.5":["starbuck","adama","apollo"],
  "1.6":["politics","tyrol","sharon"],
  "1.7":["baltar","six","standalone"],
  "1.8":["fanfav","heavy","myth","starbuck","roslin"],
  "1.9":["standalone","tigh"],
  "1.10":["fanfav","battle","apollo","starbuck","baltar"],
  "1.11":["politics","baltar","roslin"],
  "1.12":["myth","twopart","cliff","starbuck","roslin"],
  "1.13":["fanfav","myth","twopart","cliff","heavy","milestone","adama","sharon","starbuck"],

  // Season 2
  "2.1":["myth","tigh","adama"],
  "2.2":["battle","tigh","apollo"],
  "2.3":["heavy","baltar","roslin"],
  "2.4":["heavy","death","politics","tigh","sharon"],
  "2.5":["heavy","myth","starbuck","helo"],
  "2.6":["myth","twopart","apollo","roslin"],
  "2.7":["fanfav","myth","twopart","adama","roslin","starbuck"],
  "2.8":["experiment","cylonpov","danna","tigh"],
  "2.9":["fanfav","tyrol","sharon"],
  "2.10":["fanfav","heavy","cliff","cain","sharon","tyrol","helo"],
  "2.11":["twopart","myth","cain","adama","starbuck"],
  "2.12":["fanfav","battle","twopart","death","cain","adama","apollo"],
  "2.13":["roslin","baltar","politics"],
  "2.14":["standalone","apollo"],
  "2.15":["standalone","battle","starbuck"],
  "2.16":["heavy","death","apollo","roslin"],
  "2.17":["politics","apollo","roslin"],
  "2.18":["fanfav","experiment","cylonpov","myth","six","sharon"],
  "2.19":["twopart","politics","tyrol","starbuck"],
  "2.20":["milestone","fanfav","twopart","cliff","politics","heavy","baltar","roslin","adama"],

  // Season 3
  "3.1":["heavy","starbuck","tigh","danna","twopart"],
  "3.2":["heavy","death","twopart","baltar","roslin"],
  "3.3":["twopart","heavy","death","tigh","tyrol"],
  "3.4":["fanfav","milestone","battle","twopart","heavy","adama","apollo","tigh"],
  "3.5":["politics","heavy","gaeta","tyrol"],
  "3.6":["cylonpov","myth","baltar","starbuck"],
  "3.7":["politics","heavy","helo","cylonpov"],
  "3.8":["standalone","adama"],
  "3.9":["fanfav","experiment","heavy","starbuck","apollo","adama"],
  "3.10":["heavy","death","starbuck"],
  "3.11":["myth","twopart","cliff","tyrol","danna"],
  "3.12":["myth","twopart","battle","danna","sharon","six"],
  "3.13":["baltar","politics","starbuck","apollo"],
  "3.14":["standalone","helo"],
  "3.15":["standalone","adama","tyrol"],
  "3.16":["politics","tyrol","baltar"],
  "3.17":["fanfav","heavy","death","myth","experiment","starbuck","adama"],
  "3.18":["politics","apollo","adama"],
  "3.19":["politics","twopart","baltar","apollo","tigh"],
  "3.20":["milestone","fanfav","myth","twopart","cliff","politics","tigh","tyrol","baltar","starbuck"],

  // Season 4
  "4.1":["myth","starbuck","baltar","tigh"],
  "4.2":["fanfav","cylonpov","myth","starbuck","six","adama"],
  "4.3":["heavy","death","tyrol","apollo","politics"],
  "4.4":["heavy","baltar","tigh"],
  "4.5":["starbuck","baltar","tyrol"],
  "4.6":["myth","heavy","starbuck","roslin"],
  "4.7":["myth","cliff","danna","sharon","roslin"],
  "4.8":["politics","adama","apollo","roslin"],
  "4.9":["fanfav","myth","heavy","roslin","baltar","danna"],
  "4.10":["milestone","fanfav","myth","heavy","cliff","tigh","adama","apollo"],
  "4.11":["fanfav","heavy","death","myth","tigh","adama","starbuck","danna"],
  "4.12":["politics","gaeta","adama","roslin"],
  "4.13":["fanfav","battle","heavy","cliff","twopart","gaeta","adama","apollo"],
  "4.14":["fanfav","battle","heavy","death","twopart","gaeta","adama","roslin"],
  "4.15":["myth","experiment","cylonpov","tigh","six"],
  "4.16":["politics","tigh","six","baltar"],
  "4.17":["fanfav","heavy","starbuck","sharon","tyrol"],
  "4.18":["heavy","adama","starbuck","roslin"],
  "4.19":["myth","twopart","experiment","heavy","adama","roslin","baltar","apollo"],
  "4.20":["milestone","fanfav","battle","myth","heavy","twopart","adama","roslin","starbuck","baltar","six","tigh"],
};
