// Generated by the skipto.tv show-submission service from declarative data.
window.ERA_CATS = [
  [
    "era",
    "Production era"
  ],
  [
    "team",
    "The fellowship"
  ],
  [
    "constants",
    "Around House"
  ],
  [
    "arcs",
    "Arcs & antagonists"
  ]
];
window.ERAS = {
  "era": [
    [
      [
        "David Shore — creator & showrunner",
        1,
        8,
        "#7b2d26",
        "#ffffff"
      ]
    ],
    [
      [
        "Fox, Tuesdays at 9",
        1,
        4,
        "#a8453c",
        "#ffffff"
      ],
      [
        "Mondays at 8",
        5,
        7,
        "#7b2d26",
        "#ffffff"
      ],
      [
        "Mondays at 9",
        8,
        8,
        "#a8453c",
        "#ffffff"
      ]
    ],
    [
      [
        "Ratings peak — top 10 in the Nielsen season rankings",
        2,
        4,
        "#a8453c",
        "#ffffff"
      ]
    ],
    [
      [
        "Writers' strike cuts the season to 16 episodes",
        4,
        4,
        "#7b2d26",
        "#ffffff"
      ]
    ]
  ],
  "team": [
    [
      [
        "Eric Foreman — original team",
        1,
        3,
        "#2f6f8f",
        "#ffffff"
      ],
      [
        "Foreman returns; Dean of Medicine from 8×01",
        4,
        8,
        "#4a90b8",
        "#ffffff"
      ]
    ],
    [
      [
        "Robert Chase — original team (fired 3×24)",
        1,
        3,
        "#4a90b8",
        "#ffffff"
      ],
      [
        "Chase in surgery, rejoins diagnostics 6×07 (leaves 8×20)",
        4,
        8,
        "#2f6f8f",
        "#ffffff"
      ]
    ],
    [
      [
        "Allison Cameron — original team (resigns 3×24)",
        1,
        3,
        "#2f6f8f",
        "#ffffff"
      ],
      [
        "Cameron runs the ER (leaves in 6×08)",
        4,
        6,
        "#4a90b8",
        "#ffffff"
      ]
    ],
    [
      [
        "The fellowship competition — 40 applicants down to three",
        4,
        4,
        "#4a90b8",
        "#ffffff"
      ]
    ],
    [
      [
        "Remy 'Thirteen' Hadley (hired 4×10)",
        4,
        7,
        "#2f6f8f",
        "#ffffff"
      ]
    ],
    [
      [
        "Chris Taub (hired 4×10)",
        4,
        8,
        "#4a90b8",
        "#ffffff"
      ]
    ],
    [
      [
        "Lawrence Kutner (hired 4×10; dies 5×20)",
        4,
        5,
        "#2f6f8f",
        "#ffffff"
      ]
    ],
    [
      [
        "Martha Masters",
        7,
        7,
        "#4a90b8",
        "#ffffff"
      ]
    ],
    [
      [
        "Jessica Adams",
        8,
        8,
        "#2f6f8f",
        "#ffffff"
      ]
    ],
    [
      [
        "Chi Park",
        8,
        8,
        "#4a90b8",
        "#ffffff"
      ]
    ]
  ],
  "constants": [
    [
      [
        "James Wilson — Head of Oncology, and the only friend",
        1,
        8,
        "#3f6b52",
        "#ffffff"
      ]
    ],
    [
      [
        "Lisa Cuddy — Dean of Medicine",
        1,
        7,
        "#5c9074",
        "#ffffff"
      ]
    ],
    [
      [
        "Stacy Warner — the ex, then hospital counsel",
        1,
        2,
        "#3f6b52",
        "#ffffff"
      ]
    ],
    [
      [
        "Lucas Douglas — the private investigator",
        5,
        6,
        "#5c9074",
        "#ffffff"
      ]
    ],
    [
      [
        "Dr. Nolan and Mayfield",
        5,
        6,
        "#3f6b52",
        "#ffffff"
      ]
    ],
    [
      [
        "Dominika — the green-card wife",
        8,
        8,
        "#5c9074",
        "#ffffff"
      ]
    ]
  ],
  "arcs": [
    [
      [
        "Edward Vogler buys the hospital (1×14–1×18)",
        1,
        1,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "Det. Michael Tritter (3×05–3×11)",
        3,
        3,
        "#b07d3f",
        "#ffffff"
      ],
      [
        "House resigns; Foreman runs the team (6×02–6×06)",
        6,
        6,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "Foreman as Dean; House on an ankle monitor",
        8,
        8,
        "#b07d3f",
        "#ffffff"
      ]
    ],
    [
      [
        "The infarction, the cane, the Vicodin",
        1,
        5,
        "#b07d3f",
        "#ffffff"
      ],
      [
        "Post-Mayfield sobriety",
        6,
        7,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "A year in East New Jersey Correctional, then parole",
        8,
        8,
        "#b07d3f",
        "#ffffff"
      ]
    ],
    [
      [
        "Ketamine remission, then the pain comes back (3×01–3×03)",
        3,
        3,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "The bus crash kills Amber (4×15–4×16)",
        4,
        4,
        "#b07d3f",
        "#ffffff"
      ],
      [
        "Amber hallucinations → detox at Mayfield (5×23–6×01)",
        5,
        6,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "The self-medicating relapse (7×21–7×23)",
        7,
        7,
        "#b07d3f",
        "#ffffff"
      ]
    ],
    [
      [
        "House & Stacy",
        1,
        2,
        "#b07d3f",
        "#ffffff"
      ],
      [
        "Chase & Cameron",
        3,
        6,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "House & Cuddy, then the dining room wall",
        7,
        7,
        "#b07d3f",
        "#ffffff"
      ]
    ],
    [
      [
        "Wilson & Amber",
        4,
        4,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "Wilson's grief; he quits and comes back",
        5,
        5,
        "#b07d3f",
        "#ffffff"
      ],
      [
        "Wilson & Sam",
        6,
        7,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "Wilson's cancer",
        8,
        8,
        "#b07d3f",
        "#ffffff"
      ]
    ],
    [
      [
        "Cuddy adopts Rachel",
        5,
        7,
        "#8a5a2b",
        "#ffffff"
      ],
      [
        "Taub's twins",
        8,
        8,
        "#b07d3f",
        "#ffffff"
      ]
    ],
    [
      [
        "The Dibala case and what Chase did (6×03–6×05)",
        6,
        6,
        "#b07d3f",
        "#ffffff"
      ]
    ]
  ]
};
window.SEASON_META = {
  "1": {
    "years": "2004–05",
    "showrunner": "David Shore"
  },
  "2": {
    "years": "2005–06",
    "showrunner": "David Shore"
  },
  "3": {
    "years": "2006–07",
    "showrunner": "David Shore"
  },
  "4": {
    "years": "2007–08",
    "showrunner": "David Shore"
  },
  "5": {
    "years": "2008–09",
    "showrunner": "David Shore"
  },
  "6": {
    "years": "2009–10",
    "showrunner": "David Shore"
  },
  "7": {
    "years": "2010–11",
    "showrunner": "David Shore"
  },
  "8": {
    "years": "2011–12",
    "showrunner": "David Shore"
  }
};
