// Generated by the skipto.tv show-submission service from declarative data.
window.TAG_DEFS = {
  "fanfav": {
    "label": "Fan favorite",
    "desc": "The ones people rewatch first"
  },
  "heavy": {
    "label": "Gut-punch",
    "desc": "Bring tissues"
  },
  "experiment": {
    "label": "Format experiment",
    "desc": "The show breaking its own rules"
  },
  "bottle": {
    "label": "Bottle / one location",
    "desc": "One room, one building, or one very long night"
  },
  "twoparter": {
    "label": "Two-parter",
    "desc": "Told across two episodes"
  },
  "holiday": {
    "label": "Holiday episode",
    "desc": "Christmas, Thanksgiving, Valentine's"
  },
  "teamshift": {
    "label": "Team shake-up",
    "desc": "Someone is hired, fired, quits or dies"
  },
  "crisis": {
    "label": "House in crisis",
    "desc": "The episodes about House rather than the patient"
  },
  "wilson": {
    "label": "Wilson spotlight",
    "desc": "Wilson spotlight"
  },
  "cuddy": {
    "label": "Cuddy spotlight",
    "desc": "Cuddy spotlight"
  },
  "foreman": {
    "label": "Foreman spotlight",
    "desc": "Foreman spotlight"
  },
  "chase": {
    "label": "Chase spotlight",
    "desc": "Chase spotlight"
  },
  "cameron": {
    "label": "Cameron spotlight",
    "desc": "Cameron spotlight"
  },
  "thirteen": {
    "label": "Thirteen spotlight",
    "desc": "Thirteen spotlight"
  },
  "taub": {
    "label": "Taub spotlight",
    "desc": "Taub spotlight"
  }
};
window.EP_TAGS = {
  "1.11": [
    "fanfav",
    "crisis"
  ],
  "1.21": [
    "fanfav",
    "experiment"
  ],
  "2.2": [
    "fanfav",
    "heavy"
  ],
  "2.10": [
    "fanfav"
  ],
  "2.19": [
    "fanfav"
  ],
  "2.20": [
    "fanfav",
    "twoparter",
    "foreman"
  ],
  "2.21": [
    "fanfav",
    "heavy",
    "twoparter",
    "foreman"
  ],
  "2.24": [
    "fanfav",
    "heavy",
    "experiment",
    "bottle",
    "crisis"
  ],
  "3.7": [
    "fanfav"
  ],
  "3.15": [
    "fanfav"
  ],
  "4.15": [
    "fanfav",
    "experiment",
    "twoparter"
  ],
  "4.16": [
    "fanfav",
    "heavy",
    "twoparter",
    "wilson"
  ],
  "5.19": [
    "fanfav",
    "experiment",
    "bottle"
  ],
  "5.20": [
    "fanfav",
    "heavy",
    "teamshift"
  ],
  "5.23": [
    "fanfav",
    "heavy",
    "twoparter",
    "crisis"
  ],
  "5.24": [
    "fanfav",
    "heavy",
    "twoparter",
    "crisis"
  ],
  "6.1": [
    "fanfav",
    "heavy",
    "experiment",
    "bottle",
    "crisis"
  ],
  "6.9": [
    "fanfav",
    "experiment",
    "wilson"
  ],
  "6.13": [
    "fanfav",
    "experiment",
    "cuddy"
  ],
  "6.20": [
    "fanfav",
    "experiment"
  ],
  "6.21": [
    "fanfav",
    "heavy",
    "cuddy"
  ],
  "7.13": [
    "fanfav",
    "experiment"
  ],
  "7.15": [
    "fanfav",
    "heavy",
    "experiment",
    "cuddy"
  ],
  "7.18": [
    "fanfav",
    "thirteen"
  ],
  "7.22": [
    "fanfav",
    "crisis",
    "thirteen"
  ],
  "8.11": [
    "fanfav",
    "heavy",
    "experiment"
  ],
  "8.19": [
    "fanfav",
    "heavy",
    "wilson"
  ],
  "8.22": [
    "fanfav",
    "heavy",
    "crisis",
    "wilson"
  ],
  "3.24": [
    "heavy",
    "teamshift"
  ],
  "5.1": [
    "heavy",
    "wilson"
  ],
  "8.18": [
    "heavy",
    "wilson"
  ],
  "8.21": [
    "heavy",
    "wilson"
  ],
  "2.8": [
    "experiment",
    "chase"
  ],
  "3.12": [
    "experiment",
    "bottle"
  ],
  "4.7": [
    "experiment",
    "teamshift"
  ],
  "4.11": [
    "experiment",
    "bottle"
  ],
  "6.16": [
    "experiment",
    "bottle"
  ],
  "8.12": [
    "experiment",
    "chase"
  ],
  "5.9": [
    "bottle"
  ],
  "8.1": [
    "bottle",
    "teamshift",
    "crisis"
  ],
  "1.5": [
    "holiday"
  ],
  "3.10": [
    "holiday",
    "crisis"
  ],
  "3.14": [
    "holiday"
  ],
  "5.11": [
    "holiday"
  ],
  "6.8": [
    "holiday",
    "cameron"
  ],
  "1.16": [
    "teamshift"
  ],
  "3.22": [
    "teamshift",
    "foreman"
  ],
  "4.1": [
    "teamshift"
  ],
  "4.2": [
    "teamshift"
  ],
  "4.3": [
    "teamshift"
  ],
  "4.4": [
    "teamshift"
  ],
  "4.5": [
    "teamshift"
  ],
  "4.6": [
    "teamshift"
  ],
  "4.8": [
    "teamshift"
  ],
  "4.9": [
    "teamshift"
  ],
  "6.2": [
    "teamshift",
    "foreman"
  ],
  "6.7": [
    "teamshift"
  ],
  "7.4": [
    "teamshift"
  ],
  "7.6": [
    "teamshift"
  ],
  "7.19": [
    "teamshift"
  ],
  "8.2": [
    "teamshift",
    "foreman"
  ],
  "8.5": [
    "teamshift",
    "taub"
  ],
  "8.20": [
    "teamshift",
    "chase"
  ],
  "3.1": [
    "crisis"
  ],
  "3.2": [
    "crisis"
  ],
  "3.3": [
    "crisis"
  ],
  "3.11": [
    "crisis"
  ],
  "7.21": [
    "crisis"
  ],
  "7.23": [
    "crisis"
  ],
  "2.15": [
    "wilson"
  ],
  "3.8": [
    "wilson"
  ],
  "3.21": [
    "wilson"
  ],
  "4.13": [
    "wilson"
  ],
  "7.8": [
    "wilson"
  ],
  "2.3": [
    "cuddy"
  ],
  "5.6": [
    "cuddy"
  ],
  "5.13": [
    "cuddy",
    "cameron"
  ],
  "7.1": [
    "cuddy"
  ],
  "7.11": [
    "cuddy"
  ],
  "7.17": [
    "cuddy"
  ],
  "1.9": [
    "foreman"
  ],
  "5.8": [
    "foreman"
  ],
  "6.12": [
    "foreman"
  ],
  "1.13": [
    "chase"
  ],
  "6.3": [
    "chase"
  ],
  "6.4": [
    "chase"
  ],
  "6.5": [
    "chase"
  ],
  "1.7": [
    "cameron"
  ],
  "1.20": [
    "cameron"
  ],
  "2.7": [
    "cameron"
  ],
  "2.11": [
    "cameron"
  ],
  "5.5": [
    "thirteen"
  ],
  "5.10": [
    "thirteen"
  ],
  "5.14": [
    "thirteen"
  ],
  "6.17": [
    "thirteen"
  ],
  "5.17": [
    "taub"
  ],
  "6.15": [
    "taub"
  ],
  "7.9": [
    "taub"
  ],
  "8.6": [
    "taub"
  ],
  "8.10": [
    "taub"
  ],
  "8.13": [
    "taub"
  ]
};
