// The West Wing — episode tags. Season premieres/finales are auto-tagged by the engine.
// Keys are the season.episode numbers used in episodes.json ('3.0' = Isaac and Ishmael).
window.TAG_DEFS = {
  fanfav:     {label:"Fan favorite", desc:"The ones people rewatch first"},
  heavy:      {label:"Gut-punch", desc:"Bring tissues"},
  speech:     {label:"Big-speech episode", desc:"Two Cathedrals, Let Bartlet Be Bartlet, In Excelsis Deo\u2026"},
  bottle:     {label:"Bottle / real-time", desc:"One night, one building \u2014 or very nearly"},
  experiment: {label:"Format experiment", desc:"The show breaking its own rules"},
  flashback:  {label:"Flashback-heavy"},
  campaign:   {label:"Election / campaign", desc:"Primaries, debates, election nights"},
  xmas:       {label:"Christmas / holiday", desc:"The West Wing does the holidays better than anyone"},
  twoparter:  {label:"Two-parter"},
  lighter:    {label:"Screwball / lighter", desc:"Sorkin banter at full tilt"},
  divisive:   {label:"Divisive", desc:"The ones people argue about"},
  sorkin:     {label:"Sorkin era (S1\u20134)", desc:"Aaron Sorkin & Thomas Schlamme"},
  wells:      {label:"Wells era (S5\u20137)", desc:"John Wells takes over"},
  bartlet:    {label:"Bartlet spotlight"},
  leo:        {label:"Leo spotlight"},
  cj:         {label:"C.J. spotlight"},
  toby:       {label:"Toby spotlight"},
  josh:       {label:"Josh spotlight"},
  sam:        {label:"Sam spotlight"},
  donna:      {label:"Donna spotlight"},
  charlie:    {label:"Charlie spotlight"},
  will:       {label:"Will spotlight"},
  santos:     {label:"Santos spotlight"},
  vinick:     {label:"Vinick spotlight"},
  abbey:      {label:"Abbey spotlight"},
  zoey:       {label:"Zoey spotlight"},
  kate:       {label:"Kate Harper spotlight"},
  annabeth:   {label:"Annabeth spotlight"},
};
window.EP_TAGS = {
  "1.1":   ["fanfav","bartlet","leo","josh","sorkin"],
  "1.2":   ["bartlet","charlie","heavy","sorkin"],
  "1.3":   ["fanfav","speech","bartlet","charlie","sorkin"],
  "1.4":   ["josh","leo","heavy","sorkin"],
  "1.5":   ["fanfav","bartlet","josh","lighter","sorkin"],
  "1.6":   ["fanfav","toby","josh","charlie","sorkin"],
  "1.7":   ["cj","josh","donna","sorkin"],
  "1.8":   ["bartlet","leo","josh","sorkin"],
  "1.9":   ["fanfav","bartlet","sam","toby","sorkin"],
  "1.10":  ["fanfav","heavy","xmas","toby","speech","sorkin"],
  "1.11":  ["leo","josh","cj","sorkin"],
  "1.12":  ["bartlet","abbey","leo","sorkin"],
  "1.13":  ["cj","sam","leo","sorkin"],
  "1.14":  ["fanfav","heavy","bartlet","toby","sam","sorkin"],
  "1.15":  ["fanfav","lighter","flashback","josh","sam","cj","sorkin"],
  "1.16":  ["bartlet","josh","donna","sorkin"],
  "1.17":  ["abbey","cj","zoey","sorkin"],
  "1.18":  ["fanfav","lighter","sam","cj","charlie","sorkin"],
  "1.19":  ["fanfav","speech","bartlet","leo","sam","sorkin"],
  "1.20":  ["josh","toby","sam","sorkin"],
  "1.21":  ["josh","donna","sam","toby","sorkin"],
  "1.22":  ["fanfav","heavy","bartlet","josh","sorkin"],

  "2.1":   ["fanfav","flashback","twoparter","heavy","josh","leo","sorkin"],
  "2.2":   ["fanfav","flashback","twoparter","josh","donna","bartlet","sorkin"],
  "2.3":   ["fanfav","speech","campaign","bartlet","josh","sorkin"],
  "2.4":   ["sam","cj","sorkin"],
  "2.5":   ["sam","toby","lighter","sorkin"],
  "2.6":   ["josh","toby","donna","sorkin"],
  "2.7":   ["bartlet","toby","cj","sam","sorkin"],
  "2.8":   ["fanfav","speech","bartlet","cj","sorkin"],
  "2.9":   ["bartlet","cj","sam","toby","sorkin"],
  "2.10":  ["fanfav","heavy","xmas","speech","flashback","josh","leo","sorkin"],
  "2.11":  ["toby","cj","sam","sorkin"],
  "2.12":  ["sam","toby","josh","sorkin"],
  "2.13":  ["bartlet","cj","josh","donna","sorkin"],
  "2.14":  ["bartlet","josh","toby","heavy","sorkin"],
  "2.15":  ["bartlet","abbey","cj","sorkin"],
  "2.16":  ["sam","donna","cj","heavy","sorkin"],
  "2.17":  ["fanfav","experiment","cj","donna","bartlet","sorkin"],
  "2.18":  ["fanfav","bottle","speech","heavy","toby","bartlet","sorkin"],
  "2.19":  ["bartlet","toby","leo","cj","sorkin"],
  "2.20":  ["cj","toby","bartlet","sorkin"],
  "2.21":  ["fanfav","heavy","cj","bartlet","abbey","sorkin"],
  "2.22":  ["fanfav","heavy","speech","flashback","bartlet","leo","sorkin"],

  "3.0":   ["experiment","bottle","divisive","josh","toby","sorkin"],
  "3.1":   ["twoparter","flashback","campaign","bartlet","cj","toby","sorkin"],
  "3.2":   ["twoparter","flashback","campaign","bartlet","toby","leo","sorkin"],
  "3.3":   ["toby","cj","sam","sorkin"],
  "3.4":   ["toby","josh","cj","sorkin"],
  "3.5":   ["toby","leo","cj","heavy","sorkin"],
  "3.6":   ["cj","toby","bartlet","donna","sorkin"],
  "3.7":   ["fanfav","lighter","cj","sam","bartlet","sorkin"],
  "3.8":   ["fanfav","heavy","speech","cj","toby","sorkin"],
  "3.9":   ["fanfav","heavy","xmas","speech","flashback","leo","sorkin"],
  "3.10":  ["leo","bartlet","josh","sorkin"],
  "3.11":  ["sam","flashback","bartlet","sorkin"],
  "3.12":  ["bartlet","toby","josh","donna","sorkin"],
  "3.13":  ["fanfav","bartlet","toby","sorkin"],
  "3.14":  ["fanfav","speech","bartlet","sam","toby","charlie","josh","donna","sorkin"],
  "3.15":  ["abbey","cj","donna","lighter","sorkin"],
  "3.16":  ["cj","toby","josh","donna","lighter","sorkin"],
  "3.17":  ["bartlet","josh","toby","sorkin"],
  "3.18":  ["cj","bartlet","donna","heavy","sorkin"],
  "3.19":  ["cj","sam","toby","campaign","sorkin"],
  "3.20":  ["leo","bartlet","josh","campaign","heavy","sorkin"],
  "3.21":  ["fanfav","heavy","campaign","bartlet","cj","leo","sorkin"],

  "4.1":   ["fanfav","twoparter","campaign","josh","toby","donna","sorkin"],
  "4.2":   ["fanfav","twoparter","campaign","speech","josh","toby","bartlet","sorkin"],
  "4.3":   ["campaign","josh","sam","toby","sorkin"],
  "4.4":   ["campaign","bartlet","toby","sam","sorkin"],
  "4.5":   ["flashback","campaign","bartlet","toby","cj","sorkin"],
  "4.6":   ["fanfav","campaign","speech","bartlet","toby","sam","sorkin"],
  "4.7":   ["campaign","donna","sam","josh","sorkin"],
  "4.8":   ["campaign","josh","sam","cj","sorkin"],
  "4.9":   ["bartlet","josh","leo","sorkin"],
  "4.10":  ["donna","josh","will","toby","sorkin"],
  "4.11":  ["fanfav","xmas","heavy","flashback","toby","zoey","sorkin"],
  "4.12":  ["leo","josh","toby","sorkin"],
  "4.13":  ["heavy","bottle","experiment","divisive","cj","sorkin"],
  "4.14":  ["twoparter","bartlet","will","toby","charlie","sorkin"],
  "4.15":  ["fanfav","twoparter","speech","bartlet","will","toby","sorkin"],
  "4.16":  ["sam","bartlet","toby","will","sorkin"],
  "4.17":  ["sam","josh","donna","will","sorkin"],
  "4.18":  ["abbey","josh","donna","cj","sorkin"],
  "4.19":  ["bottle","bartlet","toby","cj","sorkin"],
  "4.20":  ["fanfav","bottle","experiment","cj","josh","charlie","donna","sorkin"],
  "4.21":  ["fanfav","heavy","bartlet","cj","sorkin"],
  "4.22":  ["fanfav","heavy","zoey","sam","josh","charlie","sorkin"],
  "4.23":  ["fanfav","heavy","speech","bartlet","leo","sorkin"],

  "5.1":   ["fanfav","heavy","bartlet","leo","zoey","wells"],
  "5.2":   ["heavy","leo","josh","bartlet","wells"],
  "5.3":   ["bartlet","josh","zoey","wells"],
  "5.4":   ["bartlet","will","toby","josh","heavy","wells"],
  "5.5":   ["josh","will","toby","donna","wells"],
  "5.6":   ["bartlet","josh","leo","cj","wells"],
  "5.7":   ["leo","josh","toby","bartlet","wells"],
  "5.8":   ["fanfav","speech","bartlet","josh","leo","wells"],
  "5.9":   ["xmas","bartlet","toby","cj","wells"],
  "5.10":  ["bartlet","leo","cj","charlie","wells"],
  "5.11":  ["toby","charlie","bartlet","josh","wells"],
  "5.12":  ["toby","cj","bartlet","wells"],
  "5.13":  ["bartlet","josh","toby","leo","wells"],
  "5.14":  ["leo","bartlet","toby","flashback","wells"],
  "5.15":  ["cj","josh","toby","heavy","wells"],
  "5.16":  ["bartlet","cj","josh","toby","lighter","wells"],
  "5.17":  ["fanfav","toby","josh","cj","bartlet","wells"],
  "5.18":  ["experiment","divisive","cj","wells"],
  "5.19":  ["donna","josh","toby","cj","wells"],
  "5.20":  ["bottle","bartlet","abbey","cj","josh","donna","wells"],
  "5.21":  ["fanfav","heavy","flashback","donna","bartlet","wells"],
  "5.22":  ["heavy","bartlet","josh","donna","leo","wells"],

  "6.1":   ["heavy","bartlet","leo","donna","wells"],
  "6.2":   ["fanfav","heavy","leo","bartlet","wells"],
  "6.3":   ["cj","josh","toby","bartlet","wells"],
  "6.4":   ["cj","josh","will","annabeth","wells"],
  "6.5":   ["josh","annabeth","toby","cj","wells"],
  "6.6":   ["heavy","bartlet","cj","kate","wells"],
  "6.7":   ["bartlet","cj","toby","charlie","wells"],
  "6.8":   ["heavy","bartlet","josh","cj","wells"],
  "6.9":   ["heavy","bartlet","josh","leo","cj","wells"],
  "6.10":  ["cj","santos","josh","charlie","wells"],
  "6.11":  ["fanfav","campaign","josh","santos","donna","will","wells"],
  "6.12":  ["cj","leo","toby","kate","wells"],
  "6.13":  ["fanfav","campaign","josh","santos","vinick","donna","wells"],
  "6.14":  ["cj","kate","abbey","wells"],
  "6.15":  ["campaign","josh","santos","donna","will","wells"],
  "6.16":  ["heavy","toby","josh","will","wells"],
  "6.17":  ["fanfav","lighter","cj","josh","santos","charlie","wells"],
  "6.18":  ["campaign","santos","josh","donna","wells"],
  "6.19":  ["flashback","bartlet","leo","cj","wells"],
  "6.20":  ["fanfav","campaign","speech","vinick","bartlet","wells"],
  "6.21":  ["campaign","leo","santos","bartlet","wells"],
  "6.22":  ["fanfav","campaign","leo","santos","josh","wells"],

  "7.1":   ["campaign","santos","leo","josh","cj","wells"],
  "7.2":   ["campaign","santos","vinick","josh","cj","wells"],
  "7.3":   ["campaign","santos","vinick","josh","wells"],
  "7.4":   ["santos","vinick","cj","bartlet","wells"],
  "7.5":   ["heavy","toby","josh","cj","kate","wells"],
  "7.6":   ["campaign","santos","vinick","donna","wells"],
  "7.7":   ["fanfav","experiment","bottle","campaign","santos","vinick","wells"],
  "7.8":   ["campaign","heavy","santos","josh","wells"],
  "7.9":   ["bartlet","abbey","lighter","josh","santos","wells"],
  "7.10":  ["campaign","santos","donna","josh","wells"],
  "7.11":  ["cj","donna","toby","wells"],
  "7.12":  ["bartlet","kate","will","josh","wells"],
  "7.13":  ["fanfav","campaign","vinick","josh","donna","santos","wells"],
  "7.14":  ["campaign","santos","vinick","josh","wells"],
  "7.15":  ["campaign","santos","toby","josh","donna","wells"],
  "7.16":  ["twoparter","campaign","heavy","cj","annabeth","santos","wells"],
  "7.17":  ["fanfav","twoparter","heavy","campaign","leo","santos","josh","wells"],
  "7.18":  ["fanfav","heavy","leo","cj","josh","toby","wells"],
  "7.19":  ["fanfav","bartlet","santos","josh","sam","toby","wells"],
  "7.20":  ["fanfav","vinick","santos","heavy","wells"],
  "7.21":  ["fanfav","heavy","cj","will","wells"],
  "7.22":  ["fanfav","heavy","flashback","bartlet","cj","charlie","santos","wells"],
};
