// Game of Thrones (HBO, 2011–19) — chart data on an EPISODE axis: columns are the 73 episodes in order.
// 1–10 = S1, 11–20 = S2, 21–30 = S3, 31–40 = S4, 41–50 = S5 (the book era),
// 51–60 = S6, 61–67 = S7 (7 eps), 68–73 = S8 (6 eps) (after the books).
// Absolute index helpers: S1eN = N | S2eN = 10+N | S3eN = 20+N | S4eN = 30+N | S5eN = 40+N
//                         S6eN = 50+N | S7eN = 60+N | S8eN = 67+N
// Each entry: [label, startEp, endEp, bg, fg?]
window.CHART_AXIS = "episode";
const STARK="#6b7780", LSTARK="#c9d1d6", ICE="#9cc4d9", DICE="#3e6f8a", LION="#a3212a", GOLD="#d9b44a",
      LGOLD="#efdca0", DRAGON="#1c1c1c", FIRE="#c4461c", EMBER="#e98a4a", STAG="#e0c341",
      KRAKEN="#2f3b33", TYRELL="#4f8a3f", LGREEN="#b9d7a8", SUN="#e07b1f", BOLTON="#b56b7b",
      FREY="#7c8aa0", WATCH="#2b2b2b", BLOOD="#6d1a17", PURPLE="#6a4a86", LPURP="#cdbde0",
      SAND="#d8c49a", BROWN="#7a5a3c", GRAY="#8a8a8a", LGRAY="#dcdcdc", DGRAY="#3a3d40",
      WHITE="#fff", BLACK="#000";

window.ERA_CATS = [
  ["eras","Book era vs after the books"],
  ["crown","The Iron Throne & its claimants"],
  ["starks","House Stark"],
  ["houses","The great houses"],
  ["places","Locations"],
  ["war","Wars, battles & the dead"],
  ["deaths","Major deaths"],
];

window.ERAS = {
  eras: [
    [["The book era — adapting A Song of Ice and Fire (S1–S5)", 1, 50, STARK, WHITE],
     ["After the books ran out (S6–S8)", 51, 73, DICE, WHITE]],
    [["S1 · A Game of Thrones", 1, 10, LSTARK, BLACK],
     ["S2 · A Clash of Kings", 11, 20, LGOLD, BLACK],
     ["S3 · A Storm of Swords, first half", 21, 30, LSTARK, BLACK],
     ["S4 · A Storm of Swords, second half", 31, 40, LGOLD, BLACK],
     ["S5 · A Feast for Crows & A Dance with Dragons", 41, 50, LSTARK, BLACK],
     ["S6 · past the books", 51, 60, ICE, BLACK],
     ["S7 · 7 episodes", 61, 67, LGOLD, BLACK],
     ["S8 · 6 episodes", 68, 73, ICE, BLACK]],
    [["2011", 1, 10, LGRAY, BLACK], ["2012", 11, 20, GRAY, WHITE], ["2013", 21, 30, LGRAY, BLACK],
     ["2014", 31, 40, GRAY, WHITE], ["2015", 41, 50, LGRAY, BLACK], ["2016", 51, 60, GRAY, WHITE],
     ["2017", 61, 67, LGRAY, BLACK], ["2019", 68, 73, GRAY, WHITE]],
    [["Created for HBO by David Benioff & D. B. Weiss, showrunners for all eight seasons", 1, 73, DGRAY, WHITE]],
    [["Written by George R. R. Martin", 8, 8, GOLD, BLACK], ["GRRM", 19, 19, GOLD, BLACK],
     ["GRRM", 27, 27, GOLD, BLACK], ["GRRM", 32, 32, GOLD, BLACK]],
    [["Dir. Neil Marshall", 19, 19, FIRE, WHITE], ["Marshall", 39, 39, FIRE, WHITE],
     ["Dir. Miguel Sapochnik", 48, 48, DICE, WHITE], ["Sapochnik", 59, 59, DICE, WHITE],
     ["Sapochnik", 70, 70, DICE, WHITE], ["Sapochnik", 72, 72, DICE, WHITE]],
  ],
  crown: [
    [["Robert I", 1, 7, STAG, BLACK], ["Joffrey I", 8, 32, LION, WHITE], ["Tommen I", 33, 59, GOLD, BLACK],
     ["Tommen falls; Cersei crowned (6×10)", 60, 60, BLOOD, WHITE], ["Cersei I", 61, 71, LION, WHITE],
     ["Daenerys takes the city (8×05)", 72, 72, FIRE, WHITE], ["Bran the Broken (8×06)", 73, 73, STARK, WHITE]],
    [["Ned Stark, Hand of the King", 1, 9, STARK, WHITE], ["Tyrion, acting Hand (named 1×10)", 10, 19, GOLD, BLACK],
     ["Tywin, Hand of the King (from 2×10)", 20, 40, LION, WHITE], ["Qyburn, Hand of the Queen (from 6×10)", 60, 72, PURPLE, WHITE],
     ["Tyrion, Hand to Bran", 73, 73, GOLD, BLACK]],
    [["Robb, King in the North (1×10–3×09)", 10, 29, STARK, WHITE], ["Jon, King in the North (6×10–7×06)", 60, 66, STARK, WHITE],
     ["Sansa, Queen in the North", 73, 73, LSTARK, BLACK]],
    [["Renly & Stannis both claim", 11, 15, STAG, BLACK], ["Stannis, the one true king", 16, 50, STAG, BLACK]],
    [["Viserys, the Beggar King", 1, 6, DRAGON, WHITE], ["Daenerys Stormborn's claim", 7, 72, FIRE, WHITE]],
    [["Tyrion, Hand of the Queen for Daenerys (from 6×10)", 60, 72, EMBER, BLACK]],
  ],
  starks: [
    [["Ned, Lord of Winterfell", 1, 9, STARK, WHITE], ["Robb, King in the North", 10, 29, DGRAY, WHITE],
     ["No Stark rules the North", 30, 58, LGRAY, BLACK], ["Starks hold Winterfell again (from 6×09)", 59, 73, STARK, WHITE]],
    [["Jon joins the Night's Watch", 1, 10, WATCH, WHITE], ["The Great Ranging", 11, 20, DGRAY, WHITE],
     ["Jon among the free folk", 21, 29, BROWN, WHITE], ["Back at the Wall", 30, 41, WATCH, WHITE],
     ["Lord Commander (from 5×02)", 42, 49, WATCH, WHITE], ["\"For the Watch\" (5×10)", 50, 50, BLOOD, WHITE],
     ["Resurrected (6×02); leaves the Watch", 51, 58, ICE, BLACK], ["Battle of the Bastards; King in the North", 59, 65, STARK, WHITE],
     ["Bends the knee (7×06)", 66, 66, FIRE, WHITE], ["Aegon Targaryen: the truth (from 7×07)", 67, 72, DRAGON, WHITE],
     ["Kills Daenerys; back to the Wall", 73, 73, WATCH, WHITE]],
    [["Sansa at court, then Joffrey's hostage", 1, 32, LSTARK, BLACK], ["With Littlefinger in the Vale", 33, 43, PURPLE, WHITE],
     ["Winterfell: married to Ramsay", 44, 50, BOLTON, WHITE], ["Escapes; finds Jon (6×04)", 51, 58, LSTARK, BLACK],
     ["Lady of Winterfell", 59, 72, STARK, WHITE], ["Queen in the North", 73, 73, DGRAY, WHITE]],
    [["Arya: Needle and Syrio", 1, 8, LSTARK, BLACK], ["On the run: Yoren, Harrenhal, the Brotherhood, the Hound", 9, 40, BROWN, WHITE],
     ["Braavos: the Faceless Men (5×02)", 42, 58, DGRAY, WHITE], ["Arya's list: the Freys (6×10, 7×01)", 60, 61, BLOOD, WHITE],
     ["Home at Winterfell (7×04)", 64, 69, STARK, WHITE], ["Kills the Night King (8×03)", 70, 70, ICE, BLACK],
     ["Rides south for Cersei", 71, 72, BROWN, WHITE], ["Sails west", 73, 73, LSTARK, BLACK]],
    [["Bran falls (1×01); lord in Winterfell", 1, 20, LSTARK, BLACK], ["North with the Reeds", 21, 40, LGREEN, BLACK],
     ["The Three-Eyed Raven's cave", 52, 55, TYRELL, WHITE], ["With Benjen, then home", 56, 62, LGREEN, BLACK],
     ["The Three-Eyed Raven at Winterfell (from 7×03)", 63, 72, ICE, BLACK], ["Bran the Broken", 73, 73, STARK, WHITE]],
  ],
  houses: [
    [["Tywin's house at its height", 1, 39, LION, WHITE], ["Tyrion kills Tywin (4×10)", 40, 40, BLOOD, WHITE],
     ["Cersei vs the Faith", 41, 59, GOLD, BLACK], ["Wildfire at the Sept (6×10)", 60, 60, BLOOD, WHITE],
     ["Queen Cersei's Lannisters", 61, 71, LION, WHITE], ["The Red Keep falls (8×05)", 72, 72, BLOOD, WHITE]],
    [["Jaime, Kingsguard", 1, 8, GOLD, BLACK], ["Robb's prisoner", 9, 17, GRAY, WHITE],
     ["Jaime & Brienne on the road", 18, 30, LGOLD, BLACK], ["Back at court", 31, 43, GOLD, BLACK],
     ["Jaime & Bronn in Dorne", 44, 50, SUN, BLACK], ["Riverrun & Cersei's wars", 51, 66, LION, WHITE],
     ["Rides north (7×07)", 67, 71, LSTARK, BLACK], ["Back to Cersei", 72, 72, BLOOD, WHITE]],
    [["Tyrion goes north; Catelyn's prisoner", 1, 6, LGOLD, BLACK], ["At war, then acting Hand", 7, 20, GOLD, BLACK],
     ["Under Tywin; on trial", 21, 39, LION, WHITE], ["Kills Tywin, flees", 40, 40, BLOOD, WHITE],
     ["Tyrion & Varys to Essos", 41, 46, SAND, BLACK], ["Tyrion with Daenerys (meets her 5×07)", 47, 72, FIRE, WHITE],
     ["Hand to Bran", 73, 73, GOLD, BLACK]],
    [["Viserys sells Dany to Drogo", 1, 6, DRAGON, WHITE], ["Khaleesi; dragons hatch (1×10)", 7, 10, FIRE, WHITE],
     ["Red Waste & Qarth", 11, 20, SAND, BLACK], ["Astapor & Yunkai: the Unsullied", 21, 30, EMBER, BLACK],
     ["Meereen, queen of Slaver's Bay", 31, 49, FIRE, WHITE], ["Drogon, the Dothraki, Vaes Dothrak", 50, 58, BROWN, WHITE],
     ["Back to Meereen; the fleet sails", 59, 60, EMBER, BLACK], ["Dragonstone & the war in Westeros", 61, 71, DRAGON, WHITE],
     ["Queen of ashes", 72, 72, FIRE, WHITE], ["Killed by Jon", 73, 73, BLOOD, WHITE]],
    [["Theon, Stark ward", 1, 11, LSTARK, BLACK], ["Pyke; Theon turns", 12, 15, KRAKEN, WHITE],
     ["Theon holds Winterfell", 16, 20, KRAKEN, WHITE], ["Reek: Ramsay's captive", 21, 50, BOLTON, WHITE],
     ["Balon dies; Euron's Kingsmoot; Yara & Theon to Daenerys", 51, 60, KRAKEN, WHITE],
     ["Euron's fleet serves Cersei", 61, 72, DGRAY, WHITE]],
    [["Roose Bolton, Robb's bannerman", 14, 28, BOLTON, WHITE], ["The Red Wedding", 29, 29, BLOOD, WHITE],
     ["The Boltons hold the North", 30, 58, BOLTON, WHITE], ["Ramsay falls (6×09)", 59, 59, BLOOD, WHITE]],
    [["Renly & the Tyrells", 13, 15, TYRELL, WHITE], ["Tyrells save the Blackwater", 19, 19, TYRELL, WHITE],
     ["Margaery & Olenna at court", 21, 59, LGREEN, BLACK], ["Wiped out at the Sept", 60, 60, BLOOD, WHITE],
     ["Olenna sides with Daenerys", 61, 63, TYRELL, WHITE]],
    [["Oberyn in King's Landing", 31, 38, SUN, BLACK], ["Dorne: Doran, Ellaria & the Sand Snakes", 42, 51, SUN, BLACK],
     ["Ellaria's Dorne sides with Daenerys", 61, 63, EMBER, BLACK]],
    [["Walder's bargain (1×09)", 9, 9, FREY, WHITE], ["The Red Wedding (3×09)", 29, 29, BLOOD, WHITE],
     ["Arya kills Walder (6×10)", 60, 60, FREY, WHITE], ["Arya poisons House Frey (7×01)", 61, 61, BLOOD, WHITE]],
  ],
  places: [
    [["King's Landing: Robert's court", 1, 7, STAG, BLACK], ["Ned's fall", 8, 9, STARK, WHITE],
     ["Joffrey's court", 10, 18, LION, WHITE], ["Battle of the Blackwater", 19, 19, FIRE, WHITE],
     ["Lannister–Tyrell court", 20, 31, GOLD, BLACK], ["The Purple Wedding", 32, 32, PURPLE, WHITE],
     ["Tyrion's trial; the Mountain & the Viper", 33, 40, LION, WHITE], ["The Faith Militant; Cersei's walk (5×10)", 41, 50, LPURP, BLACK],
     ["The Faith rules; the Sept burns (6×10)", 51, 60, LGREEN, BLACK], ["Cersei's capital", 61, 71, LION, WHITE],
     ["The Bells", 72, 72, FIRE, WHITE], ["The Dragonpit council", 73, 73, GOLD, BLACK]],
    [["The Wall: Castle Black", 3, 10, WATCH, WHITE], ["The Wall besieged", 31, 39, WATCH, WHITE],
     ["Stannis at Castle Black", 40, 50, STAG, BLACK], ["Jon rises; leaves the Watch", 51, 53, ICE, BLACK],
     ["Eastwatch", 65, 65, WATCH, WHITE], ["The Wall falls (7×07)", 67, 67, DICE, WHITE],
     ["Jon sent back to the Wall", 73, 73, WATCH, WHITE]],
    [["Beyond the Wall: Craster's & the Fist", 11, 20, DGRAY, WHITE], ["With the free folk", 21, 29, BROWN, WHITE],
     ["Craster's Keep raid", 34, 35, DGRAY, WHITE], ["Weirwood cave", 40, 40, TYRELL, WHITE],
     ["Hardhome", 48, 48, DICE, WHITE], ["The Three-Eyed Raven's cave", 52, 55, TYRELL, WHITE],
     ["The wight hunt", 66, 66, ICE, BLACK]],
    [["Winterfell under the Starks", 1, 15, STARK, WHITE], ["Theon holds Winterfell", 16, 20, KRAKEN, WHITE],
     ["Burned, then the Boltons' seat", 21, 58, BOLTON, WHITE], ["Battle of the Bastards", 59, 59, BLOOD, WHITE],
     ["Stark Winterfell, awaiting the dead", 60, 69, STARK, WHITE], ["The Long Night", 70, 70, DICE, WHITE],
     ["After the Long Night", 71, 71, LSTARK, BLACK]],
    [["Riverlands: the war camps & Riverrun", 8, 29, FREY, WHITE], ["Arya & the Hound on the road", 30, 40, BROWN, WHITE],
     ["Siege of Riverrun", 57, 58, LION, WHITE], ["The Twins: Arya's revenge", 60, 61, BLOOD, WHITE]],
    [["Essos: Pentos & the Dothraki Sea", 1, 10, SAND, BLACK], ["Red Waste & Qarth", 11, 20, SAND, BLACK],
     ["Slaver's Bay: Astapor, Yunkai, Meereen", 21, 49, EMBER, BLACK], ["Vaes Dothrak", 50, 58, BROWN, WHITE],
     ["Meereen", 59, 60, EMBER, BLACK]],
    [["Braavos: the Iron Bank (4×06)", 36, 36, DGRAY, WHITE], ["Arya at the House of Black and White", 42, 58, DGRAY, WHITE]],
    [["Dragonstone: Stannis & Melisandre", 11, 39, STAG, BLACK], ["Dragonstone: Daenerys", 61, 67, DRAGON, WHITE]],
    [["Dorne", 42, 51, SUN, BLACK], ["Oldtown: Sam at the Citadel", 60, 65, LGRAY, BLACK]],
  ],
  war: [
    [["War of the Five Kings", 8, 50, LION, WHITE], ["Starks vs Boltons; Daenerys vs Cersei", 51, 66, FIRE, WHITE],
     ["The Great War: the dead march", 67, 70, DICE, WHITE], ["The last war for the throne", 71, 73, BLOOD, WHITE]],
    [["Blackwater", 19, 19, FIRE, WHITE], ["Castle Black", 39, 39, WATCH, WHITE], ["Hardhome", 48, 48, DICE, WHITE],
     ["Daznak's Pit", 49, 49, EMBER, BLACK], ["Battle of the Bastards & the Masters' fleet", 59, 59, BLOOD, WHITE],
     ["Euron's ambush", 62, 62, KRAKEN, WHITE], ["Casterly Rock & Highgarden", 63, 63, LION, WHITE],
     ["The Loot Train", 64, 64, FIRE, WHITE], ["Beyond the Wall", 66, 66, ICE, BLACK],
     ["The Long Night", 70, 70, DICE, WHITE], ["The Bells", 72, 72, FIRE, WHITE]],
    [["The Others return", 1, 1, ICE, BLACK], ["The army of the dead (2×10)", 20, 20, ICE, BLACK],
     ["Sam kills a White Walker", 28, 28, ICE, BLACK], ["The Night King", 34, 34, DICE, WHITE],
     ["Hardhome", 48, 48, DICE, WHITE], ["The Children made them", 55, 55, TYRELL, WHITE],
     ["Viserion raised", 66, 66, DICE, WHITE], ["The Wall falls", 67, 67, DICE, WHITE],
     ["The Night King dies", 70, 70, ICE, BLACK]],
  ],
  deaths: [
    [["Ned", 9, 9, STARK, WHITE], ["Robb, Catelyn & Talisa", 29, 29, BLOOD, WHITE], ["Hodor", 55, 55, STARK, WHITE],
     ["Rickon", 59, 59, STARK, WHITE], ["Theon, Jorah, Lyanna Mormont, Beric, Edd, Melisandre", 70, 70, DICE, WHITE]],
    [["Robert", 7, 7, STAG, BLACK], ["Joffrey", 32, 32, LION, WHITE], ["Tywin & Shae", 40, 40, LION, WHITE],
     ["Myrcella", 50, 50, GOLD, BLACK], ["Tommen", 60, 60, GOLD, BLACK], ["Cersei & Jaime", 72, 72, LION, WHITE]],
    [["Viserys", 6, 6, DRAGON, WHITE], ["Drogo", 10, 10, BROWN, WHITE], ["Barristan", 44, 44, LGRAY, BLACK],
     ["Viserion", 66, 66, DICE, WHITE], ["Rhaegal & Missandei", 71, 71, FIRE, WHITE], ["Daenerys", 73, 73, DRAGON, WHITE]],
    [["Renly", 15, 15, STAG, BLACK], ["Lysa Arryn", 37, 37, LSTARK, BLACK], ["Oberyn", 38, 38, SUN, BLACK],
     ["Shireen", 49, 49, STAG, BLACK], ["Stannis", 50, 50, STAG, BLACK], ["Roose Bolton & Balon Greyjoy", 52, 52, BOLTON, WHITE],
     ["Ramsay", 59, 59, BOLTON, WHITE], ["Margaery, Loras, the High Sparrow, Kevan", 60, 60, TYRELL, WHITE],
     ["Olenna", 63, 63, TYRELL, WHITE], ["Randyll & Dickon Tarly", 65, 65, FIRE, WHITE], ["Littlefinger", 67, 67, PURPLE, WHITE],
     ["Varys, Euron, the Cleganes, Qyburn", 72, 72, BLOOD, WHITE]],
    [["Jeor Mormont", 24, 24, WATCH, WHITE], ["Ygritte, Grenn, Pyp", 39, 39, WATCH, WHITE], ["Mance Rayder", 41, 41, BROWN, WHITE],
     ["Maester Aemon", 47, 47, WATCH, WHITE], ["Jon Snow (for now)", 50, 50, BLOOD, WHITE], ["Thorne & Olly hanged", 53, 53, WATCH, WHITE],
     ["Walder Frey", 60, 60, FREY, WHITE], ["House Frey", 61, 61, FREY, WHITE], ["Benjen", 66, 66, STARK, WHITE]],
  ],
};

window.SEASON_META = {
  1: { years: "2011", showrunner: "David Benioff & D. B. Weiss" },
  2: { years: "2012", showrunner: "David Benioff & D. B. Weiss" },
  3: { years: "2013", showrunner: "David Benioff & D. B. Weiss" },
  4: { years: "2014", showrunner: "David Benioff & D. B. Weiss" },
  5: { years: "2015", showrunner: "David Benioff & D. B. Weiss" },
  6: { years: "2016", showrunner: "David Benioff & D. B. Weiss" },
  7: { years: "2017", showrunner: "David Benioff & D. B. Weiss" },
  8: { years: "2019", showrunner: "David Benioff & D. B. Weiss" },
};
