// Game of Thrones — episode tags. Keys are TVmaze season.episode, matching episodes.json.
// Season premieres and finales are auto-tagged by the engine and are not listed here.
window.TAG_DEFS = {
  fanfav:  {label:"Fan favorite", desc:"The ones people rewatch and quote"},
  heavy:   {label:"Gut-punch", desc:"The ones that hurt"},
  death:   {label:"A major death", desc:"Someone you know doesn't make it out"},
  battle:  {label:"Big battle", desc:"A set-piece battle takes over the episode"},
  wedding: {label:"A wedding", desc:"In Westeros, never a good sign"},
  walkers: {label:"The White Walkers", desc:"The Others, the wights and the Night King"},
  dragons: {label:"Dragons", desc:"Hatching, burning, flying"},
  reveal:  {label:"Big reveal", desc:"Something you can't un-know"},

  tyrion:{label:"Tyrion spotlight"}, jon:{label:"Jon spotlight"}, dany:{label:"Daenerys spotlight"},
  arya:{label:"Arya spotlight"}, sansa:{label:"Sansa spotlight"}, cersei:{label:"Cersei spotlight"},
  jaime:{label:"Jaime spotlight"}, bran:{label:"Bran spotlight"}, theon:{label:"Theon spotlight"},
  brienne:{label:"Brienne spotlight"},
};

window.EP_TAGS = {
  // S1 — A Game of Thrones
  "1.1":["walkers","wedding","reveal","bran","jaime","dany"],
  "1.2":["heavy","arya","sansa"],
  "1.3":["jon","arya","tyrion"],
  "1.4":["tyrion","jon"],
  "1.5":["tyrion","jaime"],
  "1.6":["fanfav","death","dany","tyrion"],
  "1.7":["fanfav","death","cersei","jon"],
  "1.8":["walkers","arya","jon"],
  "1.9":["fanfav","heavy","death","arya","sansa","dany"],
  "1.10":["dragons","dany","jon","arya"],
  // S2 — A Clash of Kings
  "2.1":["heavy","tyrion","cersei","dany"],
  "2.2":["theon","jon","arya","tyrion"],
  "2.3":["theon","tyrion","arya","brienne"],
  "2.4":["arya","dany","sansa"],
  "2.5":["death","arya","brienne","dany"],
  "2.6":["fanfav","theon","jon","dany"],
  "2.7":["theon","jaime","sansa"],
  "2.8":["jaime","theon","tyrion"],
  "2.9":["fanfav","battle","tyrion","cersei","sansa"],
  "2.10":["walkers","dany","tyrion","arya"],
  // S3 — A Storm of Swords, part one
  "3.1":["dany","jon","tyrion"],
  "3.2":["jaime","brienne","bran","sansa"],
  "3.3":["heavy","jaime","brienne","theon","dany"],
  "3.4":["fanfav","dragons","death","dany","jaime"],
  "3.5":["fanfav","jaime","brienne","arya"],
  "3.6":["jon","sansa"],
  "3.7":["jaime","brienne","dany"],
  "3.8":["wedding","walkers","tyrion","sansa","dany"],
  "3.9":["fanfav","heavy","death","wedding","arya","bran","jon"],
  "3.10":["dany","theon","arya"],
  // S4 — A Storm of Swords, part two
  "4.1":["arya","jaime","dany"],
  "4.2":["fanfav","death","wedding","tyrion","theon"],
  "4.3":["dany","jaime","cersei","tyrion"],
  "4.4":["walkers","jon","jaime","brienne"],
  "4.5":["jon","bran","sansa","cersei"],
  "4.6":["fanfav","tyrion"],
  "4.7":["death","sansa","arya","tyrion"],
  "4.8":["fanfav","heavy","death","tyrion","sansa"],
  "4.9":["fanfav","battle","death","jon"],
  "4.10":["heavy","death","tyrion","arya","bran","dany"],
  // S5 — A Feast for Crows / A Dance with Dragons
  "5.1":["death","jon","dany","tyrion"],
  "5.2":["arya","jon","dany"],
  "5.3":["wedding","arya","cersei","jon"],
  "5.4":["death","dany","cersei"],
  "5.5":["jon","tyrion","dany"],
  "5.6":["wedding","heavy","sansa","arya","cersei"],
  "5.7":["death","dany","tyrion","cersei","jon"],
  "5.8":["fanfav","battle","walkers","jon","dany","tyrion"],
  "5.9":["heavy","death","dragons","dany","arya"],
  "5.10":["heavy","death","cersei","jon","arya"],
  // S6 — past the books
  "6.1":["death","jon","cersei","dany"],
  "6.2":["death","jon","bran","theon"],
  "6.3":["death","bran","jon","arya"],
  "6.4":["fanfav","sansa","jon","dany"],
  "6.5":["fanfav","heavy","death","walkers","bran","arya"],
  "6.6":["bran","arya","cersei"],
  "6.7":["arya","jon","sansa"],
  "6.8":["death","arya","jaime","brienne"],
  "6.9":["fanfav","battle","death","dragons","jon","sansa","dany"],
  "6.10":["fanfav","heavy","death","reveal","cersei","arya","jon"],
  // S7
  "7.1":["death","arya","dany"],
  "7.2":["battle","death","dany","arya"],
  "7.3":["death","jon","dany","jaime","cersei"],
  "7.4":["fanfav","battle","dragons","dany","jaime","arya","bran"],
  "7.5":["death","dragons","jon","dany"],
  "7.6":["battle","walkers","dragons","death","jon","dany"],
  "7.7":["death","reveal","walkers","jon","dany","cersei","sansa","arya"],
  // S8
  "8.1":["reveal","jon","dany","arya"],
  "8.2":["fanfav","brienne","jaime","arya"],
  "8.3":["battle","walkers","death","heavy","arya"],
  "8.4":["death","heavy","dragons","dany"],
  "8.5":["battle","death","heavy","dragons","dany","cersei","jaime","arya"],
  "8.6":["death","dany","jon","tyrion"],
};
