// Star Trek: Deep Space Nine — episode tags. Season premieres and finales are auto-tagged by the engine,
// so they aren't listed here. Keys are TVmaze season.episode numbers as used in episodes.json (TVmaze splits
// "Emissary", "The Way of the Warrior" and "What You Leave Behind" in two; see eras.js).
// Every episode carries exactly one of "dominion" (part of the Dominion War serial) or "standalone".
window.TAG_DEFS = {
  dominion:    {label:"Dominion War arc", desc:"A chapter of the serialized Dominion story, from the first Jem'Hadar to the surrender"},
  standalone:  {label:"Standalone", desc:"Outside the Dominion War serial; watchable on its own"},
  finalchapter:{label:"The final chapter", desc:"The closing ten, 7×17–7×26, one continuous story"},
  bajor:       {label:"Bajor & the Prophets", desc:"The Emissary, the Kai, the Prophets and the Pah-wraiths"},
  occupation:  {label:"The Occupation", desc:"Bajor's fifty years under Cardassia, remembered"},
  klingon:     {label:"Klingons", desc:"Gowron, Martok, Kor and the Klingon war"},
  maquis:      {label:"The Maquis", desc:"Federation colonists at war with Cardassia, and Eddington"},
  section31:   {label:"Section 31", desc:"Starfleet's secret service"},
  mirror:      {label:"Mirror Universe", desc:"Intendant Kira, Smiley O'Brien and the Alliance"},
  ferengi:     {label:"Ferengi episode", desc:"Quark, Rom, Nog, Zek and Moogie: Ferenginar's comedy of manners"},
  fanfav:      {label:"Fan favorite", desc:"The hours people rewatch first"},
  heavy:       {label:"Gut-punch", desc:"The ones that hurt"},
  milestone:   {label:"Milestone", desc:"Arrivals, departures and the turns the series hinges on"},
  twoparter:   {label:"Multi-parter", desc:"Part of a two- or three-part story (including the features TVmaze splits in two)"},
  serial:      {label:"Season 6 opening six", desc:"The occupation of the station and Operation Return, 6×01–6×06"},
  experiment:  {label:"Format experiment", desc:"Time travel, holosuites, the 1950s and the show bending its own shape"},
  crossover:   {label:"Trek crossover", desc:"Faces from TNG and the original series"},
  sisko:       {label:"Sisko spotlight"},
  kira:        {label:"Kira spotlight"},
  odo:         {label:"Odo spotlight"},
  quark:       {label:"Quark spotlight"},
  bashir:      {label:"Bashir spotlight"},
  obrien:      {label:"O'Brien spotlight"},
  jadzia:      {label:"Jadzia Dax spotlight"},
  ezri:        {label:"Ezri Dax spotlight"},
  worf:        {label:"Worf spotlight"},
  jake:        {label:"Jake spotlight"},
  garak:       {label:"Garak spotlight"},
  dukat:       {label:"Dukat spotlight"},
};

window.EP_TAGS = {
  // season 1
  "1.1":   ["standalone","bajor","twoparter","milestone","fanfav","sisko"],
  "1.2":   ["standalone","bajor","twoparter","sisko"],
  "1.3":   ["standalone","kira","garak","occupation","crossover"],
  "1.4":   ["standalone","odo"],
  "1.5":   ["standalone","kira","obrien"],
  "1.6":   ["standalone","obrien"],
  "1.7":   ["standalone","crossover"],
  "1.8":   ["standalone","jadzia"],
  "1.9":   ["standalone","bashir"],
  "1.10":  ["standalone","quark"],
  "1.11":  ["standalone","ferengi","quark","jake"],
  "1.12":  ["standalone","odo"],
  "1.13":  ["standalone","bajor","kira"],
  "1.14":  ["standalone","obrien","bashir"],
  "1.15":  ["standalone","kira","jake"],
  "1.16":  ["standalone"],
  "1.17":  ["standalone","odo","crossover"],
  "1.18":  ["standalone"],
  "1.19":  ["standalone","kira","occupation","fanfav","heavy"],
  "1.20":  ["standalone","bajor"],
  // season 2
  "2.1":   ["standalone","bajor","twoparter","kira"],
  "2.2":   ["standalone","bajor","twoparter","kira"],
  "2.3":   ["standalone","bajor","twoparter","kira"],
  "2.4":   ["standalone","jadzia"],
  "2.5":   ["standalone","garak","occupation"],
  "2.6":   ["standalone","bashir"],
  "2.7":   ["standalone","ferengi","quark","milestone"],
  "2.8":   ["standalone","odo","kira","occupation","fanfav"],
  "2.9":   ["standalone","sisko"],
  "2.10":  ["standalone","kira"],
  "2.11":  ["standalone","quark"],
  "2.12":  ["standalone","odo"],
  "2.13":  ["standalone","bashir","obrien"],
  "2.14":  ["standalone","obrien","experiment"],
  "2.15":  ["standalone","sisko"],
  "2.16":  ["standalone","odo","jake"],
  "2.17":  ["standalone","jadzia"],
  "2.18":  ["standalone","quark","garak"],
  "2.19":  ["standalone","jadzia","klingon","crossover","fanfav"],
  "2.20":  ["standalone","maquis","twoparter","sisko"],
  "2.21":  ["standalone","maquis","twoparter","sisko"],
  "2.22":  ["standalone","garak","bashir","fanfav"],
  "2.23":  ["standalone","mirror","kira","bashir"],
  "2.24":  ["standalone","bajor","kira"],
  "2.25":  ["standalone","obrien","maquis"],
  "2.26":  ["dominion","milestone","sisko","jake"],
  // season 3
  "3.1":   ["dominion","twoparter","milestone","sisko"],
  "3.2":   ["dominion","twoparter","milestone","odo"],
  "3.3":   ["standalone","ferengi","klingon","quark"],
  "3.4":   ["standalone","jadzia"],
  "3.5":   ["standalone","kira","garak"],
  "3.6":   ["standalone","odo"],
  "3.7":   ["standalone","dukat"],
  "3.8":   ["standalone","jadzia"],
  "3.9":   ["standalone","maquis","kira","crossover"],
  "3.10":  ["standalone"],
  "3.11":  ["standalone","twoparter","experiment","sisko","bashir"],
  "3.12":  ["standalone","twoparter","experiment","sisko"],
  "3.13":  ["standalone","bajor","heavy","bashir","kira"],
  "3.14":  ["standalone","odo","kira"],
  "3.15":  ["standalone","bajor","sisko"],
  "3.16":  ["standalone","ferengi","quark"],
  "3.17":  ["standalone","obrien"],
  "3.18":  ["standalone","bashir"],
  "3.19":  ["standalone","mirror","sisko"],
  "3.20":  ["dominion","twoparter","garak","odo","fanfav"],
  "3.21":  ["dominion","twoparter","garak","odo","fanfav"],
  "3.22":  ["standalone","sisko","jake"],
  "3.23":  ["standalone","ferengi","quark"],
  "3.24":  ["standalone","bajor","kira"],
  "3.25":  ["standalone","jadzia"],
  "3.26":  ["dominion","milestone","odo","sisko"],
  // season 4
  "4.1":   ["dominion","twoparter","klingon","milestone","fanfav","worf"],
  "4.2":   ["dominion","twoparter","klingon","milestone","fanfav","worf","garak"],
  "4.3":   ["standalone","jake","sisko","fanfav","heavy","experiment"],
  "4.4":   ["standalone","bashir","worf"],
  "4.5":   ["standalone","kira","dukat"],
  "4.6":   ["standalone","jadzia"],
  "4.7":   ["standalone","sisko"],
  "4.8":   ["standalone","ferengi","quark","fanfav"],
  "4.9":   ["standalone","klingon","worf","jadzia"],
  "4.10":  ["standalone","bashir","garak","experiment","fanfav"],
  "4.11":  ["dominion","twoparter","sisko"],
  "4.12":  ["dominion","twoparter","sisko"],
  "4.13":  ["standalone","odo","kira"],
  "4.14":  ["standalone","klingon","kira","dukat"],
  "4.15":  ["standalone","klingon","worf"],
  "4.16":  ["standalone","ferengi","quark"],
  "4.17":  ["standalone","bajor","sisko"],
  "4.18":  ["standalone","worf","klingon"],
  "4.19":  ["standalone","obrien","heavy","experiment","fanfav"],
  "4.20":  ["standalone","mirror","sisko","jake"],
  "4.21":  ["standalone","jake"],
  "4.22":  ["standalone","maquis","sisko"],
  "4.23":  ["dominion","sisko","worf"],
  "4.24":  ["standalone","bashir","heavy"],
  "4.25":  ["standalone","ferengi","quark","kira"],
  "4.26":  ["dominion","odo","garak"],
  // season 5
  "5.1":   ["dominion","klingon","worf","odo","sisko"],
  "5.2":   ["dominion","sisko","heavy"],
  "5.3":   ["standalone","worf","quark","jadzia","klingon"],
  "5.4":   ["standalone","jake","klingon","heavy"],
  "5.5":   ["standalone","bajor","obrien"],
  "5.6":   ["standalone","experiment","crossover","milestone","fanfav"],
  "5.7":   ["standalone","worf","jadzia"],
  "5.8":   ["standalone","odo","occupation"],
  "5.9":   ["standalone","odo","quark"],
  "5.10":  ["standalone","bajor","sisko"],
  "5.11":  ["standalone","kira","occupation","heavy"],
  "5.12":  ["standalone","odo","kira"],
  "5.13":  ["standalone","maquis","sisko"],
  "5.14":  ["dominion","twoparter","garak","bashir","worf","fanfav"],
  "5.15":  ["dominion","twoparter","garak","bashir","worf","klingon","fanfav","milestone"],
  "5.16":  ["standalone","bashir"],
  "5.17":  ["standalone","odo"],
  "5.18":  ["standalone","quark"],
  "5.19":  ["dominion","kira","heavy"],
  "5.20":  ["standalone","ferengi","quark"],
  "5.21":  ["standalone","klingon","worf"],
  "5.22":  ["standalone","odo","kira","heavy","fanfav"],
  "5.23":  ["standalone","maquis","sisko"],
  "5.24":  ["standalone","obrien","garak"],
  "5.25":  ["standalone","jake","fanfav"],
  "5.26":  ["dominion","milestone","sisko"],
  // season 6
  "6.1":   ["dominion","serial","sisko"],
  "6.2":   ["dominion","serial","sisko","kira","fanfav","heavy"],
  "6.3":   ["dominion","serial","worf","kira","dukat"],
  "6.4":   ["dominion","serial","odo","kira"],
  "6.5":   ["dominion","serial","sisko"],
  "6.6":   ["dominion","serial","sisko","dukat","milestone","fanfav","heavy"],
  "6.7":   ["standalone","worf","jadzia","klingon","milestone"],
  "6.8":   ["standalone","mirror","kira"],
  "6.9":   ["dominion","bashir"],
  "6.10":  ["standalone","ferengi","quark","fanfav"],
  "6.11":  ["dominion","sisko","dukat","heavy","fanfav"],
  "6.12":  ["standalone","quark","experiment"],
  "6.13":  ["standalone","sisko","experiment","fanfav","heavy"],
  "6.14":  ["dominion","jadzia"],
  "6.15":  ["standalone","obrien"],
  "6.16":  ["dominion","worf","jadzia"],
  "6.17":  ["standalone","kira","occupation","dukat","heavy"],
  "6.18":  ["dominion","bashir","section31"],
  "6.19":  ["dominion","sisko","garak","fanfav","experiment","heavy","milestone"],
  "6.20":  ["standalone","odo","kira"],
  "6.21":  ["standalone","bajor","sisko","kira","jake"],
  "6.22":  ["dominion","jake"],
  "6.23":  ["standalone","ferengi","quark"],
  "6.24":  ["standalone","obrien"],
  "6.25":  ["standalone","sisko"],
  "6.26":  ["dominion","bajor","jadzia","worf","sisko","milestone","heavy"],
  // season 7
  "7.1":   ["dominion","twoparter","bajor","sisko","worf"],
  "7.2":   ["dominion","twoparter","bajor","sisko","ezri","worf","milestone"],
  "7.3":   ["standalone","ezri","garak"],
  "7.4":   ["standalone","sisko","experiment"],
  "7.5":   ["standalone","bashir"],
  "7.6":   ["dominion","odo"],
  "7.7":   ["standalone","worf","klingon","fanfav"],
  "7.8":   ["dominion","heavy","fanfav"],
  "7.9":   ["standalone","bajor","kira","dukat"],
  "7.10":  ["dominion","fanfav","heavy"],
  "7.11":  ["standalone","ezri","obrien"],
  "7.12":  ["standalone","mirror","ferengi","quark","ezri"],
  "7.13":  ["standalone","ezri"],
  "7.14":  ["standalone","odo"],
  "7.15":  ["standalone","experiment","fanfav"],
  "7.16":  ["dominion","bashir","section31"],
  "7.17":  ["dominion","finalchapter","worf","ezri","bajor","sisko"],
  "7.18":  ["dominion","finalchapter","bajor","sisko","dukat"],
  "7.19":  ["dominion","finalchapter","bajor","worf","ezri","dukat"],
  "7.20":  ["dominion","finalchapter","bajor","milestone","dukat"],
  "7.21":  ["dominion","finalchapter","kira","odo","section31","klingon"],
  "7.22":  ["dominion","finalchapter","worf","klingon","kira","fanfav","heavy"],
  "7.23":  ["dominion","finalchapter","bashir","section31"],
  "7.24":  ["dominion","finalchapter","ferengi","quark","kira"],
  "7.25":  ["dominion","finalchapter","twoparter","bajor","sisko","milestone"],
  "7.26":  ["dominion","finalchapter","twoparter","bajor","sisko","milestone"],
};
