// Curated episode vibes for NCIS. Keys are "S.E" (TVmaze numbering).
// Season premieres and finales are auto-tagged by the engine — they are not listed here.
window.TAG_DEFS = {
  arc:        {label:"Serial-arc episode", desc:"Ari, La Grenouille, Somalia, Dearing, the Calling, Sahar, Marino\u2026"},
  motw:       {label:"Classic case of the week", desc:"Standalone Navy-yard whodunits \u2014 the show's bread and butter"},
  twoparter:  {label:"Two-parter / cliffhanger", desc:"Multi-part stories and season-bridging cliffhangers"},
  fanfav:     {label:"Fan favorite", desc:"Commonly cited best-of episodes"},
  heavy:      {label:"Gut-punch / major death", desc:"Deaths, exits and the emotional heavy hitters"},
  crossover:  {label:"Franchise crossover", desc:"NCIS: LA, New Orleans and Hawai'i turn up (JAG backdoor pilots excluded)"},
  xmas:       {label:"Christmas & holiday", desc:"The annual December case"},
  milestone:  {label:"Milestone episode", desc:"100th, 200th, 300th, 350th, 400th, 450th and 500th"},
  format:     {label:"Format experiment", desc:"Nonlinear, framed or otherwise structurally odd episodes"},
  newface:    {label:"New team member debuts", desc:"First appearance of a future series regular"},
  gibbs:      {label:"Gibbs spotlight", desc:""},
  tony:       {label:"Tony DiNozzo spotlight", desc:""},
  kate:       {label:"Kate Todd spotlight", desc:""},
  ziva:       {label:"Ziva David spotlight", desc:""},
  mcgee:      {label:"McGee spotlight", desc:""},
  abby:       {label:"Abby spotlight", desc:""},
  ducky:      {label:"Ducky spotlight", desc:""},
  palmer:     {label:"Jimmy Palmer spotlight", desc:""},
  bishop:     {label:"Ellie Bishop spotlight", desc:""},
  torres:     {label:"Nick Torres spotlight", desc:""},
  knight:     {label:"Jessica Knight spotlight", desc:""},
  kasie:      {label:"Kasie Hines spotlight", desc:""},
  sloane:     {label:"Jack Sloane spotlight", desc:""},
  vance:      {label:"Leon Vance spotlight", desc:""},
  fornell:    {label:"Fornell spotlight", desc:""},
  parker:     {label:"Alden Parker spotlight", desc:""},
};
window.EP_TAGS = {
  // Season 1
  "1.1":["gibbs","kate","fanfav","motw"], "1.2":["motw"], "1.3":["fornell","motw"], "1.4":["motw"],
  "1.5":["ducky","motw"], "1.6":["motw"], "1.7":["mcgee","newface","fanfav","motw"], "1.8":["motw"], "1.9":["motw"],
  "1.10":["motw"], "1.11":["motw"], "1.12":["motw"], "1.13":["gibbs","fanfav","motw"], "1.14":["motw"],
  "1.15":["gibbs","motw"], "1.16":["arc","ducky","kate","heavy","fanfav"], "1.17":["motw"], "1.18":["motw"],
  "1.19":["mcgee","motw"], "1.20":["motw"], "1.21":["palmer","newface","motw"], "1.22":["motw"],
  "1.23":["arc","gibbs","kate","fanfav"],
  // Season 2
  "2.1":["motw"], "2.2":["motw"], "2.3":["motw"], "2.4":["motw"], "2.5":["fornell","motw"], "2.6":["kate","motw"],
  "2.7":["gibbs","ducky","heavy","fanfav"], "2.8":["ducky","motw"], "2.9":["kate","motw"],
  "2.10":["tony","fanfav","motw"], "2.11":["motw"], "2.12":["mcgee","motw"], "2.13":["ducky","heavy","fanfav"],
  "2.14":["mcgee","motw"], "2.15":["motw"], "2.16":["abby","motw"], "2.17":["mcgee","motw"], "2.18":["abby","motw"],
  "2.19":["fornell","motw"], "2.20":["mcgee","motw"], "2.21":["kate","gibbs","motw"],
  "2.22":["arc","tony","abby","heavy","fanfav"], "2.23":["arc","kate","gibbs","heavy","fanfav"],
  // Season 3
  "3.1":["arc","twoparter","gibbs","kate","newface","heavy","fanfav"],
  "3.2":["arc","twoparter","ziva","gibbs","heavy","fanfav"], "3.3":["gibbs","motw"], "3.4":["motw"], "3.5":["motw"],
  "3.6":["motw"], "3.7":["gibbs","fanfav","motw"], "3.8":["tony","ziva","fanfav","motw"],
  "3.9":["tony","abby","fanfav"], "3.10":["mcgee","heavy"], "3.11":["motw"], "3.12":["tony","ziva","motw"],
  "3.13":["motw"], "3.14":["motw"], "3.15":["ducky","motw"], "3.16":["palmer","motw"], "3.17":["motw"],
  "3.18":["mcgee","motw"], "3.19":["motw"], "3.20":["motw"], "3.21":["abby","mcgee","fanfav"],
  "3.22":["ziva","motw"], "3.23":["arc","twoparter","gibbs","heavy","fanfav"],
  "3.24":["arc","twoparter","gibbs","heavy","fanfav"],
  // Season 4
  "4.1":["arc","ziva","fanfav"], "4.2":["motw"], "4.3":["motw"], "4.4":["motw"], "4.5":["motw"], "4.6":["motw"],
  "4.7":["motw"], "4.8":["motw"], "4.9":["mcgee","motw"], "4.10":["arc","motw"], "4.11":["abby","motw"],
  "4.12":["motw"], "4.13":["motw"], "4.14":["arc","tony"], "4.15":["palmer","motw"],
  "4.16":["ducky","heavy","fanfav"], "4.17":["motw"], "4.18":["motw"], "4.19":["heavy","motw"],
  "4.20":["mcgee","fanfav","motw"], "4.21":["arc","tony"], "4.22":["format","motw"], "4.23":["arc","tony"],
  "4.24":["arc","tony","heavy","fanfav"],
  // Season 5
  "5.1":["arc","tony","heavy","fanfav"], "5.2":["arc","abby","motw"], "5.3":["gibbs","motw"], "5.4":["motw"],
  "5.5":["heavy","fanfav","motw"], "5.6":["milestone","fanfav","motw"], "5.7":["gibbs","heavy","fanfav"],
  "5.8":["motw"], "5.9":["gibbs","motw"], "5.10":["motw"], "5.11":["motw"], "5.12":["tony","mcgee","motw"],
  "5.13":["abby","motw"], "5.14":["arc","ziva","vance","newface"], "5.15":["mcgee","motw"], "5.16":["ziva","heavy"],
  "5.17":["palmer","motw"], "5.18":["arc","twoparter","heavy","fanfav"],
  "5.19":["arc","twoparter","heavy","fanfav"],
  // Season 6
  "6.1":["arc","vance","newface"], "6.2":["tony","motw"], "6.3":["motw"], "6.4":["gibbs","heavy","fanfav"],
  "6.5":["fornell","motw"], "6.6":["abby","motw"], "6.7":["motw"], "6.8":["arc","twoparter"],
  "6.9":["arc","twoparter","fanfav"], "6.10":["motw"], "6.11":["xmas","fanfav","motw"], "6.12":["mcgee","motw"],
  "6.13":["ducky","heavy","fanfav"], "6.14":["motw"], "6.15":["motw"], "6.16":["tony","motw"], "6.17":["motw"],
  "6.18":["vance","motw"], "6.19":["motw"], "6.20":["arc","motw"], "6.21":["abby","motw"],
  "6.22":["arc","crossover","twoparter"], "6.23":["arc","crossover","twoparter"], "6.24":["arc","ziva"],
  "6.25":["arc","twoparter","ziva","heavy","fanfav"],
  // Season 7
  "7.1":["arc","twoparter","ziva","tony","heavy","fanfav"], "7.2":["arc","ziva"], "7.3":["motw"],
  "7.4":["arc","ziva","fanfav"], "7.5":["motw"], "7.6":["gibbs","motw"], "7.7":["vance","motw"], "7.8":["motw"],
  "7.9":["heavy","fanfav","motw"], "7.10":["xmas","mcgee","motw"], "7.11":["motw"],
  "7.12":["tony","newface","fanfav"], "7.13":["ziva","format","motw"], "7.14":["motw"], "7.15":["motw"],
  "7.16":["gibbs","heavy"], "7.17":["motw"], "7.18":["motw"], "7.19":["tony","motw"], "7.20":["palmer","motw"],
  "7.21":["gibbs","motw"], "7.22":["arc","abby","gibbs"], "7.23":["arc","twoparter","heavy"],
  "7.24":["arc","twoparter","gibbs","heavy","fanfav"],
  // Season 8
  "8.1":["arc","gibbs","heavy"], "8.2":["motw"], "8.3":["motw"], "8.4":["motw"], "8.5":["motw"],
  "8.6":["abby","fanfav","motw"], "8.7":["tony","motw"], "8.8":["arc","twoparter","ziva"],
  "8.9":["arc","twoparter","gibbs","heavy"], "8.10":["motw"], "8.11":["motw"], "8.12":["motw"], "8.13":["motw"],
  "8.14":["format","fanfav","motw"], "8.15":["motw"], "8.16":["mcgee","motw"], "8.17":["motw"], "8.18":["motw"],
  "8.19":["motw"], "8.20":["arc","ziva"], "8.21":["arc","motw"], "8.22":["arc","tony","fanfav"],
  "8.23":["arc","twoparter","heavy","fanfav"], "8.24":["arc","twoparter","gibbs","heavy","fanfav"],
  // Season 9
  "9.1":["arc","tony"], "9.2":["motw"], "9.3":["mcgee","motw"], "9.4":["motw"], "9.5":["motw"], "9.6":["motw"],
  "9.7":["fornell","motw"], "9.8":["twoparter","motw"], "9.9":["twoparter","ziva","heavy"], "9.10":["arc","tony"],
  "9.11":["xmas","ziva","motw"], "9.12":["arc","motw"], "9.13":["ziva","motw"],
  "9.14":["milestone","format","gibbs","heavy","fanfav"], "9.15":["motw"], "9.16":["gibbs","motw"], "9.17":["motw"],
  "9.18":["gibbs","motw"], "9.19":["vance","motw"], "9.20":["ziva","motw"], "9.21":["mcgee","motw"],
  "9.22":["arc","ziva"], "9.23":["arc","motw"], "9.24":["arc","twoparter","palmer","heavy","fanfav"],
  // Season 10
  "10.1":["arc","twoparter","heavy","fanfav"], "10.2":["arc","motw"], "10.3":["ducky","motw"],
  "10.4":["ziva","motw"], "10.5":["vance","gibbs","heavy"], "10.6":["twoparter","motw"],
  "10.7":["twoparter","motw"], "10.8":["ziva","motw"], "10.9":["fornell","fanfav","motw"],
  "10.10":["xmas","tony","motw"], "10.11":["arc","ziva","vance","heavy","fanfav"],
  "10.12":["arc","ziva","vance","heavy","fanfav"], "10.13":["arc","motw"], "10.14":["mcgee","motw"],
  "10.15":["vance","heavy"], "10.16":["ducky","palmer","fanfav"], "10.17":["gibbs","motw"],
  "10.18":["heavy","motw"], "10.19":["motw"], "10.20":["ziva","motw"], "10.21":["arc","ziva","tony","fanfav"],
  "10.22":["arc","ziva"], "10.23":["arc","motw"], "10.24":["arc","heavy"],
  // Season 11
  "11.1":["arc","gibbs","heavy"], "11.2":["arc","ziva","tony","heavy","fanfav"], "11.3":["motw"], "11.4":["motw"],
  "11.5":["mcgee","motw"], "11.6":["motw"], "11.7":["gibbs","heavy"], "11.8":["motw"],
  "11.9":["arc","bishop","newface"], "11.10":["xmas","fornell","bishop","motw"], "11.11":["xmas","abby","motw"],
  "11.12":["arc","mcgee","heavy"], "11.13":["arc","mcgee"], "11.14":["arc","bishop"], "11.15":["motw"],
  "11.16":["tony","motw"], "11.17":["motw"], "11.18":["arc","crossover","twoparter"],
  "11.19":["arc","crossover","twoparter"], "11.20":["mcgee","format","fanfav"], "11.21":["motw"], "11.22":["motw"],
  "11.23":["tony","motw"], "11.24":["gibbs","heavy","fanfav"],
  // Season 12
  "12.1":["arc","gibbs","motw"], "12.2":["vance","motw"], "12.3":["ducky","bishop","fanfav"], "12.4":["motw"],
  "12.5":["motw"], "12.6":["motw"], "12.7":["bishop","motw"], "12.8":["motw"], "12.9":["bishop","motw"],
  "12.10":["xmas","mcgee","gibbs","fanfav"], "12.11":["arc","fornell","heavy","fanfav"], "12.12":["arc","tony"],
  "12.13":["palmer","motw"], "12.14":["bishop","motw"], "12.15":["arc","fornell","gibbs","heavy"],
  "12.16":["arc","gibbs"], "12.17":["tony","motw"], "12.18":["mcgee","motw"], "12.19":["motw"], "12.20":["motw"],
  "12.21":["bishop","motw"], "12.22":["mcgee","motw"], "12.23":["arc","twoparter","heavy"],
  "12.24":["arc","twoparter","gibbs","heavy","fanfav"],
  // Season 13
  "13.1":["arc","gibbs","heavy"], "13.2":["abby","motw"], "13.3":["bishop","motw"], "13.4":["ducky","motw"],
  "13.5":["motw"], "13.6":["mcgee","motw"], "13.7":["motw"], "13.8":["arc","tony"], "13.9":["bishop","motw"],
  "13.10":["ducky","motw"], "13.11":["xmas","ducky","fanfav"], "13.12":["arc","crossover","twoparter","abby"],
  "13.13":["motw"], "13.14":["format","fanfav","motw"], "13.15":["motw"], "13.16":["arc","tony"],
  "13.17":["mcgee","motw"], "13.18":["milestone","motw"], "13.19":["tony","motw"], "13.20":["motw"],
  "13.21":["arc","motw"], "13.22":["arc","motw"], "13.23":["arc","twoparter","heavy"],
  "13.24":["arc","twoparter","tony","ziva","heavy","fanfav"],
  // Season 14
  "14.1":["arc","torres","newface"], "14.2":["torres","motw"], "14.3":["torres","motw"], "14.4":["mcgee","motw"],
  "14.5":["bishop","motw"], "14.6":["motw"], "14.7":["torres","bishop","motw"], "14.8":["motw"],
  "14.9":["vance","motw"], "14.10":["xmas","ducky","heavy","fanfav"], "14.11":["bishop","motw"],
  "14.12":["bishop","motw"], "14.13":["heavy","fanfav","motw"], "14.14":["motw"],
  "14.15":["arc","crossover","twoparter","abby"], "14.16":["torres","bishop","motw"], "14.17":["motw"],
  "14.18":["torres","motw"], "14.19":["torres","bishop","motw"], "14.20":["palmer","motw"],
  "14.21":["torres","motw"], "14.22":["motw"], "14.23":["mcgee","fanfav"],
  "14.24":["arc","torres","mcgee","gibbs","heavy"],
  // Season 15
  "15.1":["arc","torres","gibbs","heavy"], "15.2":["sloane","newface"], "15.3":["torres","motw"],
  "15.4":["sloane","torres","bishop","motw"], "15.5":["motw"], "15.6":["torres","motw"], "15.7":["motw"],
  "15.8":["abby","motw"], "15.9":["xmas","sloane","mcgee","fanfav"], "15.10":["xmas","sloane","torres","motw"],
  "15.11":["torres","bishop","motw"], "15.12":["motw"], "15.13":["torres","motw"],
  "15.14":["arc","twoparter","torres","bishop"], "15.15":["arc","twoparter","mcgee","fornell"],
  "15.16":["ducky","motw"], "15.17":["ducky","kasie","newface"], "15.18":["motw"], "15.19":["motw"],
  "15.20":["milestone","torres","motw"], "15.21":["arc","abby","gibbs"], "15.22":["arc","abby","heavy","fanfav"],
  "15.23":["arc","vance","motw"], "15.24":["arc","sloane","vance","heavy"],
  // Season 16
  "16.1":["arc","vance","gibbs"], "16.2":["torres","motw"], "16.3":["vance","motw"],
  "16.4":["gibbs","mcgee","torres","fanfav"], "16.5":["motw"], "16.6":["torres","motw"], "16.7":["bishop","motw"],
  "16.8":["kasie","torres","bishop","motw"], "16.9":["motw"], "16.10":["xmas","fanfav","motw"],
  "16.11":["torres","motw"], "16.12":["ducky","motw"], "16.13":["arc","bishop","ziva","heavy","fanfav"],
  "16.14":["mcgee","format","fanfav"], "16.15":["torres","motw"], "16.16":["palmer","motw"],
  "16.17":["bishop","motw"], "16.18":["torres","motw"], "16.19":["sloane","motw"],
  "16.20":["gibbs","heavy","fanfav"], "16.21":["arc","twoparter","kasie","mcgee"],
  "16.22":["arc","twoparter","mcgee"], "16.23":["sloane","motw"],
  "16.24":["arc","ziva","fornell","gibbs","heavy","fanfav"],
  // Season 17
  "17.1":["arc","twoparter","ziva","gibbs","fanfav"], "17.2":["arc","twoparter","ziva","fanfav"],
  "17.3":["arc","sloane","ziva"], "17.4":["torres","bishop","motw"], "17.5":["gibbs","motw"],
  "17.6":["kasie","motw"], "17.7":["motw"], "17.8":["palmer","motw"], "17.9":["mcgee","motw"],
  "17.10":["xmas","arc","ziva","fanfav"], "17.11":["arc","ziva","gibbs","heavy","fanfav"], "17.12":["motw"],
  "17.13":["motw"], "17.14":["torres","bishop","motw"], "17.15":["sloane","ducky","motw"], "17.16":["motw"],
  "17.17":["format","fanfav","motw"], "17.18":["sloane","motw"], "17.19":["kasie","motw"],
  "17.20":["gibbs","heavy","fanfav"],
  // Season 18
  "18.1":["arc","gibbs","fornell"], "18.2":["milestone","format","gibbs","ducky","fanfav"], "18.3":["motw"],
  "18.4":["mcgee","motw"], "18.5":["arc","gibbs","fornell","heavy","fanfav"], "18.6":["torres","bishop","motw"],
  "18.7":["palmer","sloane","heavy","fanfav"], "18.8":["torres","bishop","motw"], "18.9":["motw"], "18.10":["motw"],
  "18.11":["torres","bishop","motw"], "18.12":["torres","heavy"], "18.13":["vance","motw"],
  "18.14":["gibbs","motw"], "18.15":["knight","newface","motw"], "18.16":["arc","bishop","knight","heavy","fanfav"],
  // Season 19
  "19.1":["arc","twoparter","gibbs"], "19.2":["arc","gibbs","parker","newface"],
  "19.3":["arc","gibbs","parker","knight"], "19.4":["arc","gibbs","mcgee","heavy","fanfav"],
  "19.5":["palmer","motw"], "19.6":["motw"], "19.7":["motw"], "19.8":["kasie","motw"], "19.9":["format","motw"],
  "19.10":["motw"], "19.11":["knight","motw"], "19.12":["motw"], "19.13":["kasie","torres","motw"],
  "19.14":["motw"], "19.15":["parker","motw"], "19.16":["motw"], "19.17":["crossover","palmer","knight","torres"],
  "19.18":["torres","heavy"], "19.19":["motw"], "19.20":["knight","motw"], "19.21":["arc","twoparter","parker"],
  // Season 20
  "20.1":["arc","twoparter","parker","crossover"], "20.2":["mcgee","motw"], "20.3":["motw"], "20.4":["motw"],
  "20.5":["motw"], "20.6":["motw"], "20.7":["motw"], "20.8":["xmas","motw"], "20.9":["mcgee","motw"],
  "20.10":["crossover","fanfav"], "20.11":["parker","palmer","knight","motw"], "20.12":["motw"], "20.13":["motw"],
  "20.14":["motw"], "20.15":["milestone","motw"], "20.16":["motw"], "20.17":["motw"], "20.18":["kasie","motw"],
  "20.19":["motw"], "20.20":["palmer","motw"], "20.21":["arc","palmer","knight"], "20.22":["arc","torres","heavy"],
  // Season 21
  "21.1":["arc","torres","heavy","fanfav"], "21.2":["ducky","tony","heavy","fanfav"], "21.3":["kasie","fanfav"],
  "21.4":["motw"], "21.5":["knight","mcgee","motw"], "21.6":["motw"], "21.7":["arc","crossover","vance"],
  "21.8":["fanfav","motw"], "21.9":["motw"], "21.10":["arc","parker","knight"],
  // Season 22
  "22.1":["arc","motw"], "22.2":["vance","motw"], "22.3":["motw"], "22.4":["motw"], "22.5":["motw"],
  "22.6":["knight","motw"], "22.7":["torres","motw"], "22.8":["parker","motw"], "22.9":["xmas","fanfav","motw"],
  "22.10":["parker","torres","motw"], "22.11":["arc","motw"], "22.12":["kasie","mcgee","motw"], "22.13":["motw"],
  "22.14":["motw"], "22.15":["motw"], "22.16":["motw"], "22.17":["motw"], "22.18":["crossover","motw"],
  "22.19":["arc","mcgee","torres","knight"], "22.20":["arc","parker","heavy"],
  // Season 23
  "23.1":["arc","twoparter","parker","heavy"], "23.2":["arc","twoparter","parker","heavy"],
  "23.3":["arc","torres","knight"], "23.4":["motw"], "23.5":["motw"], "23.6":["motw"], "23.7":["motw"],
  "23.8":["motw"], "23.9":["xmas","arc","mcgee","torres","parker"],
  "23.10":["arc","bishop","knight","torres","fanfav"], "23.11":["motw"], "23.12":["motw"],
  "23.13":["milestone","arc","fanfav"], "23.14":["motw"], "23.15":["motw"], "23.16":["motw"],
  "23.17":["crossover","kasie","format"], "23.18":["crossover","motw"], "23.19":["arc","parker"],
  "23.20":["arc","heavy"],
};
