// Curated episode vibes for Buffy the Vampire Slayer. Keys are "S.E".
// Season premieres/finales are auto-tagged in app.js — not repeated here.
window.TAG_DEFS = {
  fanfav:    {label:"Fan favorite", desc:"The ones everybody puts on their best-of list"},
  heavy:     {label:"Gut-punch", desc:"Grief, heartbreak and the episodes that hurt (yes, 'The Body')"},
  format:    {label:"Format experiment", desc:"Whedon and co. breaking the format — silent, musical, dream-logic, POV tricks, alternate realities"},
  musical:   {label:"Musical", desc:"'Once More, with Feeling'"},
  arc:       {label:"Arc / mythology", desc:"Big Bad plot, Slayer lore and season-long story"},
  motw:      {label:"Monster of the week", desc:"Standalone-friendly Sunnydale weirdness"},
  comedy:    {label:"Comedy", desc:"The funny ones"},
  horror:    {label:"Extra creepy", desc:"Genuinely scary — watch with the lights on"},
  twopart:   {label:"Two-parter", desc:"Halves of a single story"},
  angelverse:{label:"Angel-verse", desc:"Crossovers with 'Angel' and trips to Los Angeles"},
  milestone: {label:"Milestone", desc:"The 100th episode, the musical, the series' landmark hours"},
  buffy:     {label:"Buffy-centric", desc:"The Slayer gets the spotlight"},
  willow:    {label:"Willow-centric", desc:"Willow Rosenberg episodes"},
  xander:    {label:"Xander-centric", desc:"Xander Harris episodes"},
  giles:     {label:"Giles-centric", desc:"Rupert Giles, Ripper included"},
  spike:     {label:"Spike-centric", desc:"William the Bloody"},
  angel:     {label:"Angel-centric", desc:"Angel and/or Angelus"},
  faith:     {label:"Faith-centric", desc:"The other Slayer"},
  anya:      {label:"Anya-centric", desc:"Anyanka, vengeance demon and capitalist"},
  dawn:      {label:"Dawn-centric", desc:"Dawn Summers, the Key"},
  cordelia:  {label:"Cordelia-centric", desc:"Cordelia Chase, before LA"},
  oz:        {label:"Oz-centric", desc:"Daniel 'Oz' Osbourne"},
  tara:      {label:"Tara-centric", desc:"Tara Maclay"},
  riley:     {label:"Riley-centric", desc:"Riley Finn and the Initiative"},
};

window.EP_TAGS = {
  "1.1":["arc","twopart","buffy"], "1.2":["arc","twopart"], "1.3":["motw"], "1.4":["motw","xander"],
  "1.5":["motw","buffy"], "1.6":["motw","xander","horror"], "1.7":["arc","angel","fanfav"],
  "1.8":["motw","willow"], "1.9":["motw","comedy","giles"], "1.10":["motw","buffy"],
  "1.11":["motw","cordelia"], "1.12":["arc","fanfav","heavy","buffy"],

  "2.1":["arc","buffy"], "2.2":["motw"], "2.3":["arc","fanfav","spike"], "2.4":["motw","xander"],
  "2.5":["motw","buffy"], "2.6":["fanfav","comedy","giles"], "2.7":["arc","fanfav","heavy","angel"],
  "2.8":["motw","giles"], "2.9":["arc","twopart","spike"], "2.10":["arc","twopart","spike"],
  "2.11":["motw","buffy"], "2.12":["motw"], "2.13":["arc","twopart","fanfav","buffy","angel"],
  "2.14":["arc","twopart","fanfav","heavy","angel"], "2.15":["motw","oz","willow"],
  "2.16":["comedy","xander","cordelia","fanfav"], "2.17":["arc","heavy","fanfav","angel","giles"],
  "2.18":["motw","horror"], "2.19":["motw","fanfav","angel"], "2.20":["motw","comedy"],
  "2.21":["arc","twopart","fanfav","angel"], "2.22":["arc","twopart","fanfav","heavy","buffy","angel"],

  "3.1":["arc","buffy","angelverse"], "3.2":["motw","arc"], "3.3":["arc","faith"],
  "3.4":["motw","oz"], "3.5":["comedy","cordelia","fanfav"], "3.6":["comedy","fanfav","giles"],
  "3.7":["arc","angel","faith"], "3.8":["fanfav","spike","comedy","heavy"],
  "3.9":["format","fanfav","anya","cordelia"], "3.10":["arc","angel","heavy"],
  "3.11":["motw","willow"], "3.12":["arc","giles","buffy","fanfav"],
  "3.13":["format","fanfav","xander","comedy"], "3.14":["arc","faith","fanfav"],
  "3.15":["arc","faith","heavy"], "3.16":["format","comedy","fanfav","willow","anya"],
  "3.17":["arc","faith","angel"], "3.18":["format","buffy","fanfav"], "3.19":["arc","willow"],
  "3.20":["heavy","fanfav","buffy","angel"], "3.21":["arc","twopart","faith"],
  "3.22":["arc","twopart","fanfav","angel","faith"],

  "4.1":["arc","buffy"], "4.2":["comedy","buffy"], "4.3":["arc","spike"],
  "4.4":["motw","comedy","horror"], "4.5":["comedy","buffy"], "4.6":["heavy","oz","willow","arc"],
  "4.7":["arc","riley","spike"], "4.8":["comedy","angelverse","fanfav"],
  "4.9":["comedy","fanfav","willow","spike"], "4.10":["format","fanfav","horror","milestone","tara"],
  "4.11":["arc","riley"], "4.12":["comedy","giles","fanfav"], "4.13":["arc","riley"],
  "4.14":["arc","riley"], "4.15":["arc","twopart","faith"],
  "4.16":["format","twopart","fanfav","faith"], "4.17":["format","comedy","fanfav"],
  "4.18":["motw","riley"], "4.19":["heavy","oz","willow","tara","fanfav"],
  "4.20":["arc","angelverse","spike"], "4.21":["arc","fanfav"],
  "4.22":["format","fanfav","milestone","buffy","willow","xander","giles"],

  "5.1":["comedy","motw","fanfav","dawn"], "5.2":["arc","dawn"],
  "5.3":["comedy","xander","format","fanfav"], "5.4":["arc","riley","spike"],
  "5.5":["arc","dawn","fanfav"], "5.6":["tara","willow","fanfav","heavy"],
  "5.7":["spike","fanfav","arc","format"], "5.8":["arc","heavy"], "5.9":["motw","horror","heavy"],
  "5.10":["heavy","riley","buffy","arc"], "5.11":["comedy","anya"], "5.12":["arc","giles","buffy"],
  "5.13":["arc","dawn","heavy"], "5.14":["spike","arc"], "5.15":["buffy","arc"],
  "5.16":["heavy","fanfav","format","milestone","willow","anya"],
  "5.17":["heavy","dawn","angelverse"], "5.18":["comedy","spike","fanfav","buffy"],
  "5.19":["arc","willow","tara","heavy"], "5.20":["arc"], "5.21":["arc","buffy","willow"],
  "5.22":["arc","heavy","fanfav","milestone","buffy"],

  "6.1":["arc","twopart","willow"], "6.2":["arc","twopart","buffy"], "6.3":["arc","heavy","buffy"],
  "6.4":["arc","giles"], "6.5":["comedy","buffy","format"], "6.6":["motw","dawn"],
  "6.7":["musical","format","fanfav","milestone","heavy"],
  "6.8":["comedy","fanfav","format","heavy","giles"], "6.9":["arc","willow","spike"],
  "6.10":["arc","willow","heavy"], "6.11":["comedy","format","buffy"],
  "6.12":["comedy","motw","buffy"], "6.13":["heavy","buffy","spike","arc"],
  "6.14":["motw","dawn"], "6.15":["riley","buffy","heavy"],
  "6.16":["heavy","anya","xander","fanfav"], "6.17":["format","fanfav","buffy"],
  "6.18":["anya","spike","arc"], "6.19":["heavy","fanfav","arc","tara","willow"],
  "6.20":["arc","willow","heavy","fanfav"], "6.21":["arc","twopart","willow"],
  "6.22":["arc","twopart","fanfav","xander","willow"],

  "7.1":["arc","dawn"], "7.2":["arc","spike","fanfav"], "7.3":["motw","willow","format"],
  "7.4":["heavy","buffy","motw"], "7.5":["anya","fanfav","format","heavy"],
  "7.6":["comedy","dawn"], "7.7":["format","fanfav","heavy","willow","dawn","buffy"],
  "7.8":["arc","spike"], "7.9":["arc","spike"], "7.10":["arc","giles"], "7.11":["arc","buffy"],
  "7.12":["dawn","xander","fanfav","heavy"], "7.13":["willow","arc","tara"],
  "7.14":["arc","xander","buffy"], "7.15":["arc","buffy"], "7.16":["format","comedy","fanfav"],
  "7.17":["spike","giles","arc","fanfav","heavy"], "7.18":["arc","faith","heavy","xander","fanfav"],
  "7.19":["arc","buffy","heavy","faith"], "7.20":["arc","spike","faith"],
  "7.21":["arc","angelverse","faith"],
  "7.22":["arc","fanfav","heavy","milestone","angelverse","buffy","willow","spike"],
};
