window.TAG_DEFS = {
  fanfav:     { label: "Fan favorite", desc: "The ones people bring up first" },
  heavy:      { label: "Gut-punch", desc: "Fraggle Rock's occasional surprisingly poignant episodes" },
  milestone:  { label: "Milestone", desc: "Hinge points and format-breakers for the show's world" },
  classic:    { label: "Classic Fraggle Rock", desc: "A good day in the Rock — TVmaze has little more than the title for this one, so it's not filed under anything more specific" },
  musical:    { label: "Musical highlight", desc: "A song-and-dance-forward episode, beyond the show's usual one-or-two numbers" },
  trashheap:  { label: "Trash Heap wisdom", desc: "Marjory the Trash Heap (or her stand-in) is consulted" },
  doozer:     { label: "Doozer-centric", desc: "Cotterpin, construction and Doozer politics" },
  gorg:       { label: "Gorg-centric", desc: "Pa, Ma or Junior Gorg and the garden" },
  postcard:   { label: "Traveling Matt postcard", desc: "Uncle Matt's reports from \"Outer Space\" drive the episode" },
  gobo:       { label: "Gobo spotlight" },
  mokey:      { label: "Mokey spotlight" },
  wembley:    { label: "Wembley spotlight" },
  boober:     { label: "Boober spotlight" },
  red:        { label: "Red spotlight" },
  doc:        { label: "Doc & Sprocket spotlight" },
};

window.EP_TAGS = {
  "1.1": ["milestone", "doc", "postcard"],
  "1.2": ["wembley", "gorg"],
  "1.3": ["red", "doc"],
  "1.4": ["classic"],
  "1.5": ["wembley", "classic"],
  "1.6": ["mokey", "doozer"],
  "1.7": ["wembley", "boober"],
  "1.8": ["classic"],
  "1.9": ["wembley", "red", "doc"],
  "1.10": ["boober", "classic"],
  "1.11": ["classic"],
  "1.12": ["milestone", "postcard"],
  "1.13": ["wembley", "doc"],
  "1.14": ["gobo", "red"],
  "1.15": ["boober", "classic"],
  "1.16": ["fanfav", "classic"],
  "1.17": ["postcard", "gobo"],
  "1.18": ["musical", "classic"],
  "1.19": ["gorg", "classic"],
  "1.20": ["gorg", "classic"],
  "1.21": ["gobo"],
  "1.22": ["heavy", "fanfav", "mokey"],
  "1.23": ["classic"],
  "1.24": ["trashheap", "mokey", "milestone"],

  "2.1": ["wembley", "doc"],
  "2.2": ["boober", "classic"],
  "2.3": ["trashheap"],
  "2.4": ["red"],
  "2.5": ["postcard", "milestone"],
  "2.6": ["boober", "fanfav"],
  "2.7": ["mokey", "musical"],
  "2.8": ["classic"],
  "2.9": ["gorg"],
  "2.10": ["doc", "gorg"],
  "2.11": ["classic", "fanfav"],
  "2.12": ["doozer"],
  "2.13": ["red"],
  "2.14": ["classic"],
  "2.15": ["classic"],
  "2.16": ["gorg"],
  "2.17": ["milestone", "fanfav"],
  "2.18": ["musical", "classic"],
  "2.19": ["classic"],
  "2.20": ["classic"],
  "2.21": ["wembley"],
  "2.22": ["doozer"],
  "2.23": ["boober"],
  "2.24": ["classic"],

  "3.1": ["milestone", "fanfav", "musical", "doc"],
  "3.2": ["red", "classic"],
  "3.3": ["boober"],
  "3.4": ["classic"],
  "3.5": ["classic"],
  "3.6": ["musical", "classic"],
  "3.7": ["trashheap"],
  "3.8": ["classic"],
  "3.9": ["wembley"],
  "3.10": ["milestone", "fanfav"],
  "3.11": ["classic"],
  "3.12": ["gobo"],
  "3.13": ["boober", "wembley"],
  "3.14": ["gorg", "classic"],
  "3.15": ["classic"],
  "3.16": ["doc", "classic"],
  "3.17": ["classic"],
  "3.18": ["classic"],
  "3.19": ["classic"],
  "3.20": ["mokey", "fanfav"],
  "3.21": ["classic"],
  "3.22": ["classic"],

  "4.1": ["doc"],
  "4.2": ["wembley"],
  "4.3": ["musical", "classic"],
  "4.4": ["postcard"],
  "4.5": ["gorg", "musical"],
  "4.6": ["musical", "classic"],
  "4.7": ["classic"],
  "4.8": ["classic"],
  "4.9": ["wembley"],
  "4.10": ["red"],
  "4.11": ["mokey", "red", "doc"],
  "4.12": ["doc", "fanfav"],
  "4.13": ["boober", "gorg", "milestone"],

  "5.1": ["classic"],
  "5.2": ["classic"],
  "5.3": ["classic"],
  "5.4": ["doozer", "milestone", "fanfav"],
  "5.5": ["milestone"],
  "5.6": ["classic"],
  "5.7": ["heavy"],
  "5.8": ["mokey", "milestone"],
  "5.9": ["classic"],
  "5.10": ["red"],
  "5.11": ["gorg", "milestone"],
  "5.12": ["classic"],
  "5.13": ["milestone", "fanfav", "heavy"],
};
