// M*A*S*H — episode tags. Season premieres and finales are auto-tagged by the engine, so they aren't listed here.
// Keys are the season.episode numbers used in episodes.json.
window.TAG_DEFS = {
  fanfav:     {label:"Fan favorite", desc:"The ones people rewatch first"},
  heavy:      {label:"Gut-punch", desc:"The war wins this one"},
  funny:      {label:"Full-tilt farce", desc:"The still, the pranks, the Section 8 schemes"},
  war:        {label:"The war up close", desc:"O.R. marathons, bug-outs, incoming wounded"},
  experiment: {label:"Format experiment", desc:"The show breaking its own rules"},
  letters:    {label:"Letter home", desc:"The \"Dear Dad\" frame and its descendants"},
  twoparter:  {label:"Two-parter"},
  hour:       {label:"Hour-long", desc:"Aired as a one-hour special"},
  bottle:     {label:"Bottle episode", desc:"One room, one bus, one cave"},
  milestone:  {label:"Milestone", desc:"Arrivals, departures and the days that changed the show"},
  xmas:       {label:"Christmas / holidays", desc:"The 4077th does the holidays"},
  classic:    {label:"Classic standalone", desc:"A regular week at the 4077th"},
  sidney:     {label:"Sidney Freedman", desc:"The psychiatrist episodes"},
  flagg:      {label:"Colonel Flagg", desc:"Counter-intelligence, allegedly"},
  hawkeye:    {label:"Hawkeye spotlight"},
  trapper:    {label:"Trapper spotlight"},
  bj:         {label:"B.J. spotlight"},
  henry:      {label:"Henry Blake spotlight"},
  potter:     {label:"Colonel Potter spotlight"},
  frank:      {label:"Frank Burns spotlight"},
  winchester: {label:"Winchester spotlight"},
  margaret:   {label:"Margaret spotlight"},
  radar:      {label:"Radar spotlight"},
  klinger:    {label:"Klinger spotlight"},
  mulcahy:    {label:"Father Mulcahy spotlight"},
};

window.EP_TAGS = {
  // season 1
  "1.1":   ["fanfav","hawkeye"],
  "1.2":   ["classic","henry"],
  "1.3":   ["classic","funny","trapper"],
  "1.4":   ["fanfav","hawkeye","milestone"],
  "1.5":   ["classic","hawkeye"],
  "1.6":   ["fanfav","funny","experiment","hawkeye"],
  "1.7":   ["funny","classic"],
  "1.8":   ["classic","war"],
  "1.9":   ["henry","funny"],
  "1.10":  ["funny","classic"],
  "1.11":  ["classic","frank"],
  "1.12":  ["fanfav","letters","xmas"],
  "1.13":  ["funny","classic"],
  "1.14":  ["radar","classic"],
  "1.15":  ["fanfav","funny","radar"],
  "1.16":  ["classic","funny"],
  "1.17":  ["fanfav","heavy","war","hawkeye","milestone"],
  "1.18":  ["letters","funny"],
  "1.19":  ["funny","classic"],
  "1.20":  ["fanfav","funny","war"],
  "1.21":  ["hawkeye","war"],
  "1.22":  ["frank","funny"],
  "1.23":  ["war","classic"],
  "1.24":  ["war","classic"],
  // season 2
  "2.1":   ["classic","henry"],
  "2.2":   ["fanfav","funny"],
  "2.3":   ["sidney","radar","milestone"],
  "2.4":   ["war","classic"],
  "2.5":   ["hawkeye","war"],
  "2.6":   ["trapper","heavy"],
  "2.7":   ["classic","war"],
  "2.8":   ["fanfav","henry","funny"],
  "2.9":   ["letters"],
  "2.10":  ["fanfav","funny","war"],
  "2.11":  ["hawkeye","funny"],
  "2.12":  ["funny","classic"],
  "2.13":  ["flagg","funny","fanfav"],
  "2.14":  ["margaret","classic"],
  "2.15":  ["classic","funny"],
  "2.16":  ["henry","funny"],
  "2.17":  ["funny","classic"],
  "2.18":  ["funny","classic"],
  "2.19":  ["classic","war"],
  "2.20":  ["classic","funny"],
  "2.21":  ["funny","classic"],
  "2.22":  ["fanfav","hawkeye","frank"],
  "2.23":  ["letters","funny"],
  "2.24":  ["flagg","funny"],
  // season 3
  "3.1":   ["fanfav","funny","milestone"],
  "3.2":   ["war","classic"],
  "3.3":   ["flagg","classic"],
  "3.4":   ["funny","classic"],
  "3.5":   ["experiment","war","fanfav"],
  "3.6":   ["funny","radar"],
  "3.7":   ["trapper","classic"],
  "3.8":   ["mulcahy","radar","funny"],
  "3.9":   ["funny","frank"],
  "3.10":  ["funny","classic"],
  "3.11":  ["fanfav","funny","hawkeye"],
  "3.12":  ["war","classic"],
  "3.13":  ["radar","heavy"],
  "3.14":  ["mulcahy","funny"],
  "3.15":  ["war","classic"],
  "3.16":  ["milestone","funny"],
  "3.17":  ["hawkeye","classic"],
  "3.18":  ["frank","margaret","funny"],
  "3.19":  ["war","margaret","heavy"],
  "3.20":  ["classic","funny"],
  "3.21":  ["funny","classic"],
  "3.22":  ["classic","radar"],
  "3.23":  ["flagg","funny"],
  "3.24":  ["fanfav","heavy","henry","milestone"],
  // season 4
  "4.1":   ["milestone","bj","hour","fanfav"],
  "4.2":   ["milestone","potter","fanfav"],
  "4.3":   ["war","classic"],
  "4.4":   ["hawkeye","funny"],
  "4.5":   ["funny","classic"],
  "4.6":   ["fanfav","funny","bottle"],
  "4.7":   ["potter","letters"],
  "4.8":   ["heavy","war"],
  "4.9":   ["sidney","heavy","fanfav"],
  "4.10":  ["letters","bj"],
  "4.11":  ["classic","funny"],
  "4.12":  ["funny","radar","frank"],
  "4.13":  ["potter","classic"],
  "4.14":  ["letters","funny"],
  "4.15":  ["potter","radar","funny"],
  "4.16":  ["letters","radar"],
  "4.17":  ["frank","classic"],
  "4.18":  ["experiment","hawkeye","fanfav","bottle"],
  "4.19":  ["classic","war"],
  "4.20":  ["frank","funny","fanfav"],
  "4.21":  ["classic","war"],
  "4.22":  ["hawkeye","heavy"],
  "4.23":  ["war","classic"],
  "4.24":  ["experiment","fanfav","war","milestone"],
  // season 5
  "5.1":   ["hour","war","fanfav"],
  "5.2":   ["margaret","milestone"],
  "5.3":   ["hawkeye","fanfav","heavy"],
  "5.4":   ["radar","funny"],
  "5.5":   ["margaret","fanfav","heavy"],
  "5.6":   ["margaret","funny"],
  "5.7":   ["sidney","letters","fanfav"],
  "5.8":   ["mulcahy","war"],
  "5.9":   ["classic","war"],
  "5.10":  ["potter","hawkeye","funny"],
  "5.11":  ["potter","funny"],
  "5.12":  ["funny","classic"],
  "5.13":  ["hawkeye","sidney","heavy"],
  "5.14":  ["radar","funny"],
  "5.15":  ["funny","classic"],
  "5.16":  ["classic","funny"],
  "5.17":  ["war","heavy"],
  "5.18":  ["bj","classic"],
  "5.19":  ["mulcahy","classic"],
  "5.20":  ["classic","funny"],
  "5.21":  ["fanfav","funny","experiment"],
  "5.22":  ["heavy","war"],
  "5.23":  ["war","fanfav"],
  "5.24":  ["margaret","milestone","funny"],
  // season 6
  "6.1":   ["milestone","winchester","hour","fanfav"],
  "6.2":   ["radar","hawkeye","heavy"],
  "6.3":   ["bj","funny"],
  "6.4":   ["sidney","fanfav","heavy"],
  "6.5":   ["winchester","letters","funny"],
  "6.6":   ["funny","classic"],
  "6.7":   ["hawkeye","heavy","fanfav"],
  "6.8":   ["funny","classic"],
  "6.9":   ["margaret","radar","classic"],
  "6.10":  ["funny","classic"],
  "6.11":  ["winchester","heavy"],
  "6.12":  ["twoparter","hawkeye","margaret","fanfav"],
  "6.13":  ["twoparter","hawkeye","margaret","fanfav"],
  "6.14":  ["klinger","funny"],
  "6.15":  ["winchester","funny"],
  "6.16":  ["classic","funny"],
  "6.17":  ["mulcahy","classic"],
  "6.18":  ["radar","war","fanfav"],
  "6.19":  ["margaret","funny"],
  "6.20":  ["letters","funny"],
  "6.21":  ["margaret","classic"],
  "6.22":  ["potter","classic"],
  "6.23":  ["winchester","funny"],
  "6.24":  ["funny","classic"],
  // season 7
  "7.1":   ["hawkeye","funny"],
  "7.2":   ["war","funny"],
  "7.3":   ["potter","classic"],
  "7.4":   ["experiment","classic"],
  "7.5":   ["sidney","classic"],
  "7.6":   ["funny","klinger"],
  "7.7":   ["classic","war"],
  "7.8":   ["winchester","funny"],
  "7.9":   ["funny","margaret"],
  "7.10":  ["experiment","fanfav","war"],
  "7.11":  ["letters","winchester"],
  "7.12":  ["war","heavy"],
  "7.13":  ["funny","classic"],
  "7.14":  ["mulcahy","letters","xmas","fanfav","heavy"],
  "7.15":  ["bj","heavy"],
  "7.16":  ["hawkeye","margaret","fanfav"],
  "7.17":  ["potter","classic"],
  "7.18":  ["potter","funny"],
  "7.19":  ["margaret","milestone"],
  "7.20":  ["funny","bottle"],
  "7.21":  ["flagg","funny","fanfav"],
  "7.22":  ["hawkeye","bj","heavy","fanfav"],
  "7.23":  ["funny","classic"],
  "7.24":  ["klinger","classic"],
  "7.25":  ["fanfav","funny"],
  // season 8
  "8.1":   ["classic","funny"],
  "8.2":   ["margaret","heavy"],
  "8.3":   ["war","heavy","hawkeye"],
  "8.4":   ["twoparter","radar","milestone","fanfav"],
  "8.5":   ["twoparter","radar","milestone","fanfav","heavy"],
  "8.6":   ["bj","klinger","heavy","fanfav"],
  "8.7":   ["mulcahy","classic"],
  "8.8":   ["klinger","classic"],
  "8.9":   ["winchester","funny"],
  "8.10":  ["funny","klinger","hawkeye"],
  "8.11":  ["experiment","war","fanfav","heavy"],
  "8.12":  ["klinger","letters","funny"],
  "8.13":  ["mulcahy","classic"],
  "8.14":  ["winchester","classic"],
  "8.15":  ["heavy","classic"],
  "8.16":  ["winchester","funny"],
  "8.17":  ["heavy","war"],
  "8.18":  ["potter","heavy","fanfav"],
  "8.19":  ["winchester","heavy","fanfav"],
  "8.20":  ["hawkeye","winchester","classic"],
  "8.21":  ["heavy","classic"],
  "8.22":  ["experiment","heavy","fanfav"],
  "8.23":  ["bj","classic"],
  "8.24":  ["hawkeye","funny"],
  "8.25":  ["funny","classic"],
  // season 9
  "9.1":   ["hawkeye","war"],
  "9.2":   ["experiment","fanfav","letters"],
  "9.3":   ["funny","classic"],
  "9.4":   ["margaret","funny"],
  "9.5":   ["xmas","heavy","fanfav","winchester"],
  "9.6":   ["experiment","fanfav","funny"],
  "9.7":   ["klinger","funny"],
  "9.8":   ["klinger","classic"],
  "9.9":   ["hawkeye","funny"],
  "9.10":  ["winchester","klinger","classic"],
  "9.11":  ["funny","classic"],
  "9.12":  ["hawkeye","heavy"],
  "9.13":  ["funny","classic"],
  "9.14":  ["bj","heavy","fanfav"],
  "9.15":  ["margaret","classic"],
  "9.16":  ["potter","funny"],
  "9.17":  ["hawkeye","sidney","heavy"],
  "9.18":  ["mulcahy","heavy","fanfav"],
  "9.19":  ["potter","classic"],
  "9.20":  ["winchester","heavy","fanfav"],
  // season 10
  "10.1":  ["funny","classic"],
  "10.2":  ["heavy","war"],
  "10.3":  ["potter","classic"],
  "10.4":  ["hawkeye","letters","funny"],
  "10.5":  ["bj","heavy"],
  "10.6":  ["winchester","classic"],
  "10.7":  ["twoparter","klinger","funny"],
  "10.8":  ["twoparter","klinger","funny"],
  "10.9":  ["xmas","funny","fanfav"],
  "10.10": ["experiment","heavy","fanfav","klinger"],
  "10.11": ["margaret","funny"],
  "10.12": ["war","classic"],
  "10.13": ["mulcahy","funny"],
  "10.14": ["winchester","heavy","war"],
  "10.15": ["potter","sidney","heavy"],
  "10.16": ["hawkeye","war","fanfav","heavy"],
  "10.17": ["funny","classic"],
  "10.18": ["heavy","classic"],
  "10.19": ["winchester","hawkeye","heavy","fanfav"],
  "10.20": ["funny","experiment"],
  "10.21": ["klinger","funny"],
  // season 11
  "11.1":  ["classic","margaret"],
  "11.2":  ["funny","fanfav"],
  "11.3":  ["winchester","classic"],
  "11.4":  ["bj","funny","fanfav"],
  "11.5":  ["hawkeye","heavy"],
  "11.6":  ["war","heavy","klinger"],
  "11.7":  ["potter","funny"],
  "11.8":  ["funny","fanfav"],
  "11.9":  ["winchester","heavy"],
  "11.10": ["classic","funny"],
  "11.11": ["potter","classic"],
  "11.12": ["margaret","classic"],
  "11.13": ["potter","classic"],
  "11.14": ["classic","war"],
  "11.15": ["fanfav","milestone","margaret"],
  "11.16": ["fanfav","heavy","milestone","hour","sidney","war"],
};
