// Babylon 5 — episode tags. Keys are TVmaze season.episode as used in episodes.json.
// "1.0" is The Gathering (1993 pilot movie) and "5.0" is In the Beginning (1998 prequel movie).
// Season premieres and finales are auto-tagged by the engine and are not listed here.
window.TAG_DEFS = {
  fanfav:    {label:"Fan favorite", desc:"The hours people rewatch, quote and argue about"},
  milestone: {label:"Milestone", desc:"A hinge the five-year story turns on"},
  arc:       {label:"Arc episode", desc:"Moves the big story — skip it and you'll be lost"},
  standalone:{label:"Standalone", desc:"A self-contained week on the station"},
  heavy:     {label:"Gut-punch", desc:"The ones that hurt"},
  battle:    {label:"Space battle", desc:"Starfuries, White Stars and the big fleet actions"},
  prophecy:  {label:"Prophecy & time", desc:"Visions, flash-forwards, Babylon 4 and the Valen mystery"},
  experiment:{label:"Format experiment", desc:"The show breaking its own shape — news documentary, one room, the far future"},
  twopart:   {label:"Two-parter", desc:"Half of a matched pair"},
  movie:     {label:"TV movie", desc:"Feature-length — the pilot and the prequel"},
  psi:       {label:"Psi Corps & telepaths", desc:"Bester, the Corps, rogue telepaths, Talia, Lyta and Byron"},

  sinclair: {label:"Sinclair spotlight"},
  sheridan: {label:"Sheridan spotlight"},
  delenn:   {label:"Delenn spotlight"},
  ivanova:  {label:"Ivanova spotlight"},
  garibaldi:{label:"Garibaldi spotlight"},
  franklin: {label:"Franklin spotlight"},
  londo:    {label:"Londo spotlight"},
  gkar:     {label:"G'Kar spotlight"},
  bester:   {label:"Bester episode", desc:"Walter Koenig's Psi Cop drops in"},
};

window.EP_TAGS = {
  // The Gathering + year 1
  "1.0":  ["movie","sinclair","milestone"],
  "1.1":  ["arc","londo","gkar"],
  "1.2":  ["standalone","delenn"],
  "1.3":  ["standalone","londo"],
  "1.4":  ["standalone","franklin"],
  "1.5":  ["standalone","sinclair","gkar"],
  "1.6":  ["psi","bester"],
  "1.7":  ["standalone","ivanova","londo"],
  "1.8":  ["fanfav","arc","sinclair","prophecy"],
  "1.9":  ["standalone"],
  "1.10": ["standalone","franklin","heavy"],
  "1.11": ["standalone","garibaldi"],
  "1.12": ["standalone","sinclair","gkar"],
  "1.13": ["fanfav","arc","milestone","londo"],
  "1.14": ["standalone","garibaldi","ivanova"],
  "1.15": ["standalone"],
  "1.16": ["psi","garibaldi"],
  "1.17": ["psi","ivanova","delenn"],
  "1.18": ["twopart","arc"],
  "1.19": ["twopart","arc"],
  "1.20": ["fanfav","arc","prophecy","sinclair"],
  "1.21": ["standalone","franklin"],
  "1.22": ["fanfav","arc","milestone","heavy"],

  // year 2
  "2.1":  ["arc","milestone","sheridan","battle"],
  "2.2":  ["arc","delenn","garibaldi"],
  "2.3":  ["arc","londo","ivanova"],
  "2.4":  ["standalone","sheridan"],
  "2.5":  ["standalone"],
  "2.6":  ["standalone","psi"],
  "2.7":  ["standalone","londo","psi"],
  "2.8":  ["psi","bester"],
  "2.9":  ["fanfav","arc","milestone","londo","gkar"],
  "2.10": ["standalone","franklin"],
  "2.11": ["arc","sheridan","delenn"],
  "2.12": ["standalone","gkar","ivanova"],
  "2.13": ["arc","sheridan"],
  "2.14": ["standalone","sheridan"],
  "2.15": ["experiment","arc"],
  "2.16": ["fanfav","arc","sheridan"],
  "2.17": ["standalone","londo"],
  "2.18": ["heavy","franklin"],
  "2.19": ["arc","psi","heavy","ivanova"],
  "2.20": ["fanfav","arc","milestone","heavy","gkar","londo"],
  "2.21": ["fanfav","arc","delenn","sheridan"],
  "2.22": ["fanfav","arc","battle"],

  // year 3
  "3.1":  ["arc","battle"],
  "3.2":  ["standalone"],
  "3.3":  ["standalone","gkar","franklin"],
  "3.4":  ["fanfav","heavy","standalone"],
  "3.5":  ["arc","ivanova"],
  "3.6":  ["arc","gkar","psi","bester"],
  "3.7":  ["standalone","franklin"],
  "3.8":  ["arc","sheridan","delenn","battle"],
  "3.9":  ["arc","milestone","londo"],
  "3.10": ["fanfav","arc","milestone","battle","sheridan"],
  "3.11": ["arc","delenn","sheridan"],
  "3.12": ["standalone","londo"],
  "3.13": ["standalone"],
  "3.14": ["arc","psi","bester"],
  "3.15": ["fanfav","arc","heavy","milestone"],
  "3.16": ["fanfav","twopart","prophecy","sinclair"],
  "3.17": ["fanfav","twopart","prophecy","sinclair","milestone"],
  "3.18": ["arc","psi","franklin"],
  "3.19": ["standalone","garibaldi"],
  "3.20": ["fanfav","arc","londo"],
  "3.21": ["fanfav","arc","battle","franklin"],
  "3.22": ["fanfav","arc","milestone","sheridan"],

  // year 4
  "4.1":  ["arc","londo","delenn"],
  "4.2":  ["arc","gkar","garibaldi"],
  "4.3":  ["arc","sheridan","gkar"],
  "4.4":  ["arc","sheridan"],
  "4.5":  ["fanfav","arc","gkar","londo"],
  "4.6":  ["fanfav","arc","milestone","battle"],
  "4.7":  ["arc","bester","psi","garibaldi"],
  "4.8":  ["experiment","arc"],
  "4.9":  ["arc","delenn"],
  "4.10": ["arc","franklin","garibaldi"],
  "4.11": ["arc","delenn","franklin"],
  "4.12": ["arc","garibaldi","ivanova"],
  "4.13": ["arc","sheridan","delenn"],
  "4.14": ["arc","delenn","psi","bester"],
  "4.15": ["arc","milestone","battle","sheridan"],
  "4.16": ["arc","garibaldi"],
  "4.17": ["fanfav","arc","garibaldi","bester"],
  "4.18": ["experiment","heavy","sheridan"],
  "4.19": ["arc","battle","ivanova","garibaldi"],
  "4.20": ["fanfav","arc","milestone","battle","heavy","ivanova"],
  "4.21": ["arc","milestone","heavy"],
  "4.22": ["experiment","prophecy"],

  // In the Beginning + year 5
  "5.0":  ["movie","londo","prophecy"],
  "5.1":  ["arc","psi","sheridan"],
  "5.2":  ["experiment","londo"],
  "5.3":  ["arc","sheridan","gkar"],
  "5.4":  ["experiment","standalone","battle"],
  "5.5":  ["standalone"],
  "5.6":  ["arc","psi","bester"],
  "5.7":  ["arc","psi","franklin"],
  "5.8":  ["fanfav","standalone"],
  "5.9":  ["arc","psi","londo"],
  "5.10": ["arc","psi","bester","gkar"],
  "5.11": ["arc","psi","heavy","bester"],
  "5.12": ["arc","garibaldi","gkar"],
  "5.13": ["experiment","psi","bester"],
  "5.14": ["arc"],
  "5.15": ["arc","garibaldi"],
  "5.16": ["arc","londo","gkar"],
  "5.17": ["arc","battle"],
  "5.18": ["fanfav","arc","milestone","heavy","londo"],
  "5.19": ["arc","garibaldi","gkar","psi"],
  "5.20": ["arc","twopart","garibaldi"],
  "5.21": ["arc","twopart","heavy"],
  "5.22": ["fanfav","heavy","milestone","sheridan"],
};
