// Stargate SG-1 — episode tags. Season premieres and finales are auto-tagged by the engine, so they aren't listed here.
// Keys are the season.episode numbers used in episodes.json (the films are 10.21 and 10.22).
// goauld / ori / tokra / asgard / earthpol / bratac were derived from TVmaze guest-cast credits; the rest are hand-picked.
window.TAG_DEFS = {
  fanfav:      {label:"Fan favorite", desc:"The ones people rewatch first"},
  heavy:       {label:"Gut-punch", desc:"Deaths, departures and the ones that hurt"},
  funny:       {label:"Comedy", desc:"Time loops, body swaps and Wormhole X-Treme!"},
  meta:        {label:"Meta / self-parody", desc:"The show makes fun of itself"},
  timey:       {label:"Time travel & alternate realities", desc:"Loops, paradoxes, other timelines and quantum mirrors"},
  twoparter:   {label:"Two-parter"},
  milestone:   {label:"Milestone", desc:"Arrivals, departures and the days that changed the show"},
  film:        {label:"Direct-to-DVD film", desc:"The Ark of Truth and Continuum (2008)"},
  goauld:      {label:"Goa'uld", desc:"A System Lord on screen — Apophis, Anubis, Ba'al, Yu and the rest (from the guest cast)"},
  replicators: {label:"Replicators", desc:"The bugs, the human-form Replicators and RepliCarter"},
  ori:         {label:"The Ori", desc:"Priors, Adria and the crusade (from the guest cast)"},
  tokra:       {label:"Tok'ra", desc:"Jacob, Selmak, Martouf and the resistance (from the guest cast)"},
  asgard:      {label:"Asgard", desc:"Thor and his people (from the guest cast)"},
  earthpol:    {label:"Earth politics", desc:"Maybourne, Kinsey, Woolsey — the NID and Washington (from the guest cast)"},
  bratac:      {label:"Bra'tac", desc:"Teal'c's mentor (from the guest cast)"},
  classic:     {label:"Classic standalone", desc:"Planet of the week"},
  oneill:      {label:"O'Neill spotlight"},
  carter:      {label:"Carter spotlight"},
  daniel:      {label:"Daniel spotlight"},
  tealc:       {label:"Teal'c spotlight"},
  jonas:       {label:"Jonas Quinn spotlight"},
  mitchell:    {label:"Mitchell spotlight"},
  vala:        {label:"Vala spotlight"},
};

window.EP_TAGS = {
  "1.1": ["goauld"],
  "1.2": ["classic"],
  "1.3": ["classic"],
  "1.4": ["classic"],
  "1.5": ["classic"],
  "1.6": ["oneill"],
  "1.7": ["goauld"],
  "1.8": ["classic"],
  "1.9": ["asgard"],
  "1.10": ["classic"],
  "1.11": ["bratac", "tealc"],
  "1.12": ["classic"],
  "1.13": ["goauld"],
  "1.14": ["carter"],
  "1.15": ["goauld"],
  "1.16": ["earthpol"],
  "1.17": ["oneill", "carter"],
  "1.18": ["classic"],
  "1.19": ["timey", "fanfav", "daniel"],
  "1.20": ["earthpol"],
  "1.21": ["goauld", "twoparter"],
  "2.1": ["goauld", "bratac", "twoparter"],
  "2.2": ["carter"],
  "2.3": ["classic"],
  "2.4": ["classic"],
  "2.5": ["classic"],
  "2.6": ["goauld", "asgard"],
  "2.7": ["classic"],
  "2.8": ["goauld", "bratac", "tealc"],
  "2.9": ["goauld", "tokra", "daniel"],
  "2.10": ["earthpol"],
  "2.11": ["tokra", "twoparter"],
  "2.12": ["tokra", "twoparter"],
  "2.13": ["classic"],
  "2.14": ["earthpol"],
  "2.15": ["classic"],
  "2.16": ["timey"],
  "2.17": ["funny"],
  "2.18": ["goauld", "tokra"],
  "2.19": ["classic"],
  "2.20": ["tokra"],
  "2.21": ["timey", "fanfav"],
  "2.22": ["goauld", "twoparter"],
  "3.1": ["goauld", "bratac", "twoparter"],
  "3.2": ["tokra"],
  "3.3": ["goauld", "asgard"],
  "3.4": ["daniel"],
  "3.5": ["ori"],
  "3.6": ["goauld", "timey"],
  "3.7": ["classic"],
  "3.8": ["classic"],
  "3.9": ["goauld"],
  "3.10": ["heavy", "daniel"],
  "3.11": ["classic"],
  "3.12": ["goauld", "tokra", "twoparter", "carter"],
  "3.13": ["goauld", "tokra", "twoparter", "fanfav"],
  "3.14": ["earthpol"],
  "3.15": ["classic"],
  "3.16": ["funny"],
  "3.17": ["oneill"],
  "3.18": ["earthpol", "oneill"],
  "3.19": ["classic"],
  "3.20": ["bratac", "daniel"],
  "3.21": ["classic"],
  "3.22": ["asgard", "replicators", "twoparter"],
  "4.1": ["asgard", "replicators", "twoparter"],
  "4.2": ["classic"],
  "4.3": ["tokra"],
  "4.4": ["goauld", "tokra"],
  "4.5": ["tokra"],
  "4.6": ["timey", "funny", "fanfav", "oneill"],
  "4.7": ["earthpol"],
  "4.8": ["daniel"],
  "4.9": ["classic"],
  "4.10": ["classic"],
  "4.11": ["classic"],
  "4.12": ["goauld", "tokra"],
  "4.13": ["classic"],
  "4.14": ["goauld", "tokra", "tealc"],
  "4.15": ["earthpol"],
  "4.16": ["earthpol", "timey", "fanfav"],
  "4.17": ["goauld", "tokra"],
  "4.18": ["classic"],
  "4.19": ["carter"],
  "4.20": ["carter"],
  "4.21": ["goauld"],
  "4.22": ["goauld", "tokra", "twoparter"],
  "5.1": ["goauld", "tokra", "replicators", "twoparter"],
  "5.2": ["goauld", "bratac"],
  "5.3": ["classic"],
  "5.4": ["classic"],
  "5.5": ["asgard", "carter"],
  "5.6": ["goauld"],
  "5.7": ["classic"],
  "5.8": ["classic"],
  "5.9": ["classic"],
  "5.10": ["earthpol", "timey", "fanfav"],
  "5.11": ["ori", "earthpol"],
  "5.12": ["funny", "meta", "fanfav", "milestone"],
  "5.13": ["classic"],
  "5.14": ["ori", "earthpol"],
  "5.15": ["goauld", "tokra", "twoparter"],
  "5.16": ["goauld", "tokra", "twoparter"],
  "5.17": ["asgard"],
  "5.18": ["goauld", "bratac", "tealc"],
  "5.19": ["replicators"],
  "5.20": ["classic"],
  "5.21": ["tokra", "heavy", "fanfav", "milestone", "daniel"],
  "5.22": ["goauld", "asgard"],
  "6.1": ["goauld", "bratac", "twoparter", "milestone"],
  "6.2": ["bratac", "twoparter", "jonas"],
  "6.3": ["tokra"],
  "6.4": ["classic"],
  "6.5": ["classic"],
  "6.6": ["goauld", "oneill"],
  "6.7": ["jonas"],
  "6.8": ["funny", "fanfav"],
  "6.9": ["tokra", "bratac"],
  "6.10": ["tokra"],
  "6.11": ["ori", "asgard"],
  "6.12": ["asgard", "replicators"],
  "6.13": ["classic"],
  "6.14": ["earthpol"],
  "6.15": ["earthpol"],
  "6.16": ["goauld"],
  "6.17": ["asgard", "earthpol"],
  "6.18": ["classic"],
  "6.19": ["goauld", "tokra", "bratac", "tealc"],
  "6.20": ["classic"],
  "6.21": ["jonas"],
  "6.22": ["goauld", "fanfav", "daniel"],
  "7.1": ["goauld", "twoparter", "milestone", "daniel"],
  "7.2": ["goauld", "twoparter", "milestone"],
  "7.3": ["tokra", "asgard"],
  "7.4": ["bratac", "tealc"],
  "7.5": ["classic"],
  "7.6": ["classic"],
  "7.7": ["classic"],
  "7.8": ["classic"],
  "7.9": ["classic"],
  "7.10": ["tealc"],
  "7.11": ["tokra", "bratac", "twoparter"],
  "7.12": ["goauld", "tokra", "bratac", "twoparter"],
  "7.13": ["tokra", "carter"],
  "7.14": ["jonas"],
  "7.15": ["classic"],
  "7.16": ["tokra"],
  "7.17": ["earthpol", "twoparter", "fanfav"],
  "7.18": ["earthpol", "twoparter", "heavy", "fanfav", "milestone"],
  "7.19": ["classic"],
  "7.20": ["earthpol"],
  "7.21": ["goauld", "earthpol", "bratac", "twoparter", "fanfav", "oneill"],
  "7.22": ["goauld", "earthpol", "bratac", "twoparter", "fanfav", "oneill"],
  "8.1": ["goauld", "asgard", "replicators", "twoparter"],
  "8.2": ["goauld", "asgard", "replicators", "twoparter", "milestone"],
  "8.3": ["classic"],
  "8.4": ["goauld", "oneill"],
  "8.5": ["daniel"],
  "8.6": ["classic"],
  "8.7": ["classic"],
  "8.8": ["asgard"],
  "8.9": ["bratac", "tealc"],
  "8.10": ["classic"],
  "8.11": ["asgard", "replicators", "carter"],
  "8.12": ["daniel", "vala"],
  "8.13": ["earthpol", "funny"],
  "8.14": ["earthpol"],
  "8.15": ["funny"],
  "8.16": ["goauld", "tokra", "asgard", "bratac", "replicators", "twoparter"],
  "8.17": ["goauld", "tokra", "bratac", "replicators", "twoparter", "milestone"],
  "8.18": ["goauld", "tokra", "bratac", "heavy", "fanfav", "milestone", "carter"],
  "8.19": ["twoparter", "timey", "fanfav"],
  "8.20": ["goauld", "twoparter", "timey", "fanfav"],
  "9.1": ["twoparter", "fanfav", "milestone", "mitchell", "vala"],
  "9.2": ["ori", "twoparter", "vala"],
  "9.3": ["ori"],
  "9.4": ["classic"],
  "9.5": ["ori", "vala"],
  "9.6": ["ori"],
  "9.7": ["goauld"],
  "9.8": ["ori"],
  "9.9": ["earthpol"],
  "9.10": ["ori", "bratac", "twoparter"],
  "9.11": ["ori", "bratac", "twoparter"],
  "9.12": ["mitchell"],
  "9.13": ["tokra", "timey"],
  "9.14": ["goauld", "bratac"],
  "9.15": ["classic"],
  "9.16": ["goauld"],
  "9.17": ["earthpol"],
  "9.18": ["ori"],
  "9.19": ["ori"],
  "9.20": ["twoparter"],
  "10.1": ["ori", "earthpol", "bratac", "twoparter", "milestone", "vala"],
  "10.2": ["earthpol"],
  "10.3": ["fanfav"],
  "10.4": ["goauld"],
  "10.5": ["classic"],
  "10.6": ["funny", "meta", "fanfav", "milestone"],
  "10.7": ["ori", "bratac"],
  "10.8": ["vala"],
  "10.9": ["classic"],
  "10.10": ["goauld", "ori", "twoparter"],
  "10.11": ["goauld", "ori", "twoparter"],
  "10.12": ["ori", "carter"],
  "10.13": ["timey"],
  "10.14": ["ori", "earthpol", "daniel"],
  "10.15": ["classic"],
  "10.16": ["funny", "fanfav"],
  "10.17": ["bratac", "tealc"],
  "10.18": ["classic"],
  "10.19": ["goauld", "ori"],
  "10.20": ["asgard", "timey", "heavy", "fanfav", "milestone"],
  "10.21": ["ori", "fanfav", "film"],
  "10.22": ["goauld", "timey", "film"],
};
